import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { connect, type Database } from "@tursodatabase/database";
import { DEFAULT_OSS_ACCOUNT_ID, DEFAULT_OSS_ORGANIZATION_ID } from "../../../src/CONSTANTS";
import {
  fxCanvasCanEdit,
  fxCanvasFindById,
  fxCanvasFindByName,
  fxCanvasHasOwnerRole,
  fxCanvasListAll,
  fxCanvasListMembers,
} from "../../../src/DbServiceTurso/fx.canvas";
import { txRunMigrations } from "../../../src/DbServiceTurso/tx.migrations";
import { EXPECTED_APPLICATION_TABLES } from "../../../src/schema/expected-schema";
import { TEST_TENANT } from "../tenant.fixture";

const ACCOUNT_EDITOR = "00000000-0000-4000-8000-000000000111";
const ACCOUNT_VIEWER = "00000000-0000-4000-8000-000000000112";
const ACCOUNT_OUTSIDER = "00000000-0000-4000-8000-000000000113";
const CANVAS_ALPHA = "00000000-0000-4000-8000-000000000121";
const CANVAS_BETA = "00000000-0000-4000-8000-000000000122";
const CANVAS_PRIVATE = "00000000-0000-4000-8000-000000000123";

function tenantFor(accountId: string) {
  return { ...TEST_TENANT, accountId };
}

async function inMemoryDb(): Promise<Database> {
  // @ts-expect-error custom_types not typed yet
  return connect(":memory:", { experimental: ["custom_types"] });
}

async function seedCanvasRows(db: Database): Promise<void> {
  await txRunMigrations({ db, Bun }, {
    applicationVersion: "test",
    appliedAtMs: 1,
    expectedApplicationTables: EXPECTED_APPLICATION_TABLES,
  });
  const insertAccount = await db.prepare(`
    INSERT INTO accounts (
      id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms
    ) VALUES (?, 'user', ?, 'active', 0, 1, 1)
  `);
  const insertMembership = await db.prepare(`
    INSERT INTO organization_memberships (
      org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
    ) VALUES (?, ?, 'member', 'active', 1, 1, 1)
  `);
  for (const [id, name] of [
    [ACCOUNT_EDITOR, "Editor Account"],
    [ACCOUNT_VIEWER, "Viewer Account"],
    [ACCOUNT_OUTSIDER, "Outsider Account"],
  ] as const) {
    await insertAccount.run(id, name);
    await insertMembership.run(DEFAULT_OSS_ORGANIZATION_ID, id);
  }

  const insertCanvas = await db.prepare(`
    INSERT INTO canvases (
      org_id, id, name, access_policy, created_by_account_id, created_at_ms, updated_at_ms
    ) VALUES (?, ?, ?, 'restricted', ?, 1, 1)
  `);
  const insertDocument = await db.prepare(`
    INSERT INTO collaboration_documents (
      org_id, id, canvas_id, widget_instance_id, automerge_url, partition_key,
      created_at_ms, updated_at_ms
    ) VALUES (?, ?, ?, NULL, ?, ?, 1, 1)
  `);
  for (const [id, name, url] of [
    [CANVAS_ALPHA, "Alpha", "automerge:alpha"],
    [CANVAS_BETA, "Beta", "automerge:beta"],
    [CANVAS_PRIVATE, "Private", "automerge:private"],
  ] as const) {
    await insertCanvas.run(DEFAULT_OSS_ORGANIZATION_ID, id, name, DEFAULT_OSS_ACCOUNT_ID);
    await insertDocument.run(DEFAULT_OSS_ORGANIZATION_ID, id, id, url, DEFAULT_OSS_ORGANIZATION_ID);
  }

  const insertMember = await db.prepare(`
    INSERT INTO canvas_members (
      org_id, canvas_id, account_id, role, created_at_ms, updated_at_ms
    ) VALUES (?, ?, ?, ?, 1, 1)
  `);
  await insertMember.run(DEFAULT_OSS_ORGANIZATION_ID, CANVAS_ALPHA, DEFAULT_OSS_ACCOUNT_ID, "owner");
  await insertMember.run(DEFAULT_OSS_ORGANIZATION_ID, CANVAS_ALPHA, ACCOUNT_EDITOR, "editor");
  await insertMember.run(DEFAULT_OSS_ORGANIZATION_ID, CANVAS_ALPHA, ACCOUNT_VIEWER, "viewer");
  await insertMember.run(DEFAULT_OSS_ORGANIZATION_ID, CANVAS_BETA, ACCOUNT_EDITOR, "owner");
}

describe("fx.canvas", () => {
  let db!: Database;

  beforeEach(async () => {
    db = await inMemoryDb();
    await seedCanvasRows(db);
  });

  afterEach(async () => {
    await db.close();
  });

  test("always limits canvases to the mandatory tenant account", async () => {
    const canvases = await fxCanvasListAll({ db }, { tenant: TEST_TENANT });
    expect(canvases.map((canvas) => canvas.id)).toEqual([CANVAS_ALPHA]);
  });

  test("lists only canvases visible to the account scope", async () => {
    const editorCanvases = await fxCanvasListAll({ db }, { tenant: tenantFor(ACCOUNT_EDITOR) });
    const viewerCanvases = await fxCanvasListAll({ db }, { tenant: tenantFor(ACCOUNT_VIEWER) });
    const outsiderCanvases = await fxCanvasListAll({ db }, { tenant: tenantFor(ACCOUNT_OUTSIDER) });

    expect(editorCanvases.map((canvas) => canvas.id).sort()).toEqual([CANVAS_ALPHA, CANVAS_BETA]);
    expect(viewerCanvases.map((canvas) => canvas.id)).toEqual([CANVAS_ALPHA]);
    expect(outsiderCanvases).toEqual([]);
  });

  test("finds canvas by name only within tenant membership", async () => {
    expect(await fxCanvasFindByName({ db }, { tenant: TEST_TENANT, name: "Alpha" })).toMatchObject({ id: CANVAS_ALPHA });
    expect(await fxCanvasFindByName({ db }, { tenant: TEST_TENANT, name: "Beta" })).toBeNull();
    expect(await fxCanvasFindByName({ db }, { tenant: tenantFor(ACCOUNT_EDITOR), name: "Beta" })).toMatchObject({
      id: CANVAS_BETA,
      automerge_url: "automerge:beta",
    });
  });

  test("finds canvas by id only within tenant membership", async () => {
    expect(await fxCanvasFindById({ db }, { tenant: TEST_TENANT, id: CANVAS_ALPHA })).toMatchObject({ id: CANVAS_ALPHA });
    expect(await fxCanvasFindById({ db }, { tenant: TEST_TENANT, id: CANVAS_BETA })).toBeNull();
    expect(await fxCanvasFindById({ db }, { tenant: tenantFor(ACCOUNT_EDITOR), id: CANVAS_BETA })).toMatchObject({
      id: CANVAS_BETA,
      automerge_url: "automerge:beta",
    });
  });

  test("checks edit and owner permissions from member roles", async () => {
    expect(await fxCanvasCanEdit({ db }, { tenant: TEST_TENANT, canvasId: CANVAS_ALPHA })).toBe(true);
    expect(await fxCanvasCanEdit({ db }, { tenant: tenantFor(ACCOUNT_EDITOR), canvasId: CANVAS_ALPHA })).toBe(true);
    expect(await fxCanvasCanEdit({ db }, { tenant: tenantFor(ACCOUNT_VIEWER), canvasId: CANVAS_ALPHA })).toBe(false);
    expect(await fxCanvasCanEdit({ db }, { tenant: tenantFor(ACCOUNT_OUTSIDER), canvasId: CANVAS_ALPHA })).toBe(false);
    expect(await fxCanvasHasOwnerRole({ db }, { tenant: TEST_TENANT, canvasId: CANVAS_ALPHA })).toBe(true);
    expect(await fxCanvasHasOwnerRole({ db }, { tenant: tenantFor(ACCOUNT_EDITOR), canvasId: CANVAS_ALPHA })).toBe(false);
  });

  test("lists canvas members", async () => {
    const members = await fxCanvasListMembers({ db }, { tenant: TEST_TENANT, canvasId: CANVAS_ALPHA });
    expect(members.map((member) => ({ account_id: member.account_id, role: member.role }))).toEqual([
      { account_id: DEFAULT_OSS_ACCOUNT_ID, role: "owner" },
      { account_id: ACCOUNT_EDITOR, role: "editor" },
      { account_id: ACCOUNT_VIEWER, role: "viewer" },
    ]);
  });
});
