import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { connect, Database } from "@tursodatabase/database";
import { listMigrationFiles } from "../../../src/DbServiceTurso/list-migration-files";
import { txRunMigrations } from "../../../src/DbServiceTurso/tx.migrations";
import path from "node:path"

async function inMemoryDb() {
  // @ts-expect-error custom_types not typed yet
  return connect(":memory:", { experimental: ["custom_types"] });
}

async function expectSqlConstraintFailure(action: () => Promise<unknown>) {
  let error: unknown;

  try {
    await action();
  } catch (caught) {
    error = caught;
  }

  expect(error).toBeInstanceOf(Error);
}

describe("tx.migrations", () => {
  let db!: Database;

  beforeEach(async () => {
    db = await inMemoryDb();
    await db.exec("PRAGMA foreign_keys = ON");
  });

  afterEach(async () => {
    await db.close();
  });

  test("test tables are present", async () => {
    await txRunMigrations({ db, Bun, path }, {});

    const stmt = await db.prepare("select name from sqlite_master where type = 'table' order by name");
    const tables = await stmt.all();
    const tNames = tables.map((table) => table.name);
    expect(tNames).toContain("automerge_repo_data");
    expect(tNames).toContain("accounts");
    expect(tNames).toContain("canvas");
    expect(tNames).toContain("canvas_members");
    expect(tNames).toContain("media_files");
    expect(tNames).toContain("actor_definitions");
    expect(tNames).toContain("actor_instances");
    expect(tNames).toContain("actor_connections");
    expect(tNames).toContain("kv");
    expect(tNames).toContain("migrations");

    const migrationStmt = await db.prepare("select name, hash_hex, applied_at from migrations order by name");
    const migrations = await migrationStmt.all();
    const migrationFiles = listMigrationFiles();
    expect(migrations).toHaveLength(migrationFiles.length);
    expect(migrations.map((migration) => migration.name)).toEqual(
      migrationFiles.map((file) => path.basename(file.path)).sort(),
    );
    for (const migration of migrations) {
      expect(migration.hash_hex).toEqual(expect.any(String));
      expect(migration.hash_hex).not.toBe("");
      expect(migration.applied_at).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
    }
  });

  test("accounts table", async () => {
    await txRunMigrations({ db, Bun, path }, {});

    const insertAccount = await db.prepare("insert into accounts (id, display_name) values (?, ?)");
    await insertAccount.run("account-1", "Test Account");

    const selectAccount = await db.prepare("select id, kind, display_name, role, is_autogenerated, created_at, updated_at from accounts where id = ?");
    const account = await selectAccount.get("account-1");

    expect(account).toEqual({
      id: "account-1",
      kind: "user",
      display_name: "Test Account",
      role: "member",
      is_autogenerated: 1,
      created_at: expect.any(String),
      updated_at: expect.any(String),
    });
    expect(account.created_at).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
    expect(account.updated_at).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);

    await Bun.sleep(1100); // at least 1 second after the update trigger should have fired

    const updateAccount = await db.prepare("update accounts set display_name = ? where id = ?");
    await updateAccount.run("Renamed Account", "account-1");

    const updatedAccount = await selectAccount.get("account-1");
    expect(updatedAccount.updated_at).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
    expect(updatedAccount.updated_at).not.toBe(account.updated_at);
    expect(updatedAccount.created_at).toBe(account.created_at);
  });

  test("canvas tables", async () => {
    await txRunMigrations({ db, Bun, path }, {});

    const insertAccount = await db.prepare("insert into accounts (id, display_name) values (?, ?)");
    await insertAccount.run("account-1", "Test Account");

    const insertCanvas = await db.prepare("insert into canvas (id, name, automerge_url) values (?, ?, ?)");
    await insertCanvas.run("canvas-1", "Test Canvas", "automerge:abc");

    const selectCanvas = await db.prepare("select id, name, automerge_url, created_at from canvas where id = ?");
    const canvas = await selectCanvas.get("canvas-1");

    expect(canvas).toEqual({
      id: "canvas-1",
      name: "Test Canvas",
      automerge_url: "automerge:abc",
      created_at: expect.any(String),
    });
    expect(canvas.created_at).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);

    const insertCanvasMember = await db.prepare("insert into canvas_members (canvas_id, account_id, role) values (?, ?, ?)");
    await insertCanvasMember.run("canvas-1", "account-1", "editor");

    const selectCanvasMember = await db.prepare("select canvas_id, account_id, role, created_at, updated_at from canvas_members where canvas_id = ? and account_id = ?");
    const member = await selectCanvasMember.get("canvas-1", "account-1");

    expect(member).toEqual({
      canvas_id: "canvas-1",
      account_id: "account-1",
      role: "editor",
      created_at: expect.any(String),
      updated_at: expect.any(String),
    });
    expect(member.created_at).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
    expect(member.updated_at).toMatch(/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/);
  });

  test("actor tables accept connected data and enforce constraints", async () => {
    await txRunMigrations({ db, Bun, path }, {});

    const insertCanvas = await db.prepare("insert into canvas (id, name, automerge_url) values (?, ?, ?)");
    await insertCanvas.run("canvas-actor", "Actor Canvas", "automerge:actor");

    const insertDefinition = await db.prepare("insert into actor_definitions (name, slug, manifest_path) values (?, ?, ?)");
    await insertDefinition.run("Counter", "counter", "/actors/counter/vibecanvas.json");

    await expectSqlConstraintFailure(() => insertDefinition.run("Counter Copy", "counter", '"/actors/counter-copy/vibecanvas.json"'));

    const insertInstance = await db.prepare("insert into actor_instances (id, canvas_id, element_id, actor_definition_name, display_name, status, machine_state, machine_context) values (?, ?, ?, ?, ?, ?, ?, ?)");
    await insertInstance.run("actor-1", "canvas-actor", "element-1", "Counter", "Counter A", "created", "idle", '{"count":0}');
    await insertInstance.run("actor-2", "canvas-actor", "element-2", "Counter", "Counter B", "running", "idle", '{"count":10}');

    const selectInstance = await db.prepare("select id, canvas_id, actor_definition_name, display_name, status, machine_context from actor_instances where id = ?");
    const instance = await selectInstance.get("actor-1");
    expect(instance).toEqual({
      id: "actor-1",
      canvas_id: "canvas-actor",
      actor_definition_name: "Counter",
      display_name: "Counter A",
      status: "created",
      machine_context: '{"count":0}',
    });

    const insertInvalidInstance = await db.prepare("insert into actor_instances (id, canvas_id, element_id, actor_definition_name, display_name, status, machine_state) values (?, ?, ?, ?, ?, ?, ?)");
    await expectSqlConstraintFailure(() => insertInvalidInstance.run("actor-bad", "canvas-actor", "element-bad", "Counter", "Broken", "not-a-status", "idle"));

    const insertConnection = await db.prepare("insert into actor_connections (id, canvas_id, source_actor_instance_id, target_actor_instance_id, label, msg_name_whitelist, style) values (?, ?, ?, ?, ?, ?, ?)");
    await insertConnection.run("connection-1", "canvas-actor", "actor-1", "actor-2", "A to B", '["increment"]', '{"stroke":"blue"}');

    const selectConnection = await db.prepare("select id, enabled, label, msg_name_whitelist, style from actor_connections where id = ?");
    const connection = await selectConnection.get("connection-1");
    expect(connection).toEqual({
      id: "connection-1",
      enabled: 1,
      label: "A to B",
      msg_name_whitelist: '["increment"]',
      style: '{"stroke":"blue"}',
    });

    await expectSqlConstraintFailure(() => insertConnection.run("connection-bad", "canvas-actor", "missing-source", "actor-2", null, null, "{}"));
  });

  test("media files table stores image bytes as blobs", async () => {
    await txRunMigrations({ db, Bun, path }, {});

    const bytes = new Uint8Array([1, 2, 3, 4]);
    const insertFile = await db.prepare("insert into media_files (id, hash, mime_type, data) values (?, ?, ?, ?)");
    await insertFile.run("media-1", "hash-1", "image/png", bytes);

    const selectFile = await db.prepare("select id, hash, mime_type, data, typeof(data) as data_type, created_at from media_files where id = ?");
    const file = await selectFile.get("media-1");

    expect(file).toEqual({
      id: "media-1",
      hash: "hash-1",
      mime_type: "image/png",
      data: bytes,
      data_type: "blob",
      created_at: expect.any(String),
    });
  });
});
