import {
  apiCreateResource,
  apiDeleteResource,
  apiDeleteResourceData,
  apiGetResource,
  apiListResourceData,
  apiListResources,
  apiRenameResource,
  apiRevealResourceSecret,
  apiSetResourceData,
} from './api.resources';
import {
  apiBulkDbRows,
  apiChangeDbDraft,
  apiConfirmDbApply,
  apiCreateDbDraft,
  apiCreateDbRow,
  apiDbResourceImpact,
  apiDeleteDbRow,
  apiDiscardDbBackup,
  apiDiscardDbDraft,
  apiExecuteDbDraftSql,
  apiExecuteDbLiveSql,
  apiGetActiveDbDraft,
  apiGetDbApply,
  apiGetDbBackup,
  apiGetDbDraft,
  apiGetDbRestoreStatus,
  apiGetDbRow,
  apiInspectDbDraft,
  apiInspectDbResource,
  apiListDbApplies,
  apiListDbDrafts,
  apiListDbRows,
  apiPreviewDbApply,
  apiPreviewDbBackupRestore,
  apiRestoreDbBackup,
  apiUpdateDbRow,
} from './api.db-resources';

const resourceHandlers = {
  resources: {
    list: apiListResources,
    get: apiGetResource,
    create: apiCreateResource,
    rename: apiRenameResource,
    delete: apiDeleteResource,
    data: apiListResourceData,
    dataSet: apiSetResourceData,
    dataDelete: apiDeleteResourceData,
    dataRevealSecret: apiRevealResourceSecret,
  },
  dbResources: {
    impact: apiDbResourceImpact,
    inspect: apiInspectDbResource,
    executeSql: apiExecuteDbLiveSql,
  },
  dbRows: {
    list: apiListDbRows,
    get: apiGetDbRow,
    create: apiCreateDbRow,
    update: apiUpdateDbRow,
    delete: apiDeleteDbRow,
    bulk: apiBulkDbRows,
  },
  dbDrafts: {
    create: apiCreateDbDraft,
    list: apiListDbDrafts,
    get: apiGetDbDraft,
    active: apiGetActiveDbDraft,
    inspect: apiInspectDbDraft,
    change: apiChangeDbDraft,
    executeSql: apiExecuteDbDraftSql,
    discard: apiDiscardDbDraft,
  },
  dbApplies: {
    preview: apiPreviewDbApply,
    confirm: apiConfirmDbApply,
    get: apiGetDbApply,
    list: apiListDbApplies,
  },
  dbBackups: {
    get: apiGetDbBackup,
    discard: apiDiscardDbBackup,
    previewRestore: apiPreviewDbBackupRestore,
    restore: apiRestoreDbBackup,
    restoreStatus: apiGetDbRestoreStatus,
  },
};

export { resourceHandlers };
