CREATE TABLE `accounts` (
	`id` text PRIMARY KEY NOT NULL,
	`kind` text DEFAULT 'user' NOT NULL,
	`display_name` text NOT NULL,
	`role` text DEFAULT 'member' NOT NULL,
	`is_autogenerated` integer DEFAULT true NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `accounts_display_name_unique` ON `accounts` (`display_name`);--> statement-breakpoint
CREATE INDEX `accounts_role_idx` ON `accounts` (`role`);--> statement-breakpoint
CREATE TABLE `canvas_members` (
	`canvas_id` text NOT NULL,
	`account_id` text NOT NULL,
	`role` text DEFAULT 'viewer' NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	PRIMARY KEY(`canvas_id`, `account_id`),
	FOREIGN KEY (`canvas_id`) REFERENCES `canvas`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `canvas_members_account_id_idx` ON `canvas_members` (`account_id`);--> statement-breakpoint
CREATE INDEX `canvas_members_role_idx` ON `canvas_members` (`role`);--> statement-breakpoint
CREATE TABLE `filesystem_members` (
	`filesystem_id` text NOT NULL,
	`account_id` text NOT NULL,
	`role` text DEFAULT 'reader' NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	PRIMARY KEY(`filesystem_id`, `account_id`),
	FOREIGN KEY (`filesystem_id`) REFERENCES `filesystems`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`account_id`) REFERENCES `accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `filesystem_members_account_id_idx` ON `filesystem_members` (`account_id`);--> statement-breakpoint
CREATE INDEX `filesystem_members_role_idx` ON `filesystem_members` (`role`);--> statement-breakpoint
INSERT OR IGNORE INTO `accounts` (`id`, `kind`, `display_name`, `role`, `is_autogenerated`, `created_at`, `updated_at`)
VALUES ('oss-owner', 'user', 'OSS Owner', 'owner', 1, unixepoch(), unixepoch());--> statement-breakpoint
INSERT OR IGNORE INTO `canvas_members` (`canvas_id`, `account_id`, `role`, `created_at`, `updated_at`)
SELECT `id`, 'oss-owner', 'owner', unixepoch(), unixepoch() FROM `canvas`;--> statement-breakpoint
INSERT OR IGNORE INTO `filesystem_members` (`filesystem_id`, `account_id`, `role`, `created_at`, `updated_at`)
SELECT `id`, 'oss-owner', 'owner', unixepoch(), unixepoch() FROM `filesystems`;