import { Database } from 'bun:sqlite';
import { drizzle } from 'drizzle-orm/bun-sqlite';
import type { BunSQLiteDatabase } from 'drizzle-orm/bun-sqlite';
import { migrate } from 'drizzle-orm/bun-sqlite/migrator';
import { and, eq, inArray } from 'drizzle-orm';
import { dirname, join, resolve } from 'path';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';
import { txRunDatabaseMigrations } from '../core/tx.migrations';
import type { IDbConfig } from '../interface';
import type {
  IDbService,
  TCanvasInsertArgs,
  TCanvasRecord,
  TCreateFileArgs,
  TFileRecord,
  TFilesystemInsertArgs,
  TFilesystemRecord,
  TGetFileArgs,
  TGetFullCanvasResult,
} from '../IDbService';
import { DEFAULT_OSS_ACCOUNT_DISPLAY_NAME, DEFAULT_OSS_ACCOUNT_ID } from '../CONSTANTS';
import * as schema from '../schema';
import { fxGetFile } from './fx.get-file';
import { txCreateFile } from './tx.create-file';

export type TDbSchema = typeof schema;
export type TDrizzleDb = BunSQLiteDatabase<TDbSchema>;

function configureSqlite(sqlite: Database) {
  sqlite.run('PRAGMA foreign_keys = ON');
  sqlite.run('PRAGMA journal_mode = WAL');
  sqlite.run('PRAGMA busy_timeout = 5000');
  sqlite.run('PRAGMA synchronous = NORMAL');
  sqlite.run('PRAGMA cache_size = 10000');
  sqlite.run('PRAGMA temp_store = MEMORY');
  sqlite.run('PRAGMA mmap_size = 268435456');
}

export class DbServiceBunSqlite implements IDbService {
  readonly name = 'db' as const;
  readonly sqlite: Database;
  readonly drizzle: TDrizzleDb;
  #startPromise: Promise<void> | null = null;
  #stopped = false;

  constructor(private readonly config: IDbConfig) {
    this.sqlite = new Database(config.databasePath);
    configureSqlite(this.sqlite);

    this.drizzle = drizzle({ client: this.sqlite, schema });
  }

  start(): Promise<void> {
    if (this.#stopped) {
      throw new Error('Database service has been stopped');
    }

    if (this.#startPromise !== null) {
      return this.#startPromise;
    }

    this.#startPromise = txRunDatabaseMigrations({
      env: {
        VIBECANVAS_MIGRATIONS_DIR: process.env.VIBECANVAS_MIGRATIONS_DIR,
        VIBECANVAS_COMPILED: process.env.VIBECANVAS_COMPILED,
      },
      paths: {
        dirname,
        join,
        resolve,
        importMetaDir: import.meta.dir,
        execPath: process.execPath,
      },
      fs: {
        existsSync,
        mkdirSync,
        readFileSync,
        writeFileSync,
      },
      loadEmbeddedMigrationsModule: async () => {
        try {
          return await import('../embedded-migrations');
        } catch {
          return null;
        }
      },
      migrate,
      log: (message) => console.log(message),
    }, {
      dataDir: this.config.dataDir,
      cacheDir: this.config.cacheDir,
      db: this.drizzle,
      sqlite: this.sqlite,
      silent: this.config.silentMigrations,
    }).catch((error) => {
      this.#startPromise = null;
      throw error;
    });

    return this.#startPromise;
  }

  account = {
    getDefaultOwner: () => this.drizzle.query.accounts.findFirst({ where: eq(schema.accounts.id, DEFAULT_OSS_ACCOUNT_ID) }).sync() ?? null,
    ensureDefaultOwner: () => {
      const account = this.drizzle.insert(schema.accounts).values({
        id: DEFAULT_OSS_ACCOUNT_ID,
        kind: 'user',
        displayName: DEFAULT_OSS_ACCOUNT_DISPLAY_NAME,
        role: 'owner',
        isAutogenerated: true,
      }).onConflictDoUpdate({
        target: schema.accounts.id,
        set: {
          role: 'owner',
          updatedAt: new Date(),
        },
      }).returning().all()[0]!;

      this.sqlite.run(`
        INSERT OR IGNORE INTO canvas_members (canvas_id, account_id, role, created_at, updated_at)
        SELECT id, '${DEFAULT_OSS_ACCOUNT_ID}', 'owner', unixepoch(), unixepoch() FROM canvas
      `);
      this.sqlite.run(`
        INSERT OR IGNORE INTO filesystem_members (filesystem_id, account_id, role, created_at, updated_at)
        SELECT id, '${DEFAULT_OSS_ACCOUNT_ID}', 'owner', unixepoch(), unixepoch() FROM filesystems
      `);

      return account;
    },
  };

  #accountId(accountId?: string) {
    return accountId ?? DEFAULT_OSS_ACCOUNT_ID;
  }

  #ensureAccount(accountId?: string) {
    if (!accountId || accountId === DEFAULT_OSS_ACCOUNT_ID) {
      this.account.ensureDefaultOwner();
    }
    return this.#accountId(accountId);
  }

  #canEditCanvas(accountId: string, canvasId: string) {
    return this.drizzle.query.canvas_members.findFirst({
      where: and(
        eq(schema.canvas_members.canvas_id, canvasId),
        eq(schema.canvas_members.account_id, accountId),
        inArray(schema.canvas_members.role, ['owner', 'editor']),
      ),
    }).sync() !== undefined;
  }

  #canWriteFilesystem(accountId: string, filesystemId: string) {
    return this.drizzle.query.filesystem_members.findFirst({
      where: and(
        eq(schema.filesystem_members.filesystem_id, filesystemId),
        eq(schema.filesystem_members.account_id, accountId),
        inArray(schema.filesystem_members.role, ['owner', 'writer']),
      ),
    }).sync() !== undefined;
  }

  canvas = {
    listAll: (args?: { accountId?: string }) => this.drizzle
      .select({ canvas: schema.canvas })
      .from(schema.canvas)
      .innerJoin(schema.canvas_members, and(
        eq(schema.canvas_members.canvas_id, schema.canvas.id),
        eq(schema.canvas_members.account_id, this.#accountId(args?.accountId)),
      ))
      .all()
      .map((row) => row.canvas) as TCanvasRecord[],
    findByName: (name: string, args?: { accountId?: string }) => this.drizzle
      .select({ canvas: schema.canvas })
      .from(schema.canvas)
      .innerJoin(schema.canvas_members, and(
        eq(schema.canvas_members.canvas_id, schema.canvas.id),
        eq(schema.canvas_members.account_id, this.#accountId(args?.accountId)),
      ))
      .where(eq(schema.canvas.name, name))
      .all()[0]?.canvas ?? null,
    create: (args: TCanvasInsertArgs & { accountId?: string }) => {
      const { accountId, ...canvasArgs } = args;
      const actorId = this.#ensureAccount(accountId);
      const result = this.drizzle.transaction((tx) => {
        const created = tx.insert(schema.canvas).values(canvasArgs).returning().all()[0]!;
        tx.insert(schema.canvas_members).values({ canvas_id: created.id, account_id: actorId, role: 'owner' }).run();
        return created;
      });
      return result;
    },
    renameById: (args: { id: string, name: string, accountId?: string }) => {
      const actorId = this.#accountId(args.accountId);
      if (!this.#canEditCanvas(actorId, args.id)) return null;
      return this.drizzle.update(schema.canvas).set({ name: args.name }).where(eq(schema.canvas.id, args.id)).returning().all()[0] ?? null;
    },
    deleteById: (args: { id: string, accountId?: string }) => {
      const actorId = this.#accountId(args.accountId);
      const owner = this.drizzle.query.canvas_members.findFirst({
        where: and(
          eq(schema.canvas_members.canvas_id, args.id),
          eq(schema.canvas_members.account_id, actorId),
          eq(schema.canvas_members.role, 'owner'),
        ),
      }).sync();
      if (!owner) return [];
      return this.drizzle.delete(schema.canvas).where(eq(schema.canvas.id, args.id)).returning().all();
    },
    listMembers: (args: { canvasId: string }) => this.drizzle.query.canvas_members.findMany({ where: eq(schema.canvas_members.canvas_id, args.canvasId) }).sync(),
  };

  file = {
    listAll: () => this.drizzle.query.files.findMany().sync() as TFileRecord[],
    create: (args: TCreateFileArgs) => txCreateFile(this, args),
    get: (args: TGetFileArgs) => fxGetFile(this, args),
    deleteById: (args: { id: string }) => this.drizzle.delete(schema.files).where(eq(schema.files.id, args.id)).run(),
  };

  filesystem = {
    listAll: (args?: { accountId?: string }) => this.drizzle
      .select({ filesystem: schema.filesystems })
      .from(schema.filesystems)
      .innerJoin(schema.filesystem_members, and(
        eq(schema.filesystem_members.filesystem_id, schema.filesystems.id),
        eq(schema.filesystem_members.account_id, this.#accountId(args?.accountId)),
      ))
      .all()
      .map((row) => row.filesystem) as TFilesystemRecord[],
    findById: (id: string, args?: { accountId?: string }) => this.drizzle
      .select({ filesystem: schema.filesystems })
      .from(schema.filesystems)
      .innerJoin(schema.filesystem_members, and(
        eq(schema.filesystem_members.filesystem_id, schema.filesystems.id),
        eq(schema.filesystem_members.account_id, this.#accountId(args?.accountId)),
      ))
      .where(eq(schema.filesystems.id, id))
      .all()[0]?.filesystem ?? null,
    findByMachineId: (machineId: string, args?: { accountId?: string }) => this.drizzle
      .select({ filesystem: schema.filesystems })
      .from(schema.filesystems)
      .innerJoin(schema.filesystem_members, and(
        eq(schema.filesystem_members.filesystem_id, schema.filesystems.id),
        eq(schema.filesystem_members.account_id, this.#accountId(args?.accountId)),
      ))
      .where(eq(schema.filesystems.machine_id, machineId))
      .all()[0]?.filesystem ?? null,
    create: (args: TFilesystemInsertArgs & { accountId?: string }) => {
      const { accountId, ...filesystemArgs } = args;
      const actorId = this.#ensureAccount(accountId);
      return this.drizzle.transaction((tx) => {
        const created = tx.insert(schema.filesystems).values(filesystemArgs).returning().all()[0]!;
        tx.insert(schema.filesystem_members).values({ filesystem_id: created.id, account_id: actorId, role: 'owner' }).run();
        return created;
      });
    },
    updateById: (args: { id: string; label?: string; kind?: 'local' | 'remote'; home_path?: string | null; accountId?: string }) => {
      const actorId = this.#accountId(args.accountId);
      if (!this.#canWriteFilesystem(actorId, args.id)) return null;
      return this.drizzle
        .update(schema.filesystems)
        .set({
          ...(args.label !== undefined ? { label: args.label } : {}),
          ...(args.kind !== undefined ? { kind: args.kind } : {}),
          ...(args.home_path !== undefined ? { home_path: args.home_path } : {}),
          updated_at: new Date(),
        })
        .where(eq(schema.filesystems.id, args.id))
        .returning()
        .all()[0] ?? null;
    },
    listMembers: (args: { filesystemId: string }) => this.drizzle.query.filesystem_members.findMany({ where: eq(schema.filesystem_members.filesystem_id, args.filesystemId) }).sync(),
  };

  async stop() {
    if (this.#stopped) {
      return;
    }

    this.#stopped = true;
    await this.#startPromise?.catch(() => undefined);
    this.sqlite.close();
  }

  getFullCanvas(id: string, args?: { accountId?: string }): TGetFullCanvasResult | null {
    const canvas = this.drizzle
      .select({ canvas: schema.canvas })
      .from(schema.canvas)
      .innerJoin(schema.canvas_members, and(
        eq(schema.canvas_members.canvas_id, schema.canvas.id),
        eq(schema.canvas_members.account_id, this.#accountId(args?.accountId)),
      ))
      .where(eq(schema.canvas.id, id))
      .all()[0]?.canvas;

    if (!canvas) {
      return null;
    }

    return {
      canvas,
    };
  }
}

export async function createSqliteDb(config: IDbConfig): Promise<DbServiceBunSqlite> {
  const dbService = new DbServiceBunSqlite(config);
  await dbService.start();
  return dbService;
}
