export const WIDGET_STATE_INITIAL_VERSION = 1;

export const MAX_WIDGET_STATE_BYTES = 64 * 1024;

export const MAX_WIDGET_STATE_DEPTH = 32;

export const MAX_WIDGET_STATE_NODES = 10_000;

export const WIDGET_STATE_MUTATION_RATE_LIMIT = 20;

export const WIDGET_STATE_MUTATION_RATE_WINDOW_MS = 1_000;

export const DEFAULT_WIDGET_STATE_REPLAY_CAPACITY = 256;

export const DEFAULT_WIDGET_STATE_SUBSCRIBER_QUEUE_CAPACITY = 64;

export const DEFAULT_WIDGET_STATE_MAX_ACTIVE_STREAMS = 2_048;

export const DEFAULT_WIDGET_STATE_MAX_MUTATION_RATE_LEDGERS = 2_048;

export const MAX_WIDGET_STATE_ID_LENGTH = 200;
