CREATE DOMAIN sha256_hex AS TEXT CHECK (
  length(value) = 64
  AND value = lower(value)
  AND value NOT GLOB '*[^0-9a-f]*'
);

CREATE DOMAIN resource_catalog_status AS TEXT CHECK (
  value IN ('created', 'provisioning', 'ready', 'migrating', 'error', 'deleting')
);
CREATE DOMAIN resource_draft_status AS TEXT CHECK (
  value IN ('editing', 'applying', 'applied', 'discarded', 'error')
);
CREATE DOMAIN resource_apply_status AS TEXT CHECK (
  value IN ('preparing', 'applying', 'succeeded', 'failed', 'recovered')
);
CREATE DOMAIN function_invocation_status AS TEXT CHECK (
  value IN ('queued', 'claimed', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out')
);
CREATE DOMAIN function_attempt_status AS TEXT CHECK (
  value IN ('starting', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out', 'lost')
);
CREATE DOMAIN usage_outcome AS TEXT CHECK (
  value IN ('succeeded', 'failed', 'cancelled', 'timed_out', 'lost')
);
CREATE DOMAIN agent_draft_status AS TEXT CHECK (
  value IN ('editing', 'validating', 'ready', 'published', 'error', 'discarded')
);

CREATE TABLE schema_migrations (
  version INTEGER PRIMARY KEY CHECK (version >= 0),
  name TEXT NOT NULL UNIQUE CHECK (length(trim(name)) BETWEEN 1 AND 200),
  checksum_sha256 sha256_hex NOT NULL,
  applied_at_ms INTEGER NOT NULL CHECK (applied_at_ms >= 0),
  application_version TEXT NOT NULL CHECK (length(trim(application_version)) BETWEEN 1 AND 100)
) STRICT;

CREATE TABLE accounts (
  id TEXT PRIMARY KEY NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('user', 'service_account', 'system', 'anonymous')),
  display_name TEXT NOT NULL CHECK (length(trim(display_name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
  is_autogenerated BOOLEAN NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms)
) STRICT;

CREATE TABLE organizations (
  id TEXT PRIMARY KEY NOT NULL,
  slug TEXT NOT NULL UNIQUE CHECK (
    length(slug) BETWEEN 1 AND 100
    AND slug = lower(trim(slug))
    AND substr(slug, 1, 1) <> '-'
    AND substr(slug, -1, 1) <> '-'
    AND instr(slug, '--') = 0
    AND slug NOT GLOB '*[^a-z0-9-]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('active', 'suspended', 'archived')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms)
) STRICT;

CREATE TABLE organization_memberships (
  org_id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member', 'viewer')),
  status TEXT NOT NULL CHECK (status IN ('invited', 'active', 'suspended')),
  is_billable_seat BOOLEAN NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, account_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT
) STRICT;

CREATE TABLE key_values (
  org_id TEXT NOT NULL,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 300),
  kind TEXT NOT NULL CHECK (kind IN ('text', 'json', 'number', 'bool', 'blob')),
  text_value TEXT,
  json_value JSON,
  number_value REAL,
  bool_value BOOLEAN,
  blob_value BLOB,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CHECK (
    (kind = 'text' AND text_value IS NOT NULL AND json_value IS NULL AND number_value IS NULL AND bool_value IS NULL AND blob_value IS NULL)
    OR (kind = 'json' AND text_value IS NULL AND json_value IS NOT NULL AND number_value IS NULL AND bool_value IS NULL AND blob_value IS NULL)
    OR (kind = 'number' AND text_value IS NULL AND json_value IS NULL AND number_value IS NOT NULL AND bool_value IS NULL AND blob_value IS NULL)
    OR (kind = 'bool' AND text_value IS NULL AND json_value IS NULL AND number_value IS NULL AND bool_value IS NOT NULL AND blob_value IS NULL)
    OR (kind = 'blob' AND text_value IS NULL AND json_value IS NULL AND number_value IS NULL AND bool_value IS NULL AND blob_value IS NOT NULL)
  )
) STRICT;

CREATE TABLE canvases (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  access_policy TEXT NOT NULL CHECK (access_policy IN ('org', 'restricted')),
  created_by_account_id TEXT NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  revision INTEGER NOT NULL DEFAULT 0 CHECK (revision >= 0),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, created_by_account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT
) STRICT;

CREATE TABLE canvas_members (
  org_id TEXT NOT NULL,
  canvas_id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('owner', 'editor', 'viewer')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, canvas_id, account_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE CASCADE
) STRICT;

CREATE TABLE canvas_items (
  org_id TEXT NOT NULL,
  canvas_id TEXT NOT NULL,
  id TEXT NOT NULL CHECK (length(id) > 0),
  item_json JSONB NOT NULL,
  item_revision INTEGER NOT NULL DEFAULT 0 CHECK (item_revision >= 0),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  kind TEXT GENERATED ALWAYS AS (
    json_extract(item_json, '$.kind')
  ) VIRTUAL NOT NULL,
  parent_id TEXT GENERATED ALWAYS AS (
    json_extract(item_json, '$.parentId')
  ) VIRTUAL,
  order_key TEXT GENERATED ALWAYS AS (
    json_extract(item_json, '$.orderKey')
  ) VIRTUAL NOT NULL,
  widget_instance_id TEXT GENERATED ALWAYS AS (
    CASE
      WHEN json_extract(
        item_json,
        '$.extensions."omnidraw:widget".type'
      ) = 'widget-instance'
      THEN json_extract(
        item_json,
        '$.extensions."omnidraw:widget".instanceId'
      )
      ELSE NULL
    END
  ) VIRTUAL,
  definition_id TEXT GENERATED ALWAYS AS (
    CASE
      WHEN json_extract(
        item_json,
        '$.extensions."omnidraw:widget".type'
      ) = 'widget-instance'
      THEN json_extract(
        item_json,
        '$.extensions."omnidraw:widget".definitionId'
      )
      ELSE NULL
    END
  ) VIRTUAL,
  revision_id TEXT GENERATED ALWAYS AS (
    CASE
      WHEN json_extract(
        item_json,
        '$.extensions."omnidraw:widget".type'
      ) = 'widget-instance'
      THEN json_extract(
        item_json,
        '$.extensions."omnidraw:widget".revisionId'
      )
      ELSE NULL
    END
  ) VIRTUAL,
  PRIMARY KEY (org_id, canvas_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, canvas_id)
    REFERENCES canvases (org_id, id) ON DELETE CASCADE,
  CHECK (json_type(item_json, '$') = 'object'),
  CHECK (
    json_type(item_json, '$.id') IS 'text'
    AND json_extract(item_json, '$.id') = id
  ),
  CHECK (
    json_type(item_json, '$.kind') IS 'text'
    AND length(trim(kind)) > 0
  ),
  CHECK (
    json_type(item_json, '$.parentId') IS NOT NULL
    AND json_type(item_json, '$.parentId') IN ('null', 'text')
    AND (
      json_type(item_json, '$.parentId') = 'null'
      OR length(parent_id) > 0
    )
  ),
  CHECK (
    json_type(item_json, '$.orderKey') IS 'text'
    AND length(order_key) > 0
  ),
  CHECK (
    json_extract(
      item_json,
      '$.extensions."omnidraw:widget".type'
    ) IS NOT 'widget-instance'
    OR (
      widget_instance_id IS NOT NULL
      AND definition_id IS NOT NULL
      AND revision_id IS NOT NULL
      AND json_type(
        item_json,
        '$.extensions."omnidraw:widget".instanceId'
      ) = 'text'
      AND json_type(
        item_json,
        '$.extensions."omnidraw:widget".definitionId'
      ) = 'text'
      AND json_type(
        item_json,
        '$.extensions."omnidraw:widget".revisionId'
      ) = 'text'
      AND length(trim(widget_instance_id)) > 0
      AND length(trim(definition_id)) > 0
      AND length(trim(revision_id)) > 0
    )
  )
) STRICT;

CREATE TABLE artifact_references (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('ui', 'server', 'source', 'source_map')),
  digest_sha256 sha256_hex NOT NULL,
  byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
  retention_state TEXT NOT NULL CHECK (retention_state IN ('pinned', 'eligible', 'deleting')),
  retain_until_ms INTEGER CHECK (retain_until_ms IS NULL OR retain_until_ms >= 0),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, id, kind),
  UNIQUE (org_id, kind, digest_sha256),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  CHECK (retention_state <> 'eligible' OR retain_until_ms IS NOT NULL)
) STRICT;

CREATE TABLE widget_definitions (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  slug TEXT NOT NULL CHECK (
    length(slug) BETWEEN 1 AND 100 AND slug = lower(trim(slug))
    AND substr(slug, 1, 1) <> '-' AND substr(slug, -1, 1) <> '-'
    AND instr(slug, '--') = 0 AND slug NOT GLOB '*[^a-z0-9-]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('draft', 'published', 'archived')),
  active_revision_id TEXT,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  next_revision_number INTEGER NOT NULL DEFAULT 1 CHECK (next_revision_number >= 1),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, slug),
  UNIQUE (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, id, active_revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE RESTRICT,
  CHECK ((status = 'published' AND active_revision_id IS NOT NULL) OR status <> 'published')
) STRICT;

CREATE TABLE widget_definition_revisions (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  definition_id TEXT NOT NULL,
  revision_number INTEGER NOT NULL CHECK (revision_number >= 1),
  ui_artifact_id TEXT NOT NULL,
  ui_artifact_kind TEXT NOT NULL DEFAULT 'ui' CHECK (ui_artifact_kind = 'ui'),
  server_artifact_id TEXT,
  server_artifact_kind TEXT CHECK (
    (server_artifact_id IS NULL AND server_artifact_kind IS NULL)
    OR (server_artifact_id IS NOT NULL AND server_artifact_kind = 'server')
  ),
  manifest_json JSON NOT NULL CHECK (json_type(manifest_json) = 'object'),
  contract_digest_sha256 sha256_hex NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  function_descriptors_json JSON NOT NULL
    DEFAULT '{"format":"omnidraw.server-functions.v1","functions":[]}'
    CHECK (
      json_type(function_descriptors_json) = 'object'
      AND json_extract(function_descriptors_json, '$.format') = 'omnidraw.server-functions.v1'
      AND json_type(function_descriptors_json, '$.functions') = 'array'
    ),
  function_descriptors_digest_sha256 sha256_hex NOT NULL
    DEFAULT '2ffcc4002f0abc5490138a0da6fcce85b1ee82bc9e56f0000fb552953839f40b',
  ui_runtime_json JSON NOT NULL CHECK (
    json_type(ui_runtime_json) = 'object'
    AND json_extract(ui_runtime_json, '$.format') = 'omnidraw.capsule-runtime.v1'
    AND json_type(ui_runtime_json, '$.target') = 'object'
    AND json_type(ui_runtime_json, '$.budgets') = 'object'
    AND json_type(ui_runtime_json, '$.capabilityRequests') = 'array'
    AND json_type(ui_runtime_json, '$.channels') IN ('null', 'object')
    AND json_extract(ui_runtime_json, '$.parkability.parkable') = 0
    AND json_type(ui_runtime_json, '$.signatureKeyIds') = 'array'
    AND json_array_length(ui_runtime_json, '$.signatureKeyIds') BETWEEN 1 AND 32
    AND json_remove(
      ui_runtime_json,
      '$.format',
      '$.capsuleArtifactHash',
      '$.target',
      '$.budgets',
      '$.capabilityRequests',
      '$.channels',
      '$.parkability',
      '$.signatureKeyIds'
    ) = '{}'
  ),
  capsule_artifact_hash TEXT NOT NULL CHECK (
    length(capsule_artifact_hash) = 71
    AND substr(capsule_artifact_hash, 1, 7) = 'sha256:'
    AND substr(capsule_artifact_hash, 8) NOT GLOB '*[^0-9a-f]*'
    AND json_extract(ui_runtime_json, '$.capsuleArtifactHash') = capsule_artifact_hash
  ),
  capability_contract_digest_sha256 sha256_hex NOT NULL,
  channel_contract_digest_sha256 sha256_hex NOT NULL,
  capsule_build_identity_json JSON NOT NULL CHECK (
    json_type(capsule_build_identity_json) = 'object'
    AND json_extract(capsule_build_identity_json, '$.packageName') = '@omnidraw/capsule'
    AND length(json_extract(capsule_build_identity_json, '$.packageVersion')) BETWEEN 1 AND 100
    AND length(json_extract(capsule_build_identity_json, '$.buildApiVersion')) BETWEEN 1 AND 100
    AND length(json_extract(capsule_build_identity_json, '$.packageDigest')) = 71
    AND length(json_extract(capsule_build_identity_json, '$.runtimeBuildDigest')) = 71
    AND substr(json_extract(capsule_build_identity_json, '$.packageDigest'), 1, 7) = 'sha256:'
    AND substr(json_extract(capsule_build_identity_json, '$.runtimeBuildDigest'), 1, 7) = 'sha256:'
    AND json_remove(
      capsule_build_identity_json,
      '$.packageName',
      '$.packageVersion',
      '$.packageDigest',
      '$.buildApiVersion',
      '$.runtimeBuildDigest'
    ) = '{}'
  ),
  build_policy_id TEXT NOT NULL CHECK (length(trim(build_policy_id)) BETWEEN 1 AND 200),
  server_runtime_abi TEXT CHECK (
    (server_artifact_id IS NULL AND server_runtime_abi IS NULL)
    OR (server_artifact_id IS NOT NULL AND length(trim(server_runtime_abi)) BETWEEN 1 AND 100)
  ),
  contract_format_version INTEGER NOT NULL DEFAULT 3 CHECK (contract_format_version = 3),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, definition_id, id),
  UNIQUE (org_id, definition_id, revision_number),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, definition_id) REFERENCES widget_definitions (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, ui_artifact_id, ui_artifact_kind)
    REFERENCES artifact_references (org_id, id, kind) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, server_artifact_id, server_artifact_kind)
    REFERENCES artifact_references (org_id, id, kind) ON DELETE RESTRICT,
  CHECK (server_artifact_id IS NULL OR server_artifact_id <> ui_artifact_id)
) STRICT;

CREATE TABLE widget_instances (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  canvas_id TEXT NOT NULL,
  element_id TEXT NOT NULL CHECK (length(trim(element_id)) BETWEEN 1 AND 200),
  definition_id TEXT NOT NULL,
  revision_id TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active', 'archived')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, definition_id, revision_id, id),
  UNIQUE (org_id, canvas_id, element_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, definition_id) REFERENCES widget_definitions (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, definition_id, revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE RESTRICT
) STRICT;

CREATE TABLE widget_instance_states (
  org_id TEXT NOT NULL,
  widget_instance_id TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
  state_json JSONB NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, widget_instance_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, widget_instance_id)
    REFERENCES widget_instances (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE resource_catalog (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('kv', 'secretStore', 'db')),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status resource_catalog_status NOT NULL,
  last_error_json JSON CHECK (
    last_error_json IS NULL OR (json_type(last_error_json) = 'object')
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, id, kind),
  UNIQUE (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT
) STRICT;

CREATE TABLE resource_bindings (
  org_id TEXT NOT NULL,
  definition_id TEXT NOT NULL,
  revision_id TEXT NOT NULL,
  slot_name TEXT NOT NULL CHECK (length(trim(slot_name)) BETWEEN 1 AND 200),
  resource_id TEXT NOT NULL,
  resource_kind TEXT NOT NULL CHECK (resource_kind IN ('kv', 'secretStore', 'db')),
  is_required BOOLEAN NOT NULL,
  manifest_allow_read BOOLEAN NOT NULL,
  manifest_allow_write BOOLEAN NOT NULL,
  allow_read BOOLEAN NOT NULL,
  allow_write BOOLEAN NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, definition_id, revision_id, slot_name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, definition_id, revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id, resource_kind)
    REFERENCES resource_catalog (org_id, id, kind) ON DELETE RESTRICT,
  CHECK (manifest_allow_read = CAST(1 AS BOOLEAN) OR manifest_allow_write = CAST(1 AS BOOLEAN)),
  CHECK (allow_read = CAST(1 AS BOOLEAN) OR allow_write = CAST(1 AS BOOLEAN)),
  CHECK (allow_read <= manifest_allow_read AND allow_write <= manifest_allow_write)
) STRICT;

CREATE TABLE resource_placements (
  org_id TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  cell_id TEXT NOT NULL,
  placement_epoch INTEGER NOT NULL CHECK (placement_epoch >= 1),
  relative_path TEXT NOT NULL CHECK (
    length(relative_path) BETWEEN 1 AND 1024
    AND relative_path = trim(relative_path)
    AND substr(relative_path, 1, 1) <> '/'
    AND relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(relative_path, '\') = 0
    AND relative_path <> '.' AND relative_path <> '..'
    AND relative_path NOT LIKE './%' AND relative_path NOT LIKE '../%'
    AND relative_path NOT LIKE '%/./%' AND relative_path NOT LIKE '%/../%'
    AND relative_path NOT LIKE '%/.' AND relative_path NOT LIKE '%/..'
    AND relative_path NOT LIKE '%//%'
  ),
  status TEXT NOT NULL CHECK (status IN ('reserved', 'active', 'moving', 'error')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, resource_id),
  UNIQUE (org_id, relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE resource_encryption_keys (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  purpose TEXT NOT NULL CHECK (purpose = 'resource-data'),
  algorithm TEXT NOT NULL CHECK (algorithm = 'aegis-256'),
  key_material BLOB NOT NULL CHECK (length(key_material) = 32),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE db_resource_drafts (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  resource_kind TEXT NOT NULL DEFAULT 'db' CHECK (resource_kind = 'db'),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status resource_draft_status NOT NULL,
  last_error_json JSON CHECK (
    last_error_json IS NULL OR (json_type(last_error_json) = 'object')
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  applied_at_ms INTEGER CHECK (applied_at_ms IS NULL OR applied_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id, resource_kind)
    REFERENCES resource_catalog (org_id, id, kind) ON DELETE CASCADE,
  CHECK ((status = 'applied' AND applied_at_ms IS NOT NULL) OR (status <> 'applied' AND applied_at_ms IS NULL))
) STRICT;

CREATE TABLE db_resource_draft_changes (
  org_id TEXT NOT NULL,
  draft_id TEXT NOT NULL,
  sequence INTEGER NOT NULL CHECK (sequence >= 1),
  kind TEXT NOT NULL CHECK (kind IN ('structure', 'sql')),
  operation_json JSON CHECK (
    operation_json IS NULL OR (json_type(operation_json) = 'object')
  ),
  sql_text TEXT NOT NULL CHECK (length(trim(sql_text)) BETWEEN 1 AND 1000000),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, draft_id, sequence),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, draft_id) REFERENCES db_resource_drafts (org_id, id) ON DELETE CASCADE,
  CHECK (
    (kind = 'structure' AND operation_json IS NOT NULL)
    OR (
      kind = 'sql'
      AND (
        operation_json IS NULL
        OR COALESCE(
          json_type(operation_json, '$.type') = 'text'
          AND json_extract(operation_json, '$.type') = 'boundSql'
          AND json_type(operation_json, '$.parameters') = 'array',
          0
        )
      )
    )
  )
) STRICT;

CREATE TABLE db_resource_apply_runs (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  draft_id TEXT,
  source_apply_id TEXT,
  status resource_apply_status NOT NULL,
  last_error_json JSON CHECK (
    last_error_json IS NULL OR (json_type(last_error_json) = 'object')
  ),
  backup_retained BOOLEAN NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  completed_at_ms INTEGER CHECK (completed_at_ms IS NULL OR completed_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id, draft_id)
    REFERENCES db_resource_drafts (org_id, resource_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id, source_apply_id)
    REFERENCES db_resource_apply_runs (org_id, resource_id, id) ON DELETE RESTRICT,
  CHECK (draft_id IS NULL OR source_apply_id IS NULL),
  CHECK (
    (status IN ('succeeded', 'failed', 'recovered') AND completed_at_ms IS NOT NULL)
    OR (status IN ('preparing', 'applying') AND completed_at_ms IS NULL)
  )
) STRICT;

CREATE TABLE db_resource_backups (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  apply_run_id TEXT NOT NULL,
  relative_path TEXT NOT NULL CHECK (
    length(relative_path) BETWEEN 1 AND 1024
    AND relative_path = trim(relative_path)
    AND substr(relative_path, 1, 1) <> '/'
    AND relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(relative_path, '\') = 0
    AND relative_path <> '.' AND relative_path <> '..'
    AND relative_path NOT LIKE './%' AND relative_path NOT LIKE '../%'
    AND relative_path NOT LIKE '%/./%' AND relative_path NOT LIKE '%/../%'
    AND relative_path NOT LIKE '%/.' AND relative_path NOT LIKE '%/..'
    AND relative_path NOT LIKE '%//%'
  ),
  digest_sha256 sha256_hex NOT NULL,
  byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
  state TEXT NOT NULL CHECK (state IN ('retained', 'deleting', 'deleted')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  verified_at_ms INTEGER NOT NULL CHECK (verified_at_ms >= created_at_ms),
  delete_after_ms INTEGER CHECK (delete_after_ms IS NULL OR delete_after_ms >= verified_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id, apply_run_id),
  UNIQUE (org_id, relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id, apply_run_id)
    REFERENCES db_resource_apply_runs (org_id, resource_id, id) ON DELETE RESTRICT,
  CHECK ((state = 'retained' AND delete_after_ms IS NOT NULL) OR state <> 'retained')
) STRICT;

CREATE TABLE function_invocations (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  subject_kind TEXT NOT NULL CHECK (subject_kind = 'widget_instance'),
  canvas_id TEXT,
  widget_definition_id TEXT NOT NULL,
  widget_revision_id TEXT NOT NULL,
  widget_instance_id TEXT,
  function_id TEXT NOT NULL CHECK (length(trim(function_id)) BETWEEN 1 AND 200),
  function_name TEXT NOT NULL CHECK (length(trim(function_name)) BETWEEN 1 AND 200),
  definition_revision INTEGER NOT NULL CHECK (definition_revision >= 1),
  artifact_digest_sha256 sha256_hex NOT NULL,
  contract_digest_sha256 sha256_hex NOT NULL,
  runtime_abi TEXT NOT NULL CHECK (length(trim(runtime_abi)) BETWEEN 1 AND 100),
  tenant_cell_id TEXT NOT NULL CHECK (length(trim(tenant_cell_id)) BETWEEN 1 AND 200),
  tenant_placement_epoch INTEGER NOT NULL CHECK (tenant_placement_epoch >= 1),
  tenant_request_id TEXT NOT NULL CHECK (length(trim(tenant_request_id)) BETWEEN 1 AND 300),
  tenant_roles_json JSON NOT NULL CHECK (
    json_type(tenant_roles_json) = 'array'
  ),
  tenant_capabilities_json JSON NOT NULL CHECK (
    json_type(tenant_capabilities_json) = 'array'
  ),
  input_json JSON,
  input_digest_sha256 sha256_hex NOT NULL,
  idempotency_key TEXT NOT NULL CHECK (length(trim(idempotency_key)) BETWEEN 1 AND 300),
  policy_version INTEGER NOT NULL CHECK (policy_version >= 1),
  priority INTEGER NOT NULL CHECK (priority BETWEEN 0 AND 100),
  timeout_ms INTEGER NOT NULL CHECK (timeout_ms >= 1),
  memory_tier TEXT NOT NULL CHECK (memory_tier IN ('small', 'medium', 'large')),
  output_byte_limit INTEGER NOT NULL CHECK (output_byte_limit >= 1),
  log_byte_limit INTEGER NOT NULL CHECK (log_byte_limit >= 0),
  retry_mode TEXT NOT NULL CHECK (retry_mode IN ('none', 'idempotent')),
  max_attempts INTEGER NOT NULL CHECK (max_attempts BETWEEN 1 AND 100),
  initial_backoff_ms INTEGER NOT NULL CHECK (initial_backoff_ms >= 0),
  max_backoff_ms INTEGER NOT NULL CHECK (max_backoff_ms >= initial_backoff_ms),
  status function_invocation_status NOT NULL,
  result_json JSON,
  failure_json JSON CHECK (
    failure_json IS NULL OR (json_type(failure_json) = 'object')
  ),
  result_digest_sha256 sha256_hex,
  output_byte_size INTEGER NOT NULL CHECK (output_byte_size >= 0),
  log_byte_size INTEGER NOT NULL CHECK (log_byte_size >= 0),
  body_state TEXT NOT NULL CHECK (body_state IN ('full', 'compacted')),
  retains_revision BOOLEAN NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  available_at_ms INTEGER NOT NULL CHECK (available_at_ms >= created_at_ms),
  deadline_at_ms INTEGER NOT NULL CHECK (deadline_at_ms >= created_at_ms),
  cancel_requested_at_ms INTEGER CHECK (
    cancel_requested_at_ms IS NULL OR cancel_requested_at_ms >= created_at_ms
  ),
  started_at_ms INTEGER CHECK (started_at_ms IS NULL OR started_at_ms >= created_at_ms),
  finished_at_ms INTEGER CHECK (
    finished_at_ms IS NULL OR finished_at_ms >= coalesce(started_at_ms, created_at_ms)
  ),
  bodies_compacted_at_ms INTEGER CHECK (
    bodies_compacted_at_ms IS NULL
    OR (finished_at_ms IS NOT NULL AND bodies_compacted_at_ms >= finished_at_ms)
  ),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT,
  CHECK (canvas_id IS NOT NULL AND widget_instance_id IS NOT NULL),
  CHECK (
    (status IN ('succeeded', 'failed', 'cancelled', 'timed_out') AND finished_at_ms IS NOT NULL)
    OR (status IN ('queued', 'claimed', 'running') AND finished_at_ms IS NULL)
  ),
  CHECK ((status IN ('queued', 'claimed') AND started_at_ms IS NULL) OR status NOT IN ('queued', 'claimed')),
  CHECK ((status IN ('running', 'succeeded') AND started_at_ms IS NOT NULL) OR status NOT IN ('running', 'succeeded')),
  CHECK (
    (status IN ('failed', 'cancelled', 'timed_out') AND failure_json IS NOT NULL)
    OR (status NOT IN ('failed', 'cancelled', 'timed_out') AND failure_json IS NULL)
  ),
  CHECK (
    (body_state = 'full' AND input_json IS NOT NULL AND bodies_compacted_at_ms IS NULL)
    OR (body_state = 'compacted' AND input_json IS NULL AND result_json IS NULL
      AND bodies_compacted_at_ms IS NOT NULL)
  ),
  CHECK (output_byte_size <= output_byte_limit),
  CHECK (log_byte_size <= log_byte_limit),
  CHECK ((retry_mode = 'none' AND max_attempts = 1) OR retry_mode = 'idempotent')
) STRICT;

CREATE TABLE function_attempts (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  invocation_id TEXT NOT NULL,
  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
  lease_epoch INTEGER NOT NULL CHECK (lease_epoch >= 1),
  status function_attempt_status NOT NULL,
  sandbox_driver TEXT NOT NULL CHECK (length(trim(sandbox_driver)) BETWEEN 1 AND 100),
  memory_tier TEXT NOT NULL CHECK (memory_tier IN ('small', 'medium', 'large')),
  active_wall_ms INTEGER NOT NULL CHECK (active_wall_ms >= 0),
  cpu_ms INTEGER NOT NULL CHECK (cpu_ms >= 0),
  allocated_memory_byte_ms INTEGER NOT NULL CHECK (allocated_memory_byte_ms >= 0),
  peak_rss_bytes INTEGER NOT NULL CHECK (peak_rss_bytes >= 0),
  disk_read_bytes INTEGER NOT NULL CHECK (disk_read_bytes >= 0),
  disk_write_bytes INTEGER NOT NULL CHECK (disk_write_bytes >= 0),
  network_rx_bytes INTEGER NOT NULL CHECK (network_rx_bytes >= 0),
  network_tx_bytes INTEGER NOT NULL CHECK (network_tx_bytes >= 0),
  output_byte_size INTEGER NOT NULL CHECK (output_byte_size >= 0),
  log_byte_size INTEGER NOT NULL CHECK (log_byte_size >= 0),
  cold_start BOOLEAN NOT NULL,
  failure_owner TEXT CHECK (failure_owner IS NULL OR failure_owner IN ('user', 'platform', 'cancelled')),
  failure_json JSON CHECK (
    failure_json IS NULL OR (json_type(failure_json) = 'object')
  ),
  billable BOOLEAN NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  started_at_ms INTEGER CHECK (started_at_ms IS NULL OR started_at_ms >= created_at_ms),
  guest_code_entered_at_ms INTEGER CHECK (
    guest_code_entered_at_ms IS NULL
    OR (started_at_ms IS NOT NULL AND guest_code_entered_at_ms >= started_at_ms)
  ),
  finished_at_ms INTEGER CHECK (
    finished_at_ms IS NULL OR finished_at_ms >= coalesce(started_at_ms, created_at_ms)
  ),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, invocation_id, id),
  UNIQUE (org_id, invocation_id, attempt_number),
  UNIQUE (org_id, invocation_id, lease_epoch),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id) REFERENCES function_invocations (org_id, id) ON DELETE RESTRICT,
  CHECK (
    (status IN ('succeeded', 'failed', 'cancelled', 'timed_out', 'lost') AND finished_at_ms IS NOT NULL)
    OR (status IN ('starting', 'running') AND finished_at_ms IS NULL)
  ),
  CHECK ((status = 'starting' AND started_at_ms IS NULL) OR status <> 'starting'),
  CHECK ((status IN ('running', 'succeeded') AND started_at_ms IS NOT NULL)
    OR status NOT IN ('running', 'succeeded')),
  CHECK ((status = 'succeeded' AND failure_owner IS NULL AND failure_json IS NULL) OR status <> 'succeeded'),
  CHECK (
    (status IN ('failed', 'cancelled', 'timed_out', 'lost')
      AND failure_owner IS NOT NULL AND failure_json IS NOT NULL)
    OR status NOT IN ('failed', 'cancelled', 'timed_out', 'lost')
  )
) STRICT;

CREATE TABLE invocation_leases (
  org_id TEXT NOT NULL,
  invocation_id TEXT NOT NULL,
  attempt_id TEXT NOT NULL,
  lease_epoch INTEGER NOT NULL CHECK (lease_epoch >= 1),
  worker_id TEXT NOT NULL CHECK (length(trim(worker_id)) BETWEEN 1 AND 200),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  heartbeat_at_ms INTEGER NOT NULL CHECK (heartbeat_at_ms >= created_at_ms),
  expires_at_ms INTEGER NOT NULL CHECK (expires_at_ms > heartbeat_at_ms),
  PRIMARY KEY (org_id, invocation_id),
  UNIQUE (org_id, invocation_id, lease_epoch),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id) REFERENCES function_invocations (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, invocation_id, attempt_id)
    REFERENCES function_attempts (org_id, invocation_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE idempotency_records (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  function_id TEXT NOT NULL CHECK (length(trim(function_id)) BETWEEN 1 AND 200),
  scope_kind TEXT NOT NULL CHECK (scope_kind IN ('organization', 'canvas', 'widget_instance')),
  canvas_id TEXT,
  widget_instance_id TEXT,
  idempotency_key TEXT NOT NULL CHECK (length(trim(idempotency_key)) BETWEEN 1 AND 300),
  request_fingerprint_sha256 sha256_hex NOT NULL,
  widget_definition_id TEXT NOT NULL,
  widget_revision_id TEXT NOT NULL,
  invocation_id TEXT NOT NULL,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  expires_at_ms INTEGER CHECK (expires_at_ms IS NULL OR expires_at_ms > created_at_ms),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, widget_instance_id) REFERENCES widget_instances (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id) REFERENCES function_invocations (org_id, id) ON DELETE RESTRICT,
  CHECK (
    (scope_kind = 'organization' AND canvas_id IS NULL AND widget_instance_id IS NULL)
    OR (scope_kind = 'canvas' AND canvas_id IS NOT NULL AND widget_instance_id IS NULL)
    OR (scope_kind = 'widget_instance' AND canvas_id IS NULL AND widget_instance_id IS NOT NULL)
  )
) STRICT;

CREATE TABLE resource_write_permits (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  invocation_id TEXT NOT NULL,
  attempt_id TEXT NOT NULL,
  lease_epoch INTEGER NOT NULL CHECK (lease_epoch >= 1),
  operation_name TEXT NOT NULL CHECK (length(trim(operation_name)) BETWEEN 1 AND 200),
  operation_id TEXT NOT NULL CHECK (length(trim(operation_id)) BETWEEN 1 AND 200),
  operation_fingerprint_sha256 sha256_hex NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active', 'consumed', 'revoked', 'expired')),
  result_json JSON,
  result_digest_sha256 sha256_hex,
  issued_at_ms INTEGER NOT NULL CHECK (issued_at_ms >= 0),
  expires_at_ms INTEGER NOT NULL CHECK (expires_at_ms > issued_at_ms),
  consumed_at_ms INTEGER CHECK (consumed_at_ms IS NULL OR consumed_at_ms >= issued_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id, id),
  UNIQUE (org_id, resource_id, invocation_id, operation_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id) REFERENCES function_invocations (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id, attempt_id)
    REFERENCES function_attempts (org_id, invocation_id, id) ON DELETE RESTRICT,
  CHECK (
    (status = 'consumed' AND consumed_at_ms IS NOT NULL)
    OR (status <> 'consumed' AND consumed_at_ms IS NULL)
  ),
  CHECK (
    (status = 'consumed' AND result_json IS NOT NULL AND result_digest_sha256 IS NOT NULL)
    OR (status <> 'consumed' AND result_json IS NULL AND result_digest_sha256 IS NULL)
  )
) STRICT;

CREATE TABLE usage_outbox (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  attempt_id TEXT,
  invocation_id TEXT NOT NULL,
  function_id TEXT NOT NULL CHECK (length(trim(function_id)) BETWEEN 1 AND 200),
  definition_revision INTEGER NOT NULL CHECK (definition_revision >= 1),
  sandbox_driver TEXT NOT NULL CHECK (length(trim(sandbox_driver)) BETWEEN 1 AND 100),
  memory_tier TEXT NOT NULL CHECK (memory_tier IN ('small', 'medium', 'large')),
  queued_at_ms INTEGER NOT NULL CHECK (queued_at_ms >= 0),
  started_at_ms INTEGER CHECK (started_at_ms IS NULL OR started_at_ms >= queued_at_ms),
  finished_at_ms INTEGER NOT NULL CHECK (
    finished_at_ms >= queued_at_ms
    AND (started_at_ms IS NULL OR finished_at_ms >= started_at_ms)
  ),
  cold_start BOOLEAN NOT NULL,
  resource_id TEXT,
  resource_permit_id TEXT,
  state TEXT NOT NULL CHECK (state IN ('pending', 'importing', 'imported', 'error')),
  outcome usage_outcome NOT NULL,
  failure_owner TEXT CHECK (failure_owner IS NULL OR failure_owner IN ('user', 'platform', 'cancelled')),
  billable BOOLEAN NOT NULL,
  policy_version INTEGER NOT NULL CHECK (policy_version >= 1),
  active_wall_ms INTEGER NOT NULL CHECK (active_wall_ms >= 0),
  cpu_ms INTEGER NOT NULL CHECK (cpu_ms >= 0),
  allocated_memory_byte_ms INTEGER NOT NULL CHECK (allocated_memory_byte_ms >= 0),
  peak_rss_bytes INTEGER NOT NULL CHECK (peak_rss_bytes >= 0),
  disk_read_bytes INTEGER NOT NULL CHECK (disk_read_bytes >= 0),
  disk_write_bytes INTEGER NOT NULL CHECK (disk_write_bytes >= 0),
  network_rx_bytes INTEGER NOT NULL CHECK (network_rx_bytes >= 0),
  network_tx_bytes INTEGER NOT NULL CHECK (network_tx_bytes >= 0),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  imported_at_ms INTEGER CHECK (imported_at_ms IS NULL OR imported_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id)
    REFERENCES function_invocations (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, attempt_id) REFERENCES function_attempts (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id, resource_permit_id)
    REFERENCES resource_write_permits (org_id, resource_id, id) ON DELETE RESTRICT,
  CHECK (
    (attempt_id IS NOT NULL AND resource_id IS NULL AND resource_permit_id IS NULL)
    OR (attempt_id IS NULL AND resource_id IS NOT NULL AND resource_permit_id IS NOT NULL)
  ),
  CHECK ((state = 'imported' AND imported_at_ms IS NOT NULL) OR (state <> 'imported' AND imported_at_ms IS NULL)),
  CHECK ((outcome = 'succeeded' AND failure_owner IS NULL) OR outcome <> 'succeeded'),
  CHECK ((outcome <> 'succeeded' AND failure_owner IS NOT NULL) OR outcome = 'succeeded')
) STRICT;

CREATE TABLE media_files (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  canvas_id TEXT,
  source_hash TEXT NOT NULL CHECK (
    length(source_hash) BETWEEN 1 AND 200 AND source_hash = trim(source_hash)
  ),
  digest_sha256 sha256_hex,
  mime_type TEXT NOT NULL CHECK (
    length(mime_type) BETWEEN 3 AND 200
    AND mime_type = lower(trim(mime_type))
    AND instr(mime_type, '/') > 1
  ),
  byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
  data BLOB NOT NULL CHECK (length(data) = byte_size),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE tool_groups (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  configuration_json JSON CHECK (
    configuration_json IS NULL
    OR (json_type(configuration_json) = 'object')
  ),
  status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE
) STRICT;

CREATE TABLE agent_chats (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  account_id TEXT NOT NULL,
  canvas_id TEXT,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('active', 'archived', 'error')),
  workspace_relative_path TEXT NOT NULL CHECK (
    length(workspace_relative_path) BETWEEN 1 AND 1024
    AND workspace_relative_path = trim(workspace_relative_path)
    AND substr(workspace_relative_path, 1, 1) <> '/'
    AND workspace_relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(workspace_relative_path, '\') = 0
    AND workspace_relative_path <> '.' AND workspace_relative_path <> '..'
    AND workspace_relative_path NOT LIKE './%' AND workspace_relative_path NOT LIKE '../%'
    AND workspace_relative_path NOT LIKE '%/./%' AND workspace_relative_path NOT LIKE '%/../%'
    AND workspace_relative_path NOT LIKE '%/.' AND workspace_relative_path NOT LIKE '%/..'
    AND workspace_relative_path NOT LIKE '%//%'
  ),
  history_relative_path TEXT NOT NULL CHECK (
    length(history_relative_path) BETWEEN 1 AND 1024
    AND history_relative_path = trim(history_relative_path)
    AND substr(history_relative_path, 1, 1) <> '/'
    AND history_relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(history_relative_path, '\') = 0
    AND history_relative_path <> '.' AND history_relative_path <> '..'
    AND history_relative_path NOT LIKE './%' AND history_relative_path NOT LIKE '../%'
    AND history_relative_path NOT LIKE '%/./%' AND history_relative_path NOT LIKE '%/../%'
    AND history_relative_path NOT LIKE '%/.' AND history_relative_path NOT LIKE '%/..'
    AND history_relative_path NOT LIKE '%//%'
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  external_session_key TEXT CHECK (
    external_session_key IS NULL OR (
      length(external_session_key) BETWEEN 1 AND 300
      AND external_session_key = trim(external_session_key)
    )
  ),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, workspace_relative_path),
  UNIQUE (org_id, history_relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE RESTRICT
) STRICT;

CREATE TABLE agent_drafts (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL,
  chat_id TEXT NOT NULL,
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status agent_draft_status NOT NULL,
  source_relative_path TEXT NOT NULL CHECK (
    length(source_relative_path) BETWEEN 1 AND 1024
    AND source_relative_path = trim(source_relative_path)
    AND substr(source_relative_path, 1, 1) <> '/'
    AND source_relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(source_relative_path, '\') = 0
    AND source_relative_path <> '.' AND source_relative_path <> '..'
    AND source_relative_path NOT LIKE './%' AND source_relative_path NOT LIKE '../%'
    AND source_relative_path NOT LIKE '%/./%' AND source_relative_path NOT LIKE '%/../%'
    AND source_relative_path NOT LIKE '%/.' AND source_relative_path NOT LIKE '%/..'
    AND source_relative_path NOT LIKE '%//%'
  ),
  source_digest_sha256 sha256_hex,
  last_error_json JSON CHECK (
    last_error_json IS NULL OR (json_type(last_error_json) = 'object')
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  definition_id TEXT,
  published_revision_id TEXT,
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, chat_id, source_relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, chat_id) REFERENCES agent_chats (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE function_definitions (
  org_id TEXT NOT NULL,
  id TEXT NOT NULL CHECK (length(trim(id)) BETWEEN 1 AND 200),
  widget_definition_id TEXT NOT NULL,
  widget_revision_id TEXT NOT NULL,
  export_name TEXT NOT NULL CHECK (length(trim(export_name)) BETWEEN 1 AND 200),
  effect TEXT NOT NULL CHECK (effect IN ('fn', 'fx', 'tx')),
  definition_revision INTEGER NOT NULL CHECK (definition_revision >= 1),
  server_artifact_id TEXT NOT NULL,
  server_artifact_kind TEXT NOT NULL DEFAULT 'server' CHECK (server_artifact_kind = 'server'),
  artifact_digest_sha256 sha256_hex NOT NULL,
  contract_digest_sha256 sha256_hex NOT NULL,
  descriptor_digest_sha256 sha256_hex NOT NULL,
  runtime_abi TEXT NOT NULL CHECK (length(trim(runtime_abi)) BETWEEN 1 AND 100),
  input_schema_json JSON NOT NULL CHECK (
    json_type(input_schema_json) = 'object'
  ),
  output_schema_json JSON NOT NULL CHECK (
    json_type(output_schema_json) = 'object'
  ),
  resources_json JSON NOT NULL CHECK (
    json_type(resources_json) = 'array'
  ),
  timeout_ms INTEGER NOT NULL CHECK (timeout_ms >= 1),
  memory_tier TEXT NOT NULL CHECK (memory_tier IN ('small', 'medium', 'large')),
  output_byte_limit INTEGER NOT NULL CHECK (output_byte_limit >= 1),
  log_byte_limit INTEGER NOT NULL CHECK (log_byte_limit >= 0),
  retry_mode TEXT NOT NULL CHECK (retry_mode IN ('none', 'idempotent')),
  max_attempts INTEGER NOT NULL CHECK (max_attempts BETWEEN 1 AND 100),
  initial_backoff_ms INTEGER NOT NULL CHECK (initial_backoff_ms >= 0),
  max_backoff_ms INTEGER NOT NULL CHECK (max_backoff_ms >= initial_backoff_ms),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, widget_definition_id, widget_revision_id, id),
  UNIQUE (org_id, widget_definition_id, widget_revision_id, export_name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, widget_definition_id, widget_revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, server_artifact_id, server_artifact_kind)
    REFERENCES artifact_references (org_id, id, kind) ON DELETE RESTRICT,
  CHECK ((retry_mode = 'none' AND max_attempts = 1) OR retry_mode = 'idempotent')
) STRICT;

CREATE TABLE widget_revision_sources (
  org_id TEXT NOT NULL,
  definition_id TEXT NOT NULL,
  revision_id TEXT NOT NULL,
  source_snapshot_id TEXT NOT NULL,
  source_artifact_id TEXT NOT NULL,
  source_artifact_kind TEXT NOT NULL DEFAULT 'source' CHECK (source_artifact_kind = 'source'),
  source_digest_sha256 sha256_hex NOT NULL,
  builder_identity TEXT NOT NULL CHECK (length(trim(builder_identity)) BETWEEN 1 AND 300),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, revision_id),
  UNIQUE (org_id, definition_id, revision_id),
  UNIQUE (org_id, source_snapshot_id, revision_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, definition_id, revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, source_artifact_id, source_artifact_kind)
    REFERENCES artifact_references (org_id, id, kind) ON DELETE RESTRICT
) STRICT;

CREATE INDEX organization_memberships_account_idx
  ON organization_memberships (account_id, org_id);

CREATE INDEX organization_memberships_status_idx
  ON organization_memberships (org_id, status, role);

CREATE INDEX canvases_creator_idx ON canvases (org_id, created_by_account_id);

CREATE INDEX canvas_members_account_idx ON canvas_members (org_id, account_id, canvas_id);

CREATE INDEX canvas_items_kind_idx
  ON canvas_items (org_id, canvas_id, kind, id);

CREATE INDEX canvas_items_parent_order_idx
  ON canvas_items (org_id, canvas_id, parent_id, order_key, id);

CREATE UNIQUE INDEX canvas_items_widget_instance_idx
  ON canvas_items (org_id, widget_instance_id)
  WHERE widget_instance_id IS NOT NULL;

CREATE INDEX canvas_items_widget_definition_revision_idx
  ON canvas_items (org_id, definition_id, revision_id, widget_instance_id, id)
  WHERE widget_instance_id IS NOT NULL;

CREATE INDEX artifact_references_retention_idx
  ON artifact_references (org_id, retention_state, retain_until_ms);

CREATE INDEX widget_definitions_active_revision_idx
  ON widget_definitions (org_id, id, active_revision_id);

CREATE INDEX widget_definition_revisions_lookup_idx
  ON widget_definition_revisions (org_id, definition_id, revision_number);

CREATE INDEX widget_definition_revisions_ui_artifact_idx
  ON widget_definition_revisions (org_id, ui_artifact_id, ui_artifact_kind);

CREATE INDEX widget_definition_revisions_server_artifact_idx
  ON widget_definition_revisions (org_id, server_artifact_id, server_artifact_kind);

CREATE INDEX widget_definition_revisions_capsule_artifact_idx
  ON widget_definition_revisions (org_id, capsule_artifact_hash);

CREATE INDEX widget_instances_definition_idx
  ON widget_instances (org_id, definition_id, revision_id);

CREATE INDEX resource_catalog_status_idx ON resource_catalog (org_id, status, created_at_ms);

CREATE INDEX resource_catalog_kind_idx ON resource_catalog (org_id, kind, status);

CREATE INDEX resource_bindings_resource_idx
  ON resource_bindings (org_id, resource_id, resource_kind);

CREATE INDEX resource_placements_cell_idx
  ON resource_placements (org_id, cell_id, status);

CREATE INDEX db_resource_drafts_resource_idx
  ON db_resource_drafts (org_id, resource_id, status, created_at_ms);

CREATE INDEX db_resource_drafts_resource_kind_idx
  ON db_resource_drafts (org_id, resource_id, resource_kind);

CREATE UNIQUE INDEX db_resource_drafts_one_active_idx
  ON db_resource_drafts (org_id, resource_id)
  WHERE status IN ('editing', 'applying');

CREATE INDEX db_resource_apply_runs_resource_idx
  ON db_resource_apply_runs (org_id, resource_id, status, created_at_ms);

CREATE INDEX db_resource_apply_runs_draft_idx
  ON db_resource_apply_runs (org_id, resource_id, draft_id);

CREATE INDEX db_resource_apply_runs_source_idx
  ON db_resource_apply_runs (org_id, resource_id, source_apply_id);

CREATE UNIQUE INDEX db_resource_apply_runs_one_active_idx
  ON db_resource_apply_runs (org_id, resource_id)
  WHERE status IN ('preparing', 'applying');

CREATE INDEX db_resource_backups_retention_idx
  ON db_resource_backups (org_id, state, delete_after_ms);

CREATE INDEX function_invocations_queue_idx
  ON function_invocations (
    org_id, status, memory_tier, available_at_ms, priority DESC, created_at_ms
  );

CREATE INDEX function_invocations_revision_idx
  ON function_invocations (
    org_id, widget_definition_id, widget_revision_id, retains_revision, created_at_ms
  );

CREATE INDEX function_invocations_account_idx
  ON function_invocations (org_id, account_id, created_at_ms);

CREATE INDEX function_invocations_instance_idx
  ON function_invocations (
    org_id, widget_definition_id, widget_revision_id, widget_instance_id
  );

CREATE INDEX function_attempts_invocation_idx
  ON function_attempts (org_id, invocation_id, attempt_number);

CREATE INDEX invocation_leases_expiry_idx ON invocation_leases (expires_at_ms, org_id);

CREATE INDEX invocation_leases_attempt_idx
  ON invocation_leases (org_id, invocation_id, attempt_id);

CREATE UNIQUE INDEX idempotency_records_org_key_idx
  ON idempotency_records (org_id, function_id, idempotency_key)
  WHERE scope_kind = 'organization';

CREATE UNIQUE INDEX idempotency_records_canvas_key_idx
  ON idempotency_records (org_id, canvas_id, function_id, idempotency_key)
  WHERE scope_kind = 'canvas';

CREATE UNIQUE INDEX idempotency_records_widget_key_idx
  ON idempotency_records (org_id, widget_instance_id, function_id, idempotency_key)
  WHERE scope_kind = 'widget_instance';

CREATE INDEX idempotency_records_expiry_idx
  ON idempotency_records (org_id, expires_at_ms);

CREATE INDEX idempotency_records_revision_idx
  ON idempotency_records (org_id, widget_definition_id, widget_revision_id);

CREATE INDEX idempotency_records_invocation_idx
  ON idempotency_records (org_id, invocation_id);

CREATE INDEX resource_write_permits_expiry_idx
  ON resource_write_permits (org_id, status, expires_at_ms);

CREATE INDEX resource_write_permits_attempt_idx
  ON resource_write_permits (org_id, invocation_id, attempt_id, lease_epoch);

CREATE UNIQUE INDEX usage_outbox_attempt_receipt_idx
  ON usage_outbox (org_id, attempt_id) WHERE attempt_id IS NOT NULL;

CREATE UNIQUE INDEX usage_outbox_resource_receipt_idx
  ON usage_outbox (org_id, resource_permit_id) WHERE resource_permit_id IS NOT NULL;

CREATE INDEX usage_outbox_import_idx ON usage_outbox (org_id, state, created_at_ms);

CREATE INDEX usage_outbox_account_idx ON usage_outbox (org_id, account_id, created_at_ms);

CREATE INDEX usage_outbox_resource_permit_idx
  ON usage_outbox (org_id, resource_id, resource_permit_id);

CREATE INDEX media_files_canvas_idx ON media_files (org_id, canvas_id, created_at_ms);

CREATE INDEX media_files_source_hash_idx ON media_files (org_id, source_hash);

CREATE INDEX media_files_digest_idx ON media_files (org_id, digest_sha256);

CREATE INDEX agent_chats_account_idx ON agent_chats (org_id, account_id, created_at_ms);

CREATE INDEX agent_chats_canvas_idx ON agent_chats (org_id, canvas_id, created_at_ms);

CREATE INDEX agent_drafts_chat_idx ON agent_drafts (org_id, chat_id, created_at_ms);

CREATE INDEX function_definitions_lookup_idx
  ON function_definitions (org_id, widget_revision_id, export_name);

CREATE INDEX function_definitions_artifact_idx
  ON function_definitions (org_id, server_artifact_id, server_artifact_kind);

CREATE UNIQUE INDEX agent_chats_external_session_idx
  ON agent_chats (org_id, account_id, external_session_key)
  WHERE external_session_key IS NOT NULL;

CREATE INDEX agent_drafts_definition_idx
  ON agent_drafts (org_id, definition_id, published_revision_id);

CREATE INDEX widget_revision_sources_artifact_idx
  ON widget_revision_sources (org_id, source_artifact_id, source_artifact_kind);

CREATE INDEX usage_outbox_invocation_idx
  ON usage_outbox (org_id, invocation_id);

INSERT INTO organizations (id, slug, name, status, created_at_ms, updated_at_ms)
VALUES ('00000000-0000-4000-8000-000000000001', 'local', 'Local', 'active', 0, 0);

INSERT INTO accounts (id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms)
VALUES ('00000000-0000-4000-8000-000000000002', 'user', 'Local Owner', 'active', 1, 0, 0);

INSERT INTO organization_memberships (
  org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
)
VALUES (
  '00000000-0000-4000-8000-000000000001',
  '00000000-0000-4000-8000-000000000002',
  'owner', 'active', 1, 0, 0
);
