CREATE TABLE schema_migrations (
  version INTEGER PRIMARY KEY CHECK (version >= 0),
  name TEXT NOT NULL UNIQUE CHECK (length(trim(name)) BETWEEN 1 AND 200),
  checksum_sha256 TEXT NOT NULL CHECK (
    length(checksum_sha256) = 64
    AND checksum_sha256 = lower(checksum_sha256)
    AND checksum_sha256 NOT GLOB '*[^0-9a-f]*'
  ),
  applied_at_ms INTEGER NOT NULL CHECK (applied_at_ms >= 0),
  application_version TEXT NOT NULL CHECK (length(trim(application_version)) BETWEEN 1 AND 100)
) STRICT;

CREATE TABLE accounts (
  id TEXT PRIMARY KEY NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  kind TEXT NOT NULL CHECK (kind IN ('user', 'service_account', 'system', 'anonymous')),
  display_name TEXT NOT NULL CHECK (length(trim(display_name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
  is_autogenerated INTEGER NOT NULL CHECK (is_autogenerated IN (0, 1)),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms)
) STRICT;

CREATE TABLE organizations (
  id TEXT PRIMARY KEY NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  slug TEXT NOT NULL UNIQUE CHECK (
    length(slug) BETWEEN 1 AND 100
    AND slug = lower(trim(slug))
    AND substr(slug, 1, 1) <> '-'
    AND substr(slug, -1, 1) <> '-'
    AND instr(slug, '--') = 0
    AND slug NOT GLOB '*[^a-z0-9-]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('active', 'suspended', 'archived')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms)
) STRICT;

CREATE TABLE organization_memberships (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  account_id TEXT NOT NULL CHECK (
    length(account_id) = 36 AND account_id = lower(account_id)
    AND substr(account_id, 9, 1) = '-' AND substr(account_id, 14, 1) = '-'
    AND substr(account_id, 19, 1) = '-' AND substr(account_id, 24, 1) = '-'
    AND length(replace(account_id, '-', '')) = 32
    AND replace(account_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member', 'viewer')),
  status TEXT NOT NULL CHECK (status IN ('invited', 'active', 'suspended')),
  is_billable_seat INTEGER NOT NULL CHECK (is_billable_seat IN (0, 1)),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, account_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (account_id) REFERENCES accounts (id) ON DELETE RESTRICT
) STRICT;

CREATE INDEX organization_memberships_account_idx
  ON organization_memberships (account_id, org_id);
CREATE INDEX organization_memberships_status_idx
  ON organization_memberships (org_id, status, role);

CREATE TABLE key_values (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 300),
  kind TEXT NOT NULL CHECK (kind IN ('text', 'json', 'number', 'bool', 'blob')),
  text_value TEXT,
  json_value TEXT CHECK (json_value IS NULL OR json_valid(json_value)),
  number_value REAL,
  bool_value INTEGER CHECK (bool_value IS NULL OR bool_value IN (0, 1)),
  blob_value BLOB,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  CHECK (
    (kind = 'text' AND text_value IS NOT NULL AND json_value IS NULL AND number_value IS NULL AND bool_value IS NULL AND blob_value IS NULL)
    OR (kind = 'json' AND text_value IS NULL AND json_value IS NOT NULL AND number_value IS NULL AND bool_value IS NULL AND blob_value IS NULL)
    OR (kind = 'number' AND text_value IS NULL AND json_value IS NULL AND number_value IS NOT NULL AND bool_value IS NULL AND blob_value IS NULL)
    OR (kind = 'bool' AND text_value IS NULL AND json_value IS NULL AND number_value IS NULL AND bool_value IS NOT NULL AND blob_value IS NULL)
    OR (kind = 'blob' AND text_value IS NULL AND json_value IS NULL AND number_value IS NULL AND bool_value IS NULL AND blob_value IS NOT NULL)
  )
) STRICT;

CREATE TABLE canvases (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  access_policy TEXT NOT NULL CHECK (access_policy IN ('org', 'restricted')),
  created_by_account_id TEXT NOT NULL CHECK (
    length(created_by_account_id) = 36 AND created_by_account_id = lower(created_by_account_id)
    AND substr(created_by_account_id, 9, 1) = '-' AND substr(created_by_account_id, 14, 1) = '-'
    AND substr(created_by_account_id, 19, 1) = '-' AND substr(created_by_account_id, 24, 1) = '-'
    AND length(replace(created_by_account_id, '-', '')) = 32
    AND replace(created_by_account_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, created_by_account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT
) STRICT;

CREATE INDEX canvases_creator_idx ON canvases (org_id, created_by_account_id);

CREATE TABLE canvas_members (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  canvas_id TEXT NOT NULL CHECK (
    length(canvas_id) = 36 AND canvas_id = lower(canvas_id)
    AND substr(canvas_id, 9, 1) = '-' AND substr(canvas_id, 14, 1) = '-'
    AND substr(canvas_id, 19, 1) = '-' AND substr(canvas_id, 24, 1) = '-'
    AND length(replace(canvas_id, '-', '')) = 32
    AND replace(canvas_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  account_id TEXT NOT NULL CHECK (
    length(account_id) = 36 AND account_id = lower(account_id)
    AND substr(account_id, 9, 1) = '-' AND substr(account_id, 14, 1) = '-'
    AND substr(account_id, 19, 1) = '-' AND substr(account_id, 24, 1) = '-'
    AND length(replace(account_id, '-', '')) = 32
    AND replace(account_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  role TEXT NOT NULL CHECK (role IN ('owner', 'editor', 'viewer')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, canvas_id, account_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE CASCADE
) STRICT;

CREATE INDEX canvas_members_account_idx ON canvas_members (org_id, account_id, canvas_id);

CREATE TABLE artifact_references (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  kind TEXT NOT NULL CHECK (kind IN ('ui', 'server', 'source', 'source_map')),
  digest_sha256 TEXT NOT NULL CHECK (
    length(digest_sha256) = 64 AND digest_sha256 = lower(digest_sha256)
    AND digest_sha256 NOT GLOB '*[^0-9a-f]*'
  ),
  byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
  retention_state TEXT NOT NULL CHECK (retention_state IN ('pinned', 'eligible', 'deleting')),
  retain_until_ms INTEGER CHECK (retain_until_ms IS NULL OR retain_until_ms >= 0),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, id, kind),
  UNIQUE (org_id, kind, digest_sha256),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  CHECK (retention_state <> 'eligible' OR retain_until_ms IS NOT NULL)
) STRICT;

CREATE INDEX artifact_references_retention_idx
  ON artifact_references (org_id, retention_state, retain_until_ms);

CREATE TABLE widget_definitions (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  slug TEXT NOT NULL CHECK (
    length(slug) BETWEEN 1 AND 100 AND slug = lower(trim(slug))
    AND substr(slug, 1, 1) <> '-' AND substr(slug, -1, 1) <> '-'
    AND instr(slug, '--') = 0 AND slug NOT GLOB '*[^a-z0-9-]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('draft', 'published', 'archived')),
  active_revision_id TEXT CHECK (
    active_revision_id IS NULL OR (
      length(active_revision_id) = 36 AND active_revision_id = lower(active_revision_id)
      AND substr(active_revision_id, 9, 1) = '-' AND substr(active_revision_id, 14, 1) = '-'
      AND substr(active_revision_id, 19, 1) = '-' AND substr(active_revision_id, 24, 1) = '-'
      AND length(replace(active_revision_id, '-', '')) = 32
      AND replace(active_revision_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, slug),
  UNIQUE (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, id, active_revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE RESTRICT,
  CHECK ((status = 'published' AND active_revision_id IS NOT NULL) OR status <> 'published')
) STRICT;

CREATE INDEX widget_definitions_active_revision_idx
  ON widget_definitions (org_id, id, active_revision_id);

CREATE TABLE widget_definition_revisions (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  definition_id TEXT NOT NULL CHECK (
    length(definition_id) = 36 AND definition_id = lower(definition_id)
    AND substr(definition_id, 9, 1) = '-' AND substr(definition_id, 14, 1) = '-'
    AND substr(definition_id, 19, 1) = '-' AND substr(definition_id, 24, 1) = '-'
    AND length(replace(definition_id, '-', '')) = 32
    AND replace(definition_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  revision_number INTEGER NOT NULL CHECK (revision_number >= 1),
  ui_artifact_id TEXT NOT NULL CHECK (
    length(ui_artifact_id) = 36 AND ui_artifact_id = lower(ui_artifact_id)
    AND substr(ui_artifact_id, 9, 1) = '-' AND substr(ui_artifact_id, 14, 1) = '-'
    AND substr(ui_artifact_id, 19, 1) = '-' AND substr(ui_artifact_id, 24, 1) = '-'
    AND length(replace(ui_artifact_id, '-', '')) = 32
    AND replace(ui_artifact_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  ui_artifact_kind TEXT NOT NULL DEFAULT 'ui' CHECK (ui_artifact_kind = 'ui'),
  server_artifact_id TEXT CHECK (
    server_artifact_id IS NULL OR (
      length(server_artifact_id) = 36 AND server_artifact_id = lower(server_artifact_id)
      AND substr(server_artifact_id, 9, 1) = '-' AND substr(server_artifact_id, 14, 1) = '-'
      AND substr(server_artifact_id, 19, 1) = '-' AND substr(server_artifact_id, 24, 1) = '-'
      AND length(replace(server_artifact_id, '-', '')) = 32
      AND replace(server_artifact_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  server_artifact_kind TEXT CHECK (
    (server_artifact_id IS NULL AND server_artifact_kind IS NULL)
    OR (server_artifact_id IS NOT NULL AND server_artifact_kind = 'server')
  ),
  manifest_json TEXT NOT NULL CHECK (json_valid(manifest_json) AND json_type(manifest_json) = 'object'),
  contract_digest_sha256 TEXT NOT NULL CHECK (
    length(contract_digest_sha256) = 64
    AND contract_digest_sha256 = lower(contract_digest_sha256)
    AND contract_digest_sha256 NOT GLOB '*[^0-9a-f]*'
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, definition_id, id),
  UNIQUE (org_id, definition_id, revision_number),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, definition_id) REFERENCES widget_definitions (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, ui_artifact_id, ui_artifact_kind)
    REFERENCES artifact_references (org_id, id, kind) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, server_artifact_id, server_artifact_kind)
    REFERENCES artifact_references (org_id, id, kind) ON DELETE RESTRICT,
  CHECK (server_artifact_id IS NULL OR server_artifact_id <> ui_artifact_id)
) STRICT;

CREATE INDEX widget_definition_revisions_lookup_idx
  ON widget_definition_revisions (org_id, definition_id, revision_number);
CREATE INDEX widget_definition_revisions_ui_artifact_idx
  ON widget_definition_revisions (org_id, ui_artifact_id, ui_artifact_kind);
CREATE INDEX widget_definition_revisions_server_artifact_idx
  ON widget_definition_revisions (org_id, server_artifact_id, server_artifact_kind);

CREATE TABLE widget_instances (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  canvas_id TEXT NOT NULL CHECK (
    length(canvas_id) = 36 AND canvas_id = lower(canvas_id)
    AND substr(canvas_id, 9, 1) = '-' AND substr(canvas_id, 14, 1) = '-'
    AND substr(canvas_id, 19, 1) = '-' AND substr(canvas_id, 24, 1) = '-'
    AND length(replace(canvas_id, '-', '')) = 32
    AND replace(canvas_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  element_id TEXT NOT NULL CHECK (length(trim(element_id)) BETWEEN 1 AND 200),
  definition_id TEXT NOT NULL CHECK (
    length(definition_id) = 36 AND definition_id = lower(definition_id)
    AND substr(definition_id, 9, 1) = '-' AND substr(definition_id, 14, 1) = '-'
    AND substr(definition_id, 19, 1) = '-' AND substr(definition_id, 24, 1) = '-'
    AND length(replace(definition_id, '-', '')) = 32
    AND replace(definition_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  revision_id TEXT NOT NULL CHECK (
    length(revision_id) = 36 AND revision_id = lower(revision_id)
    AND substr(revision_id, 9, 1) = '-' AND substr(revision_id, 14, 1) = '-'
    AND substr(revision_id, 19, 1) = '-' AND substr(revision_id, 24, 1) = '-'
    AND length(replace(revision_id, '-', '')) = 32
    AND replace(revision_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  status TEXT NOT NULL CHECK (status IN ('active', 'archived')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, definition_id, revision_id, id),
  UNIQUE (org_id, canvas_id, element_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, definition_id) REFERENCES widget_definitions (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, definition_id, revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE RESTRICT
) STRICT;

CREATE INDEX widget_instances_definition_idx
  ON widget_instances (org_id, definition_id, revision_id);

CREATE TABLE collaboration_documents (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  canvas_id TEXT CHECK (
    canvas_id IS NULL OR (
      length(canvas_id) = 36 AND canvas_id = lower(canvas_id)
      AND substr(canvas_id, 9, 1) = '-' AND substr(canvas_id, 14, 1) = '-'
      AND substr(canvas_id, 19, 1) = '-' AND substr(canvas_id, 24, 1) = '-'
      AND length(replace(canvas_id, '-', '')) = 32
      AND replace(canvas_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  widget_instance_id TEXT CHECK (
    widget_instance_id IS NULL OR (
      length(widget_instance_id) = 36 AND widget_instance_id = lower(widget_instance_id)
      AND substr(widget_instance_id, 9, 1) = '-' AND substr(widget_instance_id, 14, 1) = '-'
      AND substr(widget_instance_id, 19, 1) = '-' AND substr(widget_instance_id, 24, 1) = '-'
      AND length(replace(widget_instance_id, '-', '')) = 32
      AND replace(widget_instance_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  automerge_url TEXT NOT NULL CHECK (length(trim(automerge_url)) BETWEEN 1 AND 500),
  partition_key TEXT NOT NULL CHECK (length(trim(partition_key)) BETWEEN 1 AND 200),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, automerge_url),
  UNIQUE (org_id, canvas_id),
  UNIQUE (org_id, widget_instance_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, widget_instance_id) REFERENCES widget_instances (org_id, id) ON DELETE CASCADE,
  CHECK ((canvas_id IS NOT NULL) <> (widget_instance_id IS NOT NULL))
) STRICT;

CREATE INDEX collaboration_documents_partition_idx
  ON collaboration_documents (org_id, partition_key, id);

CREATE TABLE collaboration_chunks (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  document_id TEXT NOT NULL CHECK (
    length(document_id) = 36 AND document_id = lower(document_id)
    AND substr(document_id, 9, 1) = '-' AND substr(document_id, 14, 1) = '-'
    AND substr(document_id, 19, 1) = '-' AND substr(document_id, 24, 1) = '-'
    AND length(replace(document_id, '-', '')) = 32
    AND replace(document_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  chunk_key TEXT NOT NULL CHECK (length(trim(chunk_key)) BETWEEN 1 AND 300),
  sequence INTEGER NOT NULL CHECK (sequence >= 0),
  chunk_bytes BLOB NOT NULL CHECK (length(chunk_bytes) > 0),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, document_id, chunk_key),
  UNIQUE (org_id, document_id, sequence),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, document_id)
    REFERENCES collaboration_documents (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE resource_catalog (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  kind TEXT NOT NULL CHECK (kind IN ('kv', 'secretStore', 'db')),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (
    status IN ('created', 'provisioning', 'ready', 'migrating', 'error', 'deleting')
  ),
  last_error_json TEXT CHECK (
    last_error_json IS NULL OR (json_valid(last_error_json) AND json_type(last_error_json) = 'object')
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, id, kind),
  UNIQUE (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT
) STRICT;

CREATE INDEX resource_catalog_status_idx ON resource_catalog (org_id, status, created_at_ms);
CREATE INDEX resource_catalog_kind_idx ON resource_catalog (org_id, kind, status);

CREATE TABLE resource_bindings (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  definition_id TEXT NOT NULL CHECK (
    length(definition_id) = 36 AND definition_id = lower(definition_id)
    AND substr(definition_id, 9, 1) = '-' AND substr(definition_id, 14, 1) = '-'
    AND substr(definition_id, 19, 1) = '-' AND substr(definition_id, 24, 1) = '-'
    AND length(replace(definition_id, '-', '')) = 32
    AND replace(definition_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  revision_id TEXT NOT NULL CHECK (
    length(revision_id) = 36 AND revision_id = lower(revision_id)
    AND substr(revision_id, 9, 1) = '-' AND substr(revision_id, 14, 1) = '-'
    AND substr(revision_id, 19, 1) = '-' AND substr(revision_id, 24, 1) = '-'
    AND length(replace(revision_id, '-', '')) = 32
    AND replace(revision_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  slot_name TEXT NOT NULL CHECK (length(trim(slot_name)) BETWEEN 1 AND 200),
  resource_id TEXT NOT NULL CHECK (
    length(resource_id) = 36 AND resource_id = lower(resource_id)
    AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
    AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
    AND length(replace(resource_id, '-', '')) = 32
    AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  resource_kind TEXT NOT NULL CHECK (resource_kind IN ('kv', 'secretStore', 'db')),
  is_required INTEGER NOT NULL CHECK (is_required IN (0, 1)),
  manifest_allow_read INTEGER NOT NULL CHECK (manifest_allow_read IN (0, 1)),
  manifest_allow_write INTEGER NOT NULL CHECK (manifest_allow_write IN (0, 1)),
  allow_read INTEGER NOT NULL CHECK (allow_read IN (0, 1)),
  allow_write INTEGER NOT NULL CHECK (allow_write IN (0, 1)),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, definition_id, revision_id, slot_name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, definition_id, revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id, resource_kind)
    REFERENCES resource_catalog (org_id, id, kind) ON DELETE RESTRICT,
  CHECK (manifest_allow_read = 1 OR manifest_allow_write = 1),
  CHECK (allow_read = 1 OR allow_write = 1),
  CHECK (allow_read <= manifest_allow_read AND allow_write <= manifest_allow_write)
) STRICT;

CREATE INDEX resource_bindings_resource_idx
  ON resource_bindings (org_id, resource_id, resource_kind);

CREATE TABLE resource_placements (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  resource_id TEXT NOT NULL CHECK (
    length(resource_id) = 36 AND resource_id = lower(resource_id)
    AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
    AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
    AND length(replace(resource_id, '-', '')) = 32
    AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  cell_id TEXT NOT NULL CHECK (
    length(cell_id) = 36 AND cell_id = lower(cell_id)
    AND substr(cell_id, 9, 1) = '-' AND substr(cell_id, 14, 1) = '-'
    AND substr(cell_id, 19, 1) = '-' AND substr(cell_id, 24, 1) = '-'
    AND length(replace(cell_id, '-', '')) = 32
    AND replace(cell_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  placement_epoch INTEGER NOT NULL CHECK (placement_epoch >= 1),
  relative_path TEXT NOT NULL CHECK (
    length(relative_path) BETWEEN 1 AND 1024
    AND relative_path = trim(relative_path)
    AND substr(relative_path, 1, 1) <> '/'
    AND relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(relative_path, '\') = 0
    AND relative_path <> '.' AND relative_path <> '..'
    AND relative_path NOT LIKE './%' AND relative_path NOT LIKE '../%'
    AND relative_path NOT LIKE '%/./%' AND relative_path NOT LIKE '%/../%'
    AND relative_path NOT LIKE '%/.' AND relative_path NOT LIKE '%/..'
    AND relative_path NOT LIKE '%//%'
  ),
  status TEXT NOT NULL CHECK (status IN ('reserved', 'active', 'moving', 'error')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, resource_id),
  UNIQUE (org_id, relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE INDEX resource_placements_cell_idx
  ON resource_placements (org_id, cell_id, status);

CREATE TABLE resource_encryption_keys (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  resource_id TEXT NOT NULL CHECK (
    length(resource_id) = 36 AND resource_id = lower(resource_id)
    AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
    AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
    AND length(replace(resource_id, '-', '')) = 32
    AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  purpose TEXT NOT NULL CHECK (purpose = 'resource-data'),
  algorithm TEXT NOT NULL CHECK (algorithm = 'aegis-256'),
  key_material BLOB NOT NULL CHECK (length(key_material) = 32),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE TABLE db_resource_drafts (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  resource_id TEXT NOT NULL CHECK (
    length(resource_id) = 36 AND resource_id = lower(resource_id)
    AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
    AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
    AND length(replace(resource_id, '-', '')) = 32
    AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  resource_kind TEXT NOT NULL DEFAULT 'db' CHECK (resource_kind = 'db'),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('editing', 'applying', 'applied', 'discarded', 'error')),
  last_error_json TEXT CHECK (
    last_error_json IS NULL OR (json_valid(last_error_json) AND json_type(last_error_json) = 'object')
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  applied_at_ms INTEGER CHECK (applied_at_ms IS NULL OR applied_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id, resource_kind)
    REFERENCES resource_catalog (org_id, id, kind) ON DELETE CASCADE,
  CHECK ((status = 'applied' AND applied_at_ms IS NOT NULL) OR (status <> 'applied' AND applied_at_ms IS NULL))
) STRICT;

CREATE INDEX db_resource_drafts_resource_idx
  ON db_resource_drafts (org_id, resource_id, status, created_at_ms);
CREATE INDEX db_resource_drafts_resource_kind_idx
  ON db_resource_drafts (org_id, resource_id, resource_kind);
CREATE UNIQUE INDEX db_resource_drafts_one_active_idx
  ON db_resource_drafts (org_id, resource_id)
  WHERE status IN ('editing', 'applying');

CREATE TABLE db_resource_draft_changes (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  draft_id TEXT NOT NULL CHECK (
    length(draft_id) = 36 AND draft_id = lower(draft_id)
    AND substr(draft_id, 9, 1) = '-' AND substr(draft_id, 14, 1) = '-'
    AND substr(draft_id, 19, 1) = '-' AND substr(draft_id, 24, 1) = '-'
    AND length(replace(draft_id, '-', '')) = 32
    AND replace(draft_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  sequence INTEGER NOT NULL CHECK (sequence >= 1),
  kind TEXT NOT NULL CHECK (kind IN ('structure', 'sql')),
  operation_json TEXT CHECK (
    operation_json IS NULL OR (json_valid(operation_json) AND json_type(operation_json) = 'object')
  ),
  sql_text TEXT NOT NULL CHECK (length(trim(sql_text)) BETWEEN 1 AND 1000000),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, draft_id, sequence),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, draft_id) REFERENCES db_resource_drafts (org_id, id) ON DELETE CASCADE,
  CHECK (
    (kind = 'structure' AND operation_json IS NOT NULL)
    OR (
      kind = 'sql'
      AND (
        operation_json IS NULL
        OR COALESCE(
          json_type(operation_json, '$.type') = 'text'
          AND json_extract(operation_json, '$.type') = 'boundSql'
          AND json_type(operation_json, '$.parameters') = 'array',
          0
        )
      )
    )
  )
) STRICT;

CREATE TABLE db_resource_apply_runs (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  resource_id TEXT NOT NULL CHECK (
    length(resource_id) = 36 AND resource_id = lower(resource_id)
    AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
    AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
    AND length(replace(resource_id, '-', '')) = 32
    AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  draft_id TEXT CHECK (
    draft_id IS NULL OR (
      length(draft_id) = 36 AND draft_id = lower(draft_id)
      AND substr(draft_id, 9, 1) = '-' AND substr(draft_id, 14, 1) = '-'
      AND substr(draft_id, 19, 1) = '-' AND substr(draft_id, 24, 1) = '-'
      AND length(replace(draft_id, '-', '')) = 32
      AND replace(draft_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  source_apply_id TEXT CHECK (
    source_apply_id IS NULL OR (
      length(source_apply_id) = 36 AND source_apply_id = lower(source_apply_id)
      AND substr(source_apply_id, 9, 1) = '-' AND substr(source_apply_id, 14, 1) = '-'
      AND substr(source_apply_id, 19, 1) = '-' AND substr(source_apply_id, 24, 1) = '-'
      AND length(replace(source_apply_id, '-', '')) = 32
      AND replace(source_apply_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  status TEXT NOT NULL CHECK (
    status IN ('preparing', 'stopping', 'applying', 'restarting', 'succeeded', 'failed', 'recovered')
  ),
  last_error_json TEXT CHECK (
    last_error_json IS NULL OR (json_valid(last_error_json) AND json_type(last_error_json) = 'object')
  ),
  backup_retained INTEGER NOT NULL CHECK (backup_retained IN (0, 1)),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  completed_at_ms INTEGER CHECK (completed_at_ms IS NULL OR completed_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id, draft_id)
    REFERENCES db_resource_drafts (org_id, resource_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id, source_apply_id)
    REFERENCES db_resource_apply_runs (org_id, resource_id, id) ON DELETE RESTRICT,
  CHECK (draft_id IS NULL OR source_apply_id IS NULL),
  CHECK (
    (status IN ('succeeded', 'failed', 'recovered') AND completed_at_ms IS NOT NULL)
    OR (status IN ('preparing', 'stopping', 'applying', 'restarting') AND completed_at_ms IS NULL)
  )
) STRICT;

CREATE INDEX db_resource_apply_runs_resource_idx
  ON db_resource_apply_runs (org_id, resource_id, status, created_at_ms);
CREATE INDEX db_resource_apply_runs_draft_idx
  ON db_resource_apply_runs (org_id, resource_id, draft_id);
CREATE INDEX db_resource_apply_runs_source_idx
  ON db_resource_apply_runs (org_id, resource_id, source_apply_id);
CREATE UNIQUE INDEX db_resource_apply_runs_one_active_idx
  ON db_resource_apply_runs (org_id, resource_id)
  WHERE status IN ('preparing', 'stopping', 'applying', 'restarting');

CREATE TABLE db_resource_backups (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  resource_id TEXT NOT NULL CHECK (
    length(resource_id) = 36 AND resource_id = lower(resource_id)
    AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
    AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
    AND length(replace(resource_id, '-', '')) = 32
    AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  apply_run_id TEXT NOT NULL CHECK (
    length(apply_run_id) = 36 AND apply_run_id = lower(apply_run_id)
    AND substr(apply_run_id, 9, 1) = '-' AND substr(apply_run_id, 14, 1) = '-'
    AND substr(apply_run_id, 19, 1) = '-' AND substr(apply_run_id, 24, 1) = '-'
    AND length(replace(apply_run_id, '-', '')) = 32
    AND replace(apply_run_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  relative_path TEXT NOT NULL CHECK (
    length(relative_path) BETWEEN 1 AND 1024
    AND relative_path = trim(relative_path)
    AND substr(relative_path, 1, 1) <> '/'
    AND relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(relative_path, '\') = 0
    AND relative_path <> '.' AND relative_path <> '..'
    AND relative_path NOT LIKE './%' AND relative_path NOT LIKE '../%'
    AND relative_path NOT LIKE '%/./%' AND relative_path NOT LIKE '%/../%'
    AND relative_path NOT LIKE '%/.' AND relative_path NOT LIKE '%/..'
    AND relative_path NOT LIKE '%//%'
  ),
  digest_sha256 TEXT NOT NULL CHECK (
    length(digest_sha256) = 64 AND digest_sha256 = lower(digest_sha256)
    AND digest_sha256 NOT GLOB '*[^0-9a-f]*'
  ),
  byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
  state TEXT NOT NULL CHECK (state IN ('retained', 'deleting', 'deleted')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  verified_at_ms INTEGER NOT NULL CHECK (verified_at_ms >= created_at_ms),
  delete_after_ms INTEGER CHECK (delete_after_ms IS NULL OR delete_after_ms >= verified_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id, apply_run_id),
  UNIQUE (org_id, relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id, apply_run_id)
    REFERENCES db_resource_apply_runs (org_id, resource_id, id) ON DELETE RESTRICT,
  CHECK ((state = 'retained' AND delete_after_ms IS NOT NULL) OR state <> 'retained')
) STRICT;

CREATE INDEX db_resource_backups_retention_idx
  ON db_resource_backups (org_id, state, delete_after_ms);

CREATE TABLE function_invocations (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  account_id TEXT NOT NULL CHECK (
    length(account_id) = 36 AND account_id = lower(account_id)
    AND substr(account_id, 9, 1) = '-' AND substr(account_id, 14, 1) = '-'
    AND substr(account_id, 19, 1) = '-' AND substr(account_id, 24, 1) = '-'
    AND length(replace(account_id, '-', '')) = 32
    AND replace(account_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  widget_definition_id TEXT NOT NULL CHECK (
    length(widget_definition_id) = 36 AND widget_definition_id = lower(widget_definition_id)
    AND substr(widget_definition_id, 9, 1) = '-' AND substr(widget_definition_id, 14, 1) = '-'
    AND substr(widget_definition_id, 19, 1) = '-' AND substr(widget_definition_id, 24, 1) = '-'
    AND length(replace(widget_definition_id, '-', '')) = 32
    AND replace(widget_definition_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  widget_revision_id TEXT NOT NULL CHECK (
    length(widget_revision_id) = 36 AND widget_revision_id = lower(widget_revision_id)
    AND substr(widget_revision_id, 9, 1) = '-' AND substr(widget_revision_id, 14, 1) = '-'
    AND substr(widget_revision_id, 19, 1) = '-' AND substr(widget_revision_id, 24, 1) = '-'
    AND length(replace(widget_revision_id, '-', '')) = 32
    AND replace(widget_revision_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  widget_instance_id TEXT NOT NULL CHECK (
    length(widget_instance_id) = 36 AND widget_instance_id = lower(widget_instance_id)
    AND substr(widget_instance_id, 9, 1) = '-' AND substr(widget_instance_id, 14, 1) = '-'
    AND substr(widget_instance_id, 19, 1) = '-' AND substr(widget_instance_id, 24, 1) = '-'
    AND length(replace(widget_instance_id, '-', '')) = 32
    AND replace(widget_instance_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  function_name TEXT NOT NULL CHECK (length(trim(function_name)) BETWEEN 1 AND 200),
  input_json TEXT NOT NULL CHECK (json_valid(input_json) AND json_type(input_json) = 'object'),
  input_digest_sha256 TEXT NOT NULL CHECK (
    length(input_digest_sha256) = 64 AND input_digest_sha256 = lower(input_digest_sha256)
    AND input_digest_sha256 NOT GLOB '*[^0-9a-f]*'
  ),
  policy_version INTEGER NOT NULL CHECK (policy_version >= 1),
  priority INTEGER NOT NULL CHECK (priority >= 0),
  status TEXT NOT NULL CHECK (
    status IN ('queued', 'claimed', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out')
  ),
  result_json TEXT CHECK (result_json IS NULL OR json_valid(result_json)),
  output_byte_size INTEGER NOT NULL CHECK (output_byte_size >= 0),
  log_byte_size INTEGER NOT NULL CHECK (log_byte_size >= 0),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  deadline_at_ms INTEGER NOT NULL CHECK (deadline_at_ms >= created_at_ms),
  started_at_ms INTEGER CHECK (started_at_ms IS NULL OR started_at_ms >= created_at_ms),
  finished_at_ms INTEGER CHECK (finished_at_ms IS NULL OR finished_at_ms >= started_at_ms),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, widget_definition_id, widget_revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, widget_definition_id, widget_revision_id, widget_instance_id)
    REFERENCES widget_instances (org_id, definition_id, revision_id, id) ON DELETE RESTRICT,
  CHECK (
    (status IN ('succeeded', 'failed', 'cancelled', 'timed_out') AND finished_at_ms IS NOT NULL)
    OR (status IN ('queued', 'claimed', 'running') AND finished_at_ms IS NULL)
  ),
  CHECK ((status IN ('queued', 'claimed') AND started_at_ms IS NULL) OR status NOT IN ('queued', 'claimed')),
  CHECK ((status IN ('running', 'succeeded', 'failed', 'cancelled', 'timed_out') AND started_at_ms IS NOT NULL)
    OR status IN ('queued', 'claimed'))
) STRICT;

CREATE INDEX function_invocations_queue_idx
  ON function_invocations (org_id, status, created_at_ms);
CREATE INDEX function_invocations_revision_idx
  ON function_invocations (org_id, widget_definition_id, widget_revision_id, created_at_ms);
CREATE INDEX function_invocations_account_idx
  ON function_invocations (org_id, account_id, created_at_ms);
CREATE INDEX function_invocations_instance_idx
  ON function_invocations (
    org_id, widget_definition_id, widget_revision_id, widget_instance_id
  );

CREATE TABLE function_attempts (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  invocation_id TEXT NOT NULL CHECK (
    length(invocation_id) = 36 AND invocation_id = lower(invocation_id)
    AND substr(invocation_id, 9, 1) = '-' AND substr(invocation_id, 14, 1) = '-'
    AND substr(invocation_id, 19, 1) = '-' AND substr(invocation_id, 24, 1) = '-'
    AND length(replace(invocation_id, '-', '')) = 32
    AND replace(invocation_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  attempt_number INTEGER NOT NULL CHECK (attempt_number >= 1),
  lease_epoch INTEGER NOT NULL CHECK (lease_epoch >= 1),
  status TEXT NOT NULL CHECK (
    status IN ('starting', 'running', 'succeeded', 'failed', 'cancelled', 'timed_out', 'lost')
  ),
  sandbox_driver TEXT NOT NULL CHECK (length(trim(sandbox_driver)) BETWEEN 1 AND 100),
  memory_tier TEXT NOT NULL CHECK (memory_tier IN ('small', 'medium', 'large')),
  active_wall_ms INTEGER NOT NULL CHECK (active_wall_ms >= 0),
  cpu_ms INTEGER NOT NULL CHECK (cpu_ms >= 0),
  allocated_memory_byte_ms INTEGER NOT NULL CHECK (allocated_memory_byte_ms >= 0),
  peak_rss_bytes INTEGER NOT NULL CHECK (peak_rss_bytes >= 0),
  disk_read_bytes INTEGER NOT NULL CHECK (disk_read_bytes >= 0),
  disk_write_bytes INTEGER NOT NULL CHECK (disk_write_bytes >= 0),
  network_rx_bytes INTEGER NOT NULL CHECK (network_rx_bytes >= 0),
  network_tx_bytes INTEGER NOT NULL CHECK (network_tx_bytes >= 0),
  cold_start INTEGER NOT NULL CHECK (cold_start IN (0, 1)),
  failure_owner TEXT CHECK (failure_owner IS NULL OR failure_owner IN ('user', 'platform', 'cancelled')),
  billable INTEGER NOT NULL CHECK (billable IN (0, 1)),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  started_at_ms INTEGER CHECK (started_at_ms IS NULL OR started_at_ms >= created_at_ms),
  finished_at_ms INTEGER CHECK (finished_at_ms IS NULL OR finished_at_ms >= started_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, invocation_id, id),
  UNIQUE (org_id, invocation_id, attempt_number),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id) REFERENCES function_invocations (org_id, id) ON DELETE RESTRICT,
  CHECK (
    (status IN ('succeeded', 'failed', 'cancelled', 'timed_out', 'lost') AND finished_at_ms IS NOT NULL)
    OR (status IN ('starting', 'running') AND finished_at_ms IS NULL)
  ),
  CHECK ((status = 'starting' AND started_at_ms IS NULL) OR (status <> 'starting' AND started_at_ms IS NOT NULL)),
  CHECK ((status = 'succeeded' AND failure_owner IS NULL) OR status <> 'succeeded'),
  CHECK ((status IN ('failed', 'cancelled', 'timed_out', 'lost') AND failure_owner IS NOT NULL)
    OR status NOT IN ('failed', 'cancelled', 'timed_out', 'lost'))
) STRICT;

CREATE INDEX function_attempts_invocation_idx
  ON function_attempts (org_id, invocation_id, attempt_number);

CREATE TABLE invocation_leases (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  invocation_id TEXT NOT NULL CHECK (
    length(invocation_id) = 36 AND invocation_id = lower(invocation_id)
    AND substr(invocation_id, 9, 1) = '-' AND substr(invocation_id, 14, 1) = '-'
    AND substr(invocation_id, 19, 1) = '-' AND substr(invocation_id, 24, 1) = '-'
    AND length(replace(invocation_id, '-', '')) = 32
    AND replace(invocation_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  attempt_id TEXT NOT NULL CHECK (
    length(attempt_id) = 36 AND attempt_id = lower(attempt_id)
    AND substr(attempt_id, 9, 1) = '-' AND substr(attempt_id, 14, 1) = '-'
    AND substr(attempt_id, 19, 1) = '-' AND substr(attempt_id, 24, 1) = '-'
    AND length(replace(attempt_id, '-', '')) = 32
    AND replace(attempt_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  lease_epoch INTEGER NOT NULL CHECK (lease_epoch >= 1),
  worker_id TEXT NOT NULL CHECK (length(trim(worker_id)) BETWEEN 1 AND 200),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  heartbeat_at_ms INTEGER NOT NULL CHECK (heartbeat_at_ms >= created_at_ms),
  expires_at_ms INTEGER NOT NULL CHECK (expires_at_ms > heartbeat_at_ms),
  PRIMARY KEY (org_id, invocation_id),
  UNIQUE (org_id, invocation_id, lease_epoch),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id) REFERENCES function_invocations (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, invocation_id, attempt_id)
    REFERENCES function_attempts (org_id, invocation_id, id) ON DELETE CASCADE
) STRICT;

CREATE INDEX invocation_leases_expiry_idx ON invocation_leases (expires_at_ms, org_id);
CREATE INDEX invocation_leases_attempt_idx
  ON invocation_leases (org_id, invocation_id, attempt_id);

CREATE TABLE idempotency_records (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  scope_kind TEXT NOT NULL CHECK (scope_kind IN ('organization', 'canvas', 'widget_instance')),
  canvas_id TEXT CHECK (
    canvas_id IS NULL OR (
      length(canvas_id) = 36 AND canvas_id = lower(canvas_id)
      AND substr(canvas_id, 9, 1) = '-' AND substr(canvas_id, 14, 1) = '-'
      AND substr(canvas_id, 19, 1) = '-' AND substr(canvas_id, 24, 1) = '-'
      AND length(replace(canvas_id, '-', '')) = 32
      AND replace(canvas_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  widget_instance_id TEXT CHECK (
    widget_instance_id IS NULL OR (
      length(widget_instance_id) = 36 AND widget_instance_id = lower(widget_instance_id)
      AND substr(widget_instance_id, 9, 1) = '-' AND substr(widget_instance_id, 14, 1) = '-'
      AND substr(widget_instance_id, 19, 1) = '-' AND substr(widget_instance_id, 24, 1) = '-'
      AND length(replace(widget_instance_id, '-', '')) = 32
      AND replace(widget_instance_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  idempotency_key TEXT NOT NULL CHECK (length(trim(idempotency_key)) BETWEEN 1 AND 300),
  request_fingerprint_sha256 TEXT NOT NULL CHECK (
    length(request_fingerprint_sha256) = 64
    AND request_fingerprint_sha256 = lower(request_fingerprint_sha256)
    AND request_fingerprint_sha256 NOT GLOB '*[^0-9a-f]*'
  ),
  widget_definition_id TEXT NOT NULL CHECK (
    length(widget_definition_id) = 36 AND widget_definition_id = lower(widget_definition_id)
    AND substr(widget_definition_id, 9, 1) = '-' AND substr(widget_definition_id, 14, 1) = '-'
    AND substr(widget_definition_id, 19, 1) = '-' AND substr(widget_definition_id, 24, 1) = '-'
    AND length(replace(widget_definition_id, '-', '')) = 32
    AND replace(widget_definition_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  widget_revision_id TEXT NOT NULL CHECK (
    length(widget_revision_id) = 36 AND widget_revision_id = lower(widget_revision_id)
    AND substr(widget_revision_id, 9, 1) = '-' AND substr(widget_revision_id, 14, 1) = '-'
    AND substr(widget_revision_id, 19, 1) = '-' AND substr(widget_revision_id, 24, 1) = '-'
    AND length(replace(widget_revision_id, '-', '')) = 32
    AND replace(widget_revision_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  invocation_id TEXT NOT NULL CHECK (
    length(invocation_id) = 36 AND invocation_id = lower(invocation_id)
    AND substr(invocation_id, 9, 1) = '-' AND substr(invocation_id, 14, 1) = '-'
    AND substr(invocation_id, 19, 1) = '-' AND substr(invocation_id, 24, 1) = '-'
    AND length(replace(invocation_id, '-', '')) = 32
    AND replace(invocation_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  expires_at_ms INTEGER CHECK (expires_at_ms IS NULL OR expires_at_ms > created_at_ms),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, widget_instance_id) REFERENCES widget_instances (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, widget_definition_id, widget_revision_id)
    REFERENCES widget_definition_revisions (org_id, definition_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id) REFERENCES function_invocations (org_id, id) ON DELETE RESTRICT,
  CHECK (
    (scope_kind = 'organization' AND canvas_id IS NULL AND widget_instance_id IS NULL)
    OR (scope_kind = 'canvas' AND canvas_id IS NOT NULL AND widget_instance_id IS NULL)
    OR (scope_kind = 'widget_instance' AND canvas_id IS NULL AND widget_instance_id IS NOT NULL)
  )
) STRICT;

CREATE UNIQUE INDEX idempotency_records_org_key_idx
  ON idempotency_records (org_id, idempotency_key)
  WHERE scope_kind = 'organization';
CREATE UNIQUE INDEX idempotency_records_canvas_key_idx
  ON idempotency_records (org_id, canvas_id, idempotency_key)
  WHERE scope_kind = 'canvas';
CREATE UNIQUE INDEX idempotency_records_widget_key_idx
  ON idempotency_records (org_id, widget_instance_id, idempotency_key)
  WHERE scope_kind = 'widget_instance';
CREATE INDEX idempotency_records_expiry_idx
  ON idempotency_records (org_id, expires_at_ms);
CREATE INDEX idempotency_records_revision_idx
  ON idempotency_records (org_id, widget_definition_id, widget_revision_id);
CREATE INDEX idempotency_records_invocation_idx
  ON idempotency_records (org_id, invocation_id);

CREATE TABLE resource_write_permits (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  resource_id TEXT NOT NULL CHECK (
    length(resource_id) = 36 AND resource_id = lower(resource_id)
    AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
    AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
    AND length(replace(resource_id, '-', '')) = 32
    AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  invocation_id TEXT NOT NULL CHECK (
    length(invocation_id) = 36 AND invocation_id = lower(invocation_id)
    AND substr(invocation_id, 9, 1) = '-' AND substr(invocation_id, 14, 1) = '-'
    AND substr(invocation_id, 19, 1) = '-' AND substr(invocation_id, 24, 1) = '-'
    AND length(replace(invocation_id, '-', '')) = 32
    AND replace(invocation_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  attempt_id TEXT NOT NULL CHECK (
    length(attempt_id) = 36 AND attempt_id = lower(attempt_id)
    AND substr(attempt_id, 9, 1) = '-' AND substr(attempt_id, 14, 1) = '-'
    AND substr(attempt_id, 19, 1) = '-' AND substr(attempt_id, 24, 1) = '-'
    AND length(replace(attempt_id, '-', '')) = 32
    AND replace(attempt_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  lease_epoch INTEGER NOT NULL CHECK (lease_epoch >= 1),
  operation_name TEXT NOT NULL CHECK (length(trim(operation_name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('active', 'consumed', 'revoked', 'expired')),
  issued_at_ms INTEGER NOT NULL CHECK (issued_at_ms >= 0),
  expires_at_ms INTEGER NOT NULL CHECK (expires_at_ms > issued_at_ms),
  consumed_at_ms INTEGER CHECK (consumed_at_ms IS NULL OR consumed_at_ms BETWEEN issued_at_ms AND expires_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, resource_id, id),
  UNIQUE (org_id, resource_id, invocation_id, attempt_id, operation_name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id) REFERENCES function_invocations (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, invocation_id, attempt_id)
    REFERENCES function_attempts (org_id, invocation_id, id) ON DELETE RESTRICT,
  CHECK ((status = 'consumed' AND consumed_at_ms IS NOT NULL) OR (status <> 'consumed' AND consumed_at_ms IS NULL))
) STRICT;

CREATE INDEX resource_write_permits_expiry_idx
  ON resource_write_permits (org_id, status, expires_at_ms);
CREATE INDEX resource_write_permits_attempt_idx
  ON resource_write_permits (org_id, invocation_id, attempt_id);

CREATE TABLE usage_outbox (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  account_id TEXT NOT NULL CHECK (
    length(account_id) = 36 AND account_id = lower(account_id)
    AND substr(account_id, 9, 1) = '-' AND substr(account_id, 14, 1) = '-'
    AND substr(account_id, 19, 1) = '-' AND substr(account_id, 24, 1) = '-'
    AND length(replace(account_id, '-', '')) = 32
    AND replace(account_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  attempt_id TEXT CHECK (
    attempt_id IS NULL OR (
      length(attempt_id) = 36 AND attempt_id = lower(attempt_id)
      AND substr(attempt_id, 9, 1) = '-' AND substr(attempt_id, 14, 1) = '-'
      AND substr(attempt_id, 19, 1) = '-' AND substr(attempt_id, 24, 1) = '-'
      AND length(replace(attempt_id, '-', '')) = 32
      AND replace(attempt_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  resource_id TEXT CHECK (
    resource_id IS NULL OR (
      length(resource_id) = 36 AND resource_id = lower(resource_id)
      AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
      AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
      AND length(replace(resource_id, '-', '')) = 32
      AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  resource_permit_id TEXT CHECK (
    resource_permit_id IS NULL OR (
      length(resource_permit_id) = 36 AND resource_permit_id = lower(resource_permit_id)
      AND substr(resource_permit_id, 9, 1) = '-' AND substr(resource_permit_id, 14, 1) = '-'
      AND substr(resource_permit_id, 19, 1) = '-' AND substr(resource_permit_id, 24, 1) = '-'
      AND length(replace(resource_permit_id, '-', '')) = 32
      AND replace(resource_permit_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  state TEXT NOT NULL CHECK (state IN ('pending', 'importing', 'imported', 'error')),
  outcome TEXT NOT NULL CHECK (outcome IN ('succeeded', 'failed', 'cancelled', 'timed_out', 'lost')),
  failure_owner TEXT CHECK (failure_owner IS NULL OR failure_owner IN ('user', 'platform', 'cancelled')),
  billable INTEGER NOT NULL CHECK (billable IN (0, 1)),
  policy_version INTEGER NOT NULL CHECK (policy_version >= 1),
  active_wall_ms INTEGER NOT NULL CHECK (active_wall_ms >= 0),
  cpu_ms INTEGER NOT NULL CHECK (cpu_ms >= 0),
  allocated_memory_byte_ms INTEGER NOT NULL CHECK (allocated_memory_byte_ms >= 0),
  peak_rss_bytes INTEGER NOT NULL CHECK (peak_rss_bytes >= 0),
  disk_read_bytes INTEGER NOT NULL CHECK (disk_read_bytes >= 0),
  disk_write_bytes INTEGER NOT NULL CHECK (disk_write_bytes >= 0),
  network_rx_bytes INTEGER NOT NULL CHECK (network_rx_bytes >= 0),
  network_tx_bytes INTEGER NOT NULL CHECK (network_tx_bytes >= 0),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  imported_at_ms INTEGER CHECK (imported_at_ms IS NULL OR imported_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, attempt_id) REFERENCES function_attempts (org_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, resource_id, resource_permit_id)
    REFERENCES resource_write_permits (org_id, resource_id, id) ON DELETE RESTRICT,
  CHECK (
    (attempt_id IS NOT NULL AND resource_id IS NULL AND resource_permit_id IS NULL)
    OR (attempt_id IS NULL AND resource_id IS NOT NULL AND resource_permit_id IS NOT NULL)
  ),
  CHECK ((state = 'imported' AND imported_at_ms IS NOT NULL) OR (state <> 'imported' AND imported_at_ms IS NULL)),
  CHECK ((outcome = 'succeeded' AND failure_owner IS NULL) OR outcome <> 'succeeded'),
  CHECK ((outcome <> 'succeeded' AND failure_owner IS NOT NULL) OR outcome = 'succeeded')
) STRICT;

CREATE UNIQUE INDEX usage_outbox_attempt_receipt_idx
  ON usage_outbox (org_id, attempt_id) WHERE attempt_id IS NOT NULL;
CREATE UNIQUE INDEX usage_outbox_resource_receipt_idx
  ON usage_outbox (org_id, resource_permit_id) WHERE resource_permit_id IS NOT NULL;
CREATE INDEX usage_outbox_import_idx ON usage_outbox (org_id, state, created_at_ms);
CREATE INDEX usage_outbox_account_idx ON usage_outbox (org_id, account_id, created_at_ms);
CREATE INDEX usage_outbox_resource_permit_idx
  ON usage_outbox (org_id, resource_id, resource_permit_id);

CREATE TABLE media_files (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  canvas_id TEXT CHECK (
    canvas_id IS NULL OR (
      length(canvas_id) = 36 AND canvas_id = lower(canvas_id)
      AND substr(canvas_id, 9, 1) = '-' AND substr(canvas_id, 14, 1) = '-'
      AND substr(canvas_id, 19, 1) = '-' AND substr(canvas_id, 24, 1) = '-'
      AND length(replace(canvas_id, '-', '')) = 32
      AND replace(canvas_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  source_hash TEXT NOT NULL CHECK (
    length(source_hash) BETWEEN 1 AND 200 AND source_hash = trim(source_hash)
  ),
  digest_sha256 TEXT CHECK (
    digest_sha256 IS NULL OR (
      length(digest_sha256) = 64 AND digest_sha256 = lower(digest_sha256)
      AND digest_sha256 NOT GLOB '*[^0-9a-f]*'
    )
  ),
  mime_type TEXT NOT NULL CHECK (
    length(mime_type) BETWEEN 3 AND 200
    AND mime_type = lower(trim(mime_type))
    AND instr(mime_type, '/') > 1
  ),
  byte_size INTEGER NOT NULL CHECK (byte_size >= 0),
  data BLOB NOT NULL CHECK (length(data) = byte_size),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE INDEX media_files_canvas_idx ON media_files (org_id, canvas_id, created_at_ms);
CREATE INDEX media_files_source_hash_idx ON media_files (org_id, source_hash);
CREATE INDEX media_files_digest_idx ON media_files (org_id, digest_sha256);

CREATE TABLE file_systems (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  slug TEXT NOT NULL CHECK (
    length(slug) BETWEEN 1 AND 100 AND slug = lower(trim(slug))
    AND substr(slug, 1, 1) <> '-' AND substr(slug, -1, 1) <> '-'
    AND instr(slug, '--') = 0 AND slug NOT GLOB '*[^a-z0-9-]*'
  ),
  capability_ref TEXT NOT NULL CHECK (length(trim(capability_ref)) BETWEEN 1 AND 300),
  relative_root TEXT NOT NULL CHECK (
    length(relative_root) BETWEEN 1 AND 1024
    AND relative_root = trim(relative_root)
    AND substr(relative_root, 1, 1) <> '/'
    AND relative_root NOT GLOB '[A-Za-z]:*'
    AND instr(relative_root, '\') = 0
    AND relative_root <> '.' AND relative_root <> '..'
    AND relative_root NOT LIKE './%' AND relative_root NOT LIKE '../%'
    AND relative_root NOT LIKE '%/./%' AND relative_root NOT LIKE '%/../%'
    AND relative_root NOT LIKE '%/.' AND relative_root NOT LIKE '%/..'
    AND relative_root NOT LIKE '%//%'
  ),
  description TEXT CHECK (description IS NULL OR length(description) <= 2000),
  status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, name),
  UNIQUE (org_id, slug),
  UNIQUE (org_id, capability_ref),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE RESTRICT
) STRICT;

CREATE TABLE tool_groups (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  configuration_json TEXT CHECK (
    configuration_json IS NULL
    OR (json_valid(configuration_json) AND json_type(configuration_json) = 'object')
  ),
  status TEXT NOT NULL CHECK (status IN ('active', 'disabled')),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE
) STRICT;

CREATE TABLE pty_session_metadata (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  account_id TEXT NOT NULL CHECK (
    length(account_id) = 36 AND account_id = lower(account_id)
    AND substr(account_id, 9, 1) = '-' AND substr(account_id, 14, 1) = '-'
    AND substr(account_id, 19, 1) = '-' AND substr(account_id, 24, 1) = '-'
    AND length(replace(account_id, '-', '')) = 32
    AND replace(account_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  file_system_id TEXT NOT NULL CHECK (
    length(file_system_id) = 36 AND file_system_id = lower(file_system_id)
    AND substr(file_system_id, 9, 1) = '-' AND substr(file_system_id, 14, 1) = '-'
    AND substr(file_system_id, 19, 1) = '-' AND substr(file_system_id, 24, 1) = '-'
    AND length(replace(file_system_id, '-', '')) = 32
    AND replace(file_system_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  cwd_relative_path TEXT NOT NULL CHECK (
    length(cwd_relative_path) BETWEEN 1 AND 1024
    AND cwd_relative_path = trim(cwd_relative_path)
    AND substr(cwd_relative_path, 1, 1) <> '/'
    AND cwd_relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(cwd_relative_path, '\') = 0
    AND cwd_relative_path <> '.' AND cwd_relative_path <> '..'
    AND cwd_relative_path NOT LIKE './%' AND cwd_relative_path NOT LIKE '../%'
    AND cwd_relative_path NOT LIKE '%/./%' AND cwd_relative_path NOT LIKE '%/../%'
    AND cwd_relative_path NOT LIKE '%/.' AND cwd_relative_path NOT LIKE '%/..'
    AND cwd_relative_path NOT LIKE '%//%'
  ),
  status TEXT NOT NULL CHECK (status IN ('opening', 'running', 'exited', 'failed', 'closed')),
  exit_code INTEGER,
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  closed_at_ms INTEGER CHECK (closed_at_ms IS NULL OR closed_at_ms >= created_at_ms),
  retain_until_ms INTEGER CHECK (retain_until_ms IS NULL OR retain_until_ms >= closed_at_ms),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, file_system_id) REFERENCES file_systems (org_id, id) ON DELETE RESTRICT,
  CHECK (
    (status IN ('exited', 'failed', 'closed') AND closed_at_ms IS NOT NULL)
    OR (status IN ('opening', 'running') AND closed_at_ms IS NULL)
  ),
  CHECK ((status = 'exited' AND exit_code IS NOT NULL) OR (status <> 'exited' AND exit_code IS NULL))
) STRICT;

CREATE INDEX pty_session_metadata_retention_idx
  ON pty_session_metadata (org_id, status, retain_until_ms);
CREATE INDEX pty_session_metadata_account_idx
  ON pty_session_metadata (org_id, account_id, created_at_ms);
CREATE INDEX pty_session_metadata_filesystem_idx
  ON pty_session_metadata (org_id, file_system_id);

CREATE TABLE agent_chats (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  account_id TEXT NOT NULL CHECK (
    length(account_id) = 36 AND account_id = lower(account_id)
    AND substr(account_id, 9, 1) = '-' AND substr(account_id, 14, 1) = '-'
    AND substr(account_id, 19, 1) = '-' AND substr(account_id, 24, 1) = '-'
    AND length(replace(account_id, '-', '')) = 32
    AND replace(account_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  canvas_id TEXT CHECK (
    canvas_id IS NULL OR (
      length(canvas_id) = 36 AND canvas_id = lower(canvas_id)
      AND substr(canvas_id, 9, 1) = '-' AND substr(canvas_id, 14, 1) = '-'
      AND substr(canvas_id, 19, 1) = '-' AND substr(canvas_id, 24, 1) = '-'
      AND length(replace(canvas_id, '-', '')) = 32
      AND replace(canvas_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (status IN ('active', 'archived', 'error')),
  workspace_relative_path TEXT NOT NULL CHECK (
    length(workspace_relative_path) BETWEEN 1 AND 1024
    AND workspace_relative_path = trim(workspace_relative_path)
    AND substr(workspace_relative_path, 1, 1) <> '/'
    AND workspace_relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(workspace_relative_path, '\') = 0
    AND workspace_relative_path <> '.' AND workspace_relative_path <> '..'
    AND workspace_relative_path NOT LIKE './%' AND workspace_relative_path NOT LIKE '../%'
    AND workspace_relative_path NOT LIKE '%/./%' AND workspace_relative_path NOT LIKE '%/../%'
    AND workspace_relative_path NOT LIKE '%/.' AND workspace_relative_path NOT LIKE '%/..'
    AND workspace_relative_path NOT LIKE '%//%'
  ),
  history_relative_path TEXT NOT NULL CHECK (
    length(history_relative_path) BETWEEN 1 AND 1024
    AND history_relative_path = trim(history_relative_path)
    AND substr(history_relative_path, 1, 1) <> '/'
    AND history_relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(history_relative_path, '\') = 0
    AND history_relative_path <> '.' AND history_relative_path <> '..'
    AND history_relative_path NOT LIKE './%' AND history_relative_path NOT LIKE '../%'
    AND history_relative_path NOT LIKE '%/./%' AND history_relative_path NOT LIKE '%/../%'
    AND history_relative_path NOT LIKE '%/.' AND history_relative_path NOT LIKE '%/..'
    AND history_relative_path NOT LIKE '%//%'
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, workspace_relative_path),
  UNIQUE (org_id, history_relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, account_id)
    REFERENCES organization_memberships (org_id, account_id) ON DELETE RESTRICT,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE RESTRICT
) STRICT;

CREATE INDEX agent_chats_account_idx ON agent_chats (org_id, account_id, created_at_ms);
CREATE INDEX agent_chats_canvas_idx ON agent_chats (org_id, canvas_id, created_at_ms);

CREATE TABLE agent_drafts (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  chat_id TEXT NOT NULL CHECK (
    length(chat_id) = 36 AND chat_id = lower(chat_id)
    AND substr(chat_id, 9, 1) = '-' AND substr(chat_id, 14, 1) = '-'
    AND substr(chat_id, 19, 1) = '-' AND substr(chat_id, 24, 1) = '-'
    AND length(replace(chat_id, '-', '')) = 32
    AND replace(chat_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (
    status IN ('editing', 'validating', 'ready', 'published', 'error', 'discarded')
  ),
  source_relative_path TEXT NOT NULL CHECK (
    length(source_relative_path) BETWEEN 1 AND 1024
    AND source_relative_path = trim(source_relative_path)
    AND substr(source_relative_path, 1, 1) <> '/'
    AND source_relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(source_relative_path, '\') = 0
    AND source_relative_path <> '.' AND source_relative_path <> '..'
    AND source_relative_path NOT LIKE './%' AND source_relative_path NOT LIKE '../%'
    AND source_relative_path NOT LIKE '%/./%' AND source_relative_path NOT LIKE '%/../%'
    AND source_relative_path NOT LIKE '%/.' AND source_relative_path NOT LIKE '%/..'
    AND source_relative_path NOT LIKE '%//%'
  ),
  source_digest_sha256 TEXT CHECK (
    source_digest_sha256 IS NULL OR (
      length(source_digest_sha256) = 64 AND source_digest_sha256 = lower(source_digest_sha256)
      AND source_digest_sha256 NOT GLOB '*[^0-9a-f]*'
    )
  ),
  last_error_json TEXT CHECK (
    last_error_json IS NULL OR (json_valid(last_error_json) AND json_type(last_error_json) = 'object')
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, chat_id, source_relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, chat_id) REFERENCES agent_chats (org_id, id) ON DELETE CASCADE
) STRICT;

CREATE INDEX agent_drafts_chat_idx ON agent_drafts (org_id, chat_id, created_at_ms);

CREATE TABLE agent_previews (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  draft_id TEXT NOT NULL CHECK (
    length(draft_id) = 36 AND draft_id = lower(draft_id)
    AND substr(draft_id, 9, 1) = '-' AND substr(draft_id, 14, 1) = '-'
    AND substr(draft_id, 19, 1) = '-' AND substr(draft_id, 24, 1) = '-'
    AND length(replace(draft_id, '-', '')) = 32
    AND replace(draft_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  artifact_id TEXT CHECK (
    artifact_id IS NULL OR (
      length(artifact_id) = 36 AND artifact_id = lower(artifact_id)
      AND substr(artifact_id, 9, 1) = '-' AND substr(artifact_id, 14, 1) = '-'
      AND substr(artifact_id, 19, 1) = '-' AND substr(artifact_id, 24, 1) = '-'
      AND length(replace(artifact_id, '-', '')) = 32
      AND replace(artifact_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  artifact_kind TEXT CHECK (
    (artifact_id IS NULL AND artifact_kind IS NULL)
    OR (artifact_id IS NOT NULL AND artifact_kind = 'ui')
  ),
  relative_path TEXT NOT NULL CHECK (
    length(relative_path) BETWEEN 1 AND 1024
    AND relative_path = trim(relative_path)
    AND substr(relative_path, 1, 1) <> '/'
    AND relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(relative_path, '\') = 0
    AND relative_path <> '.' AND relative_path <> '..'
    AND relative_path NOT LIKE './%' AND relative_path NOT LIKE '../%'
    AND relative_path NOT LIKE '%/./%' AND relative_path NOT LIKE '%/../%'
    AND relative_path NOT LIKE '%/.' AND relative_path NOT LIKE '%/..'
    AND relative_path NOT LIKE '%//%'
  ),
  status TEXT NOT NULL CHECK (status IN ('queued', 'building', 'ready', 'failed', 'stopped')),
  last_error_json TEXT CHECK (
    last_error_json IS NULL OR (json_valid(last_error_json) AND json_type(last_error_json) = 'object')
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  expires_at_ms INTEGER NOT NULL CHECK (expires_at_ms > created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, relative_path),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, draft_id) REFERENCES agent_drafts (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, artifact_id, artifact_kind)
    REFERENCES artifact_references (org_id, id, kind) ON DELETE RESTRICT,
  CHECK ((status = 'ready' AND artifact_id IS NOT NULL) OR status <> 'ready')
) STRICT;

CREATE INDEX agent_previews_draft_idx ON agent_previews (org_id, draft_id, created_at_ms);
CREATE INDEX agent_previews_expiry_idx ON agent_previews (org_id, status, expires_at_ms);
CREATE INDEX agent_previews_artifact_idx
  ON agent_previews (org_id, artifact_id, artifact_kind);

CREATE TABLE legacy_actor_definitions (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  name TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 200),
  slug TEXT NOT NULL CHECK (
    length(slug) BETWEEN 1 AND 100 AND slug = lower(trim(slug))
    AND substr(slug, 1, 1) <> '-' AND substr(slug, -1, 1) <> '-'
    AND instr(slug, '--') = 0 AND slug NOT GLOB '*[^a-z0-9-]*'
  ),
  url TEXT CHECK (url IS NULL OR length(trim(url)) BETWEEN 1 AND 1000),
  description TEXT CHECK (description IS NULL OR length(description) <= 4000),
  manifest_relative_path TEXT NOT NULL CHECK (
    length(manifest_relative_path) BETWEEN 1 AND 1024
    AND manifest_relative_path = trim(manifest_relative_path)
    AND substr(manifest_relative_path, 1, 1) <> '/'
    AND manifest_relative_path NOT GLOB '[A-Za-z]:*'
    AND instr(manifest_relative_path, '\') = 0
    AND manifest_relative_path <> '.' AND manifest_relative_path <> '..'
    AND manifest_relative_path NOT LIKE './%' AND manifest_relative_path NOT LIKE '../%'
    AND manifest_relative_path NOT LIKE '%/./%' AND manifest_relative_path NOT LIKE '%/../%'
    AND manifest_relative_path NOT LIKE '%/.' AND manifest_relative_path NOT LIKE '%/..'
    AND manifest_relative_path NOT LIKE '%//%'
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, name),
  UNIQUE (org_id, slug),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE
) STRICT;

CREATE TABLE legacy_actor_instances (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  canvas_id TEXT NOT NULL CHECK (
    length(canvas_id) = 36 AND canvas_id = lower(canvas_id)
    AND substr(canvas_id, 9, 1) = '-' AND substr(canvas_id, 14, 1) = '-'
    AND substr(canvas_id, 19, 1) = '-' AND substr(canvas_id, 24, 1) = '-'
    AND length(replace(canvas_id, '-', '')) = 32
    AND replace(canvas_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  element_id TEXT NOT NULL CHECK (length(trim(element_id)) BETWEEN 1 AND 200),
  actor_definition_name TEXT NOT NULL CHECK (length(trim(actor_definition_name)) BETWEEN 1 AND 200),
  file_system_id TEXT CHECK (
    file_system_id IS NULL OR (
      length(file_system_id) = 36 AND file_system_id = lower(file_system_id)
      AND substr(file_system_id, 9, 1) = '-' AND substr(file_system_id, 14, 1) = '-'
      AND substr(file_system_id, 19, 1) = '-' AND substr(file_system_id, 24, 1) = '-'
      AND length(replace(file_system_id, '-', '')) = 32
      AND replace(file_system_id, '-', '') NOT GLOB '*[^0-9a-f]*'
    )
  ),
  display_name TEXT NOT NULL CHECK (length(trim(display_name)) BETWEEN 1 AND 200),
  status TEXT NOT NULL CHECK (
    status IN ('created', 'starting', 'running', 'paused', 'stopping', 'stopped', 'error', 'blocked')
  ),
  machine_state TEXT NOT NULL CHECK (length(trim(machine_state)) BETWEEN 1 AND 200),
  machine_context_json TEXT NOT NULL CHECK (
    json_valid(machine_context_json) AND json_type(machine_context_json) = 'object'
  ),
  last_error_json TEXT CHECK (
    last_error_json IS NULL OR (json_valid(last_error_json) AND json_type(last_error_json) = 'object')
  ),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, id),
  UNIQUE (org_id, canvas_id, id),
  UNIQUE (org_id, id, actor_definition_name),
  UNIQUE (org_id, canvas_id, element_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, actor_definition_name)
    REFERENCES legacy_actor_definitions (org_id, name) ON DELETE CASCADE,
  FOREIGN KEY (org_id, file_system_id) REFERENCES file_systems (org_id, id) ON DELETE RESTRICT
) STRICT;

CREATE INDEX legacy_actor_instances_definition_idx
  ON legacy_actor_instances (org_id, actor_definition_name, status);
CREATE INDEX legacy_actor_instances_filesystem_idx
  ON legacy_actor_instances (org_id, file_system_id);

CREATE TABLE legacy_actor_connections (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  id TEXT NOT NULL CHECK (
    length(id) = 36 AND id = lower(id)
    AND substr(id, 9, 1) = '-' AND substr(id, 14, 1) = '-'
    AND substr(id, 19, 1) = '-' AND substr(id, 24, 1) = '-'
    AND length(replace(id, '-', '')) = 32
    AND replace(id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  canvas_id TEXT NOT NULL CHECK (
    length(canvas_id) = 36 AND canvas_id = lower(canvas_id)
    AND substr(canvas_id, 9, 1) = '-' AND substr(canvas_id, 14, 1) = '-'
    AND substr(canvas_id, 19, 1) = '-' AND substr(canvas_id, 24, 1) = '-'
    AND length(replace(canvas_id, '-', '')) = 32
    AND replace(canvas_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  source_actor_instance_id TEXT NOT NULL CHECK (
    length(source_actor_instance_id) = 36 AND source_actor_instance_id = lower(source_actor_instance_id)
    AND substr(source_actor_instance_id, 9, 1) = '-' AND substr(source_actor_instance_id, 14, 1) = '-'
    AND substr(source_actor_instance_id, 19, 1) = '-' AND substr(source_actor_instance_id, 24, 1) = '-'
    AND length(replace(source_actor_instance_id, '-', '')) = 32
    AND replace(source_actor_instance_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  target_actor_instance_id TEXT NOT NULL CHECK (
    length(target_actor_instance_id) = 36 AND target_actor_instance_id = lower(target_actor_instance_id)
    AND substr(target_actor_instance_id, 9, 1) = '-' AND substr(target_actor_instance_id, 14, 1) = '-'
    AND substr(target_actor_instance_id, 19, 1) = '-' AND substr(target_actor_instance_id, 24, 1) = '-'
    AND length(replace(target_actor_instance_id, '-', '')) = 32
    AND replace(target_actor_instance_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  enabled INTEGER NOT NULL CHECK (enabled IN (0, 1)),
  label TEXT CHECK (label IS NULL OR length(label) <= 200),
  message_name_whitelist_json TEXT CHECK (
    message_name_whitelist_json IS NULL
    OR (json_valid(message_name_whitelist_json) AND json_type(message_name_whitelist_json) = 'array')
  ),
  style_json TEXT NOT NULL CHECK (json_valid(style_json) AND json_type(style_json) = 'object'),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  PRIMARY KEY (org_id, id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, canvas_id) REFERENCES canvases (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, canvas_id, source_actor_instance_id)
    REFERENCES legacy_actor_instances (org_id, canvas_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, canvas_id, target_actor_instance_id)
    REFERENCES legacy_actor_instances (org_id, canvas_id, id) ON DELETE CASCADE,
  CHECK (source_actor_instance_id <> target_actor_instance_id)
) STRICT;

CREATE INDEX legacy_actor_connections_source_idx
  ON legacy_actor_connections (org_id, source_actor_instance_id);
CREATE INDEX legacy_actor_connections_target_idx
  ON legacy_actor_connections (org_id, target_actor_instance_id);
CREATE INDEX legacy_actor_connections_source_fk_idx
  ON legacy_actor_connections (org_id, canvas_id, source_actor_instance_id);
CREATE INDEX legacy_actor_connections_target_fk_idx
  ON legacy_actor_connections (org_id, canvas_id, target_actor_instance_id);

CREATE TABLE legacy_actor_resource_bindings (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  definition_name TEXT NOT NULL CHECK (length(trim(definition_name)) BETWEEN 1 AND 200),
  slot_name TEXT NOT NULL CHECK (length(trim(slot_name)) BETWEEN 1 AND 200),
  resource_id TEXT NOT NULL CHECK (
    length(resource_id) = 36 AND resource_id = lower(resource_id)
    AND substr(resource_id, 9, 1) = '-' AND substr(resource_id, 14, 1) = '-'
    AND substr(resource_id, 19, 1) = '-' AND substr(resource_id, 24, 1) = '-'
    AND length(replace(resource_id, '-', '')) = 32
    AND replace(resource_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  allow_read INTEGER NOT NULL CHECK (allow_read IN (0, 1)),
  allow_write INTEGER NOT NULL CHECK (allow_write IN (0, 1)),
  created_at_ms INTEGER NOT NULL CHECK (created_at_ms >= 0),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= created_at_ms),
  PRIMARY KEY (org_id, definition_name, slot_name),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, definition_name)
    REFERENCES legacy_actor_definitions (org_id, name) ON DELETE CASCADE,
  FOREIGN KEY (org_id, resource_id) REFERENCES resource_catalog (org_id, id) ON DELETE RESTRICT,
  CHECK (allow_read = 1 OR allow_write = 1)
) STRICT;

CREATE INDEX legacy_actor_resource_bindings_resource_idx
  ON legacy_actor_resource_bindings (org_id, resource_id);

CREATE TABLE legacy_actor_apply_results (
  org_id TEXT NOT NULL CHECK (
    length(org_id) = 36 AND org_id = lower(org_id)
    AND substr(org_id, 9, 1) = '-' AND substr(org_id, 14, 1) = '-'
    AND substr(org_id, 19, 1) = '-' AND substr(org_id, 24, 1) = '-'
    AND length(replace(org_id, '-', '')) = 32
    AND replace(org_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  apply_id TEXT NOT NULL CHECK (
    length(apply_id) = 36 AND apply_id = lower(apply_id)
    AND substr(apply_id, 9, 1) = '-' AND substr(apply_id, 14, 1) = '-'
    AND substr(apply_id, 19, 1) = '-' AND substr(apply_id, 24, 1) = '-'
    AND length(replace(apply_id, '-', '')) = 32
    AND replace(apply_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  actor_instance_id TEXT NOT NULL CHECK (
    length(actor_instance_id) = 36 AND actor_instance_id = lower(actor_instance_id)
    AND substr(actor_instance_id, 9, 1) = '-' AND substr(actor_instance_id, 14, 1) = '-'
    AND substr(actor_instance_id, 19, 1) = '-' AND substr(actor_instance_id, 24, 1) = '-'
    AND length(replace(actor_instance_id, '-', '')) = 32
    AND replace(actor_instance_id, '-', '') NOT GLOB '*[^0-9a-f]*'
  ),
  actor_definition_name TEXT NOT NULL CHECK (length(trim(actor_definition_name)) BETWEEN 1 AND 200),
  was_running INTEGER NOT NULL CHECK (was_running IN (0, 1)),
  status TEXT NOT NULL CHECK (
    status IN (
      'notRunning', 'pendingStop', 'stopped', 'stopFailed',
      'pendingRestart', 'restarted', 'startFailed', 'crashed'
    )
  ),
  error_json TEXT CHECK (
    error_json IS NULL OR (json_valid(error_json) AND json_type(error_json) = 'object')
  ),
  updated_at_ms INTEGER NOT NULL CHECK (updated_at_ms >= 0),
  PRIMARY KEY (org_id, apply_id, actor_instance_id),
  FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, apply_id) REFERENCES db_resource_apply_runs (org_id, id) ON DELETE CASCADE,
  FOREIGN KEY (org_id, actor_instance_id, actor_definition_name)
    REFERENCES legacy_actor_instances (org_id, id, actor_definition_name) ON DELETE CASCADE,
  CHECK ((status IN ('stopFailed', 'startFailed', 'crashed') AND error_json IS NOT NULL)
    OR status NOT IN ('stopFailed', 'startFailed', 'crashed'))
) STRICT;

CREATE INDEX legacy_actor_apply_results_actor_idx
  ON legacy_actor_apply_results (org_id, actor_instance_id, updated_at_ms);
CREATE INDEX legacy_actor_apply_results_instance_fk_idx
  ON legacy_actor_apply_results (org_id, actor_instance_id, actor_definition_name);

INSERT INTO organizations (id, slug, name, status, created_at_ms, updated_at_ms)
VALUES ('00000000-0000-4000-8000-000000000001', 'local', 'Local', 'active', 0, 0);

INSERT INTO accounts (id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms)
VALUES ('00000000-0000-4000-8000-000000000002', 'user', 'Local Owner', 'active', 1, 0, 0);

INSERT INTO organization_memberships (
  org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
)
VALUES (
  '00000000-0000-4000-8000-000000000001',
  '00000000-0000-4000-8000-000000000002',
  'owner', 'active', 1, 0, 0
);
