/** @file Local bounds for process-owned Preview state. */

export const PREVIEW_SESSION_ID_MAX_LENGTH = 100;
export const PREVIEW_WIDGET_KEY_MAX_LENGTH = 100;
export const PREVIEW_IDENTITY_MAX_LENGTH = 500;

export const PREVIEW_DEFAULT_MAX_SESSIONS = 8;
export const PREVIEW_DEFAULT_MAX_CACHED_CONSTRUCTIONS = 8;
export const PREVIEW_DEFAULT_MAX_MOUNTED_HANDLES = 8;
export const PREVIEW_DEFAULT_MAX_DIAGNOSTICS = 128;
export const PREVIEW_DEFAULT_MAX_DIAGNOSTIC_CHARACTERS = 4_096;
