export type TExpectedColumn = {
  readonly name: string;
  readonly type: "BLOB" | "INTEGER" | "REAL" | "TEXT";
  readonly notNull: boolean;
  readonly primaryKeyPosition: number;
};

export type TExpectedForeignKey = {
  readonly columns: readonly string[];
  readonly referencesTable: string;
  readonly referencesColumns: readonly string[];
  readonly onDelete: "CASCADE" | "RESTRICT";
};

export type TExpectedTable = {
  readonly columns: readonly TExpectedColumn[];
  readonly primaryKey: readonly string[];
  readonly unique: readonly (readonly string[])[];
  readonly foreignKeys: readonly TExpectedForeignKey[];
  readonly requiredSqlFragments?: readonly string[];
};

export type TExpectedIndex = {
  readonly table: string;
  readonly columns: readonly string[];
  readonly unique: boolean;
  readonly partial: boolean;
};

export type TExpectedSchema = Readonly<Record<string, TExpectedTable>>;
export type TExpectedIndexManifest = Readonly<Record<string, TExpectedIndex>>;

export type TExpectedSchemaObjectManifest = Readonly<{
  views: readonly string[];
  triggers: readonly string[];
}>;

export type TExpectedDatabaseSchemaContract = Readonly<{
  fingerprintSha256: string;
  indexes: TExpectedIndexManifest;
  objects: TExpectedSchemaObjectManifest;
  tables: TExpectedSchema;
  version: number;
}>;

export const EXPECTED_APPLICATION_TABLES = [
  "accounts",
  "agent_chats",
  "agent_drafts",
  "agent_previews",
  "artifact_references",
  "canvas_members",
  "canvases",
  "collaboration_chunks",
  "collaboration_documents",
  "db_resource_apply_runs",
  "db_resource_backups",
  "db_resource_draft_changes",
  "db_resource_drafts",
  "file_systems",
  "function_attempts",
  "function_invocations",
  "idempotency_records",
  "invocation_leases",
  "key_values",
  "legacy_actor_apply_results",
  "legacy_actor_connections",
  "legacy_actor_definitions",
  "legacy_actor_instances",
  "legacy_actor_resource_bindings",
  "media_files",
  "organization_memberships",
  "organizations",
  "pty_session_metadata",
  "resource_bindings",
  "resource_catalog",
  "resource_encryption_keys",
  "resource_placements",
  "resource_write_permits",
  "schema_migrations",
  "scoped_events",
  "tool_groups",
  "usage_outbox",
  "widget_definition_revisions",
  "widget_definitions",
  "widget_instances",
] as const;

export const EXPECTED_APPLICATION_TABLE_COUNT = EXPECTED_APPLICATION_TABLES.length;

export const EXPECTED_APPLICATION_SCHEMA_OBJECTS = Object.freeze({
  views: Object.freeze([]),
  triggers: Object.freeze([]),
}) satisfies TExpectedSchemaObjectManifest;

const column = (
  name: string,
  type: TExpectedColumn["type"],
  notNull: boolean,
  primaryKeyPosition = 0,
): TExpectedColumn => ({ name, type, notNull, primaryKeyPosition });

const tenantId = (name: string, primaryKeyPosition = 0) => column(name, "TEXT", true, primaryKeyPosition);
const text = (name: string, notNull = true, primaryKeyPosition = 0) =>
  column(name, "TEXT", notNull, primaryKeyPosition);
const integer = (name: string, notNull = true, primaryKeyPosition = 0) =>
  column(name, "INTEGER", notNull, primaryKeyPosition);

export const EXPECTED_BASELINE_SCHEMA = {
  accounts: {
    columns: [tenantId("id", 1), text("kind"), text("display_name"), text("status"), integer("is_autogenerated"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["id"], unique: [], foreignKeys: [],
  },
  organizations: {
    columns: [tenantId("id", 1), text("slug"), text("name"), text("status"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["id"], unique: [["slug"]], foreignKeys: [],
  },
  organization_memberships: {
    columns: [tenantId("org_id", 1), tenantId("account_id", 2), text("role"), text("status"), integer("is_billable_seat"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "account_id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["account_id"], referencesTable: "accounts", referencesColumns: ["id"], onDelete: "RESTRICT" },
    ],
  },
  key_values: {
    columns: [tenantId("org_id", 1), text("name", true, 2), text("kind"), text("text_value", false), text("json_value", false), column("number_value", "REAL", false, 0), integer("bool_value", false), column("blob_value", "BLOB", false, 0), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "name"], unique: [],
    foreignKeys: [{ columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" }],
  },
  canvases: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("name"), text("access_policy"), tenantId("created_by_account_id"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "name"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "created_by_account_id"], referencesTable: "organization_memberships", referencesColumns: ["org_id", "account_id"], onDelete: "RESTRICT" },
    ],
  },
  canvas_members: {
    columns: [tenantId("org_id", 1), tenantId("canvas_id", 2), tenantId("account_id", 3), text("role"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "canvas_id", "account_id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "canvas_id"], referencesTable: "canvases", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "account_id"], referencesTable: "organization_memberships", referencesColumns: ["org_id", "account_id"], onDelete: "CASCADE" },
    ],
  },
  artifact_references: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("kind"), text("digest_sha256"), integer("byte_size"), text("retention_state"), integer("retain_until_ms", false), integer("created_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "id", "kind"], ["org_id", "kind", "digest_sha256"]],
    foreignKeys: [{ columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" }],
  },
  widget_definitions: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("slug"), text("name"), text("status"), text("active_revision_id", false), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "slug"], ["org_id", "name"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "id", "active_revision_id"], referencesTable: "widget_definition_revisions", referencesColumns: ["org_id", "definition_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  widget_definition_revisions: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("definition_id"), integer("revision_number"), tenantId("ui_artifact_id"), text("ui_artifact_kind"), text("server_artifact_id", false), text("server_artifact_kind", false), text("manifest_json"), text("contract_digest_sha256"), integer("created_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "definition_id", "id"], ["org_id", "definition_id", "revision_number"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "definition_id"], referencesTable: "widget_definitions", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "ui_artifact_id", "ui_artifact_kind"], referencesTable: "artifact_references", referencesColumns: ["org_id", "id", "kind"], onDelete: "RESTRICT" },
      { columns: ["org_id", "server_artifact_id", "server_artifact_kind"], referencesTable: "artifact_references", referencesColumns: ["org_id", "id", "kind"], onDelete: "RESTRICT" },
    ],
  },
  widget_instances: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("canvas_id"), text("element_id"), tenantId("definition_id"), tenantId("revision_id"), text("status"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "definition_id", "revision_id", "id"], ["org_id", "canvas_id", "element_id"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "canvas_id"], referencesTable: "canvases", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "definition_id"], referencesTable: "widget_definitions", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "definition_id", "revision_id"], referencesTable: "widget_definition_revisions", referencesColumns: ["org_id", "definition_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  collaboration_documents: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("canvas_id", false), text("widget_instance_id", false), text("automerge_url"), text("partition_key"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "automerge_url"], ["org_id", "canvas_id"], ["org_id", "widget_instance_id"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "canvas_id"], referencesTable: "canvases", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "widget_instance_id"], referencesTable: "widget_instances", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
    ],
  },
  collaboration_chunks: {
    columns: [tenantId("org_id", 1), tenantId("document_id", 2), text("chunk_key", true, 3), integer("sequence"), column("chunk_bytes", "BLOB", true, 0), integer("created_at_ms")],
    primaryKey: ["org_id", "document_id", "chunk_key"], unique: [["org_id", "document_id", "sequence"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "document_id"], referencesTable: "collaboration_documents", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
    ],
  },
  resource_catalog: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("kind"), text("name"), text("status"), text("last_error_json", false), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "id", "kind"], ["org_id", "name"]],
    foreignKeys: [{ columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" }],
  },
  resource_bindings: {
    columns: [tenantId("org_id", 1), tenantId("definition_id", 2), tenantId("revision_id", 3), text("slot_name", true, 4), tenantId("resource_id"), text("resource_kind"), integer("is_required"), integer("manifest_allow_read"), integer("manifest_allow_write"), integer("allow_read"), integer("allow_write"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "definition_id", "revision_id", "slot_name"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "definition_id", "revision_id"], referencesTable: "widget_definition_revisions", referencesColumns: ["org_id", "definition_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "resource_id", "resource_kind"], referencesTable: "resource_catalog", referencesColumns: ["org_id", "id", "kind"], onDelete: "RESTRICT" },
    ],
  },
  resource_placements: {
    columns: [tenantId("org_id", 1), tenantId("resource_id", 2), tenantId("cell_id"), integer("placement_epoch"), text("relative_path"), text("status"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "resource_id"], unique: [["org_id", "relative_path"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "resource_id"], referencesTable: "resource_catalog", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
    ],
  },
  resource_encryption_keys: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("resource_id"), text("purpose"), text("algorithm"), column("key_material", "BLOB", true, 0), integer("created_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "resource_id"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "resource_id"], referencesTable: "resource_catalog", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
    ],
  },
  db_resource_drafts: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("resource_id"), text("resource_kind"), text("name"), text("status"), text("last_error_json", false), integer("created_at_ms"), integer("updated_at_ms"), integer("applied_at_ms", false)],
    primaryKey: ["org_id", "id"], unique: [["org_id", "resource_id", "id"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "resource_id", "resource_kind"], referencesTable: "resource_catalog", referencesColumns: ["org_id", "id", "kind"], onDelete: "CASCADE" },
    ],
  },
  db_resource_draft_changes: {
    columns: [tenantId("org_id", 1), tenantId("draft_id", 2), integer("sequence", true, 3), text("kind"), text("operation_json", false), text("sql_text"), integer("created_at_ms")],
    primaryKey: ["org_id", "draft_id", "sequence"], unique: [],
    requiredSqlFragments: [
      "json_type(operation_json, '$.type') = 'text'",
      "json_extract(operation_json, '$.type') = 'boundSql'",
      "json_type(operation_json, '$.parameters') = 'array'",
    ],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "draft_id"], referencesTable: "db_resource_drafts", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
    ],
  },
  db_resource_apply_runs: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("resource_id"), text("draft_id", false), text("source_apply_id", false), text("status"), text("last_error_json", false), integer("backup_retained"), integer("created_at_ms"), integer("completed_at_ms", false)],
    primaryKey: ["org_id", "id"], unique: [["org_id", "resource_id", "id"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "resource_id"], referencesTable: "resource_catalog", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "resource_id", "draft_id"], referencesTable: "db_resource_drafts", referencesColumns: ["org_id", "resource_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "resource_id", "source_apply_id"], referencesTable: "db_resource_apply_runs", referencesColumns: ["org_id", "resource_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  db_resource_backups: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("resource_id"), tenantId("apply_run_id"), text("relative_path"), text("digest_sha256"), integer("byte_size"), text("state"), integer("created_at_ms"), integer("verified_at_ms"), integer("delete_after_ms", false)],
    primaryKey: ["org_id", "id"], unique: [["org_id", "resource_id", "apply_run_id"], ["org_id", "relative_path"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "resource_id"], referencesTable: "resource_catalog", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "resource_id", "apply_run_id"], referencesTable: "db_resource_apply_runs", referencesColumns: ["org_id", "resource_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  function_invocations: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("account_id"), tenantId("widget_definition_id"), tenantId("widget_revision_id"), tenantId("widget_instance_id"), text("function_name"), text("input_json"), text("input_digest_sha256"), integer("policy_version"), integer("priority"), text("status"), text("result_json", false), integer("output_byte_size"), integer("log_byte_size"), integer("created_at_ms"), integer("deadline_at_ms"), integer("started_at_ms", false), integer("finished_at_ms", false)],
    primaryKey: ["org_id", "id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "account_id"], referencesTable: "organization_memberships", referencesColumns: ["org_id", "account_id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "widget_definition_id", "widget_revision_id"], referencesTable: "widget_definition_revisions", referencesColumns: ["org_id", "definition_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "widget_definition_id", "widget_revision_id", "widget_instance_id"], referencesTable: "widget_instances", referencesColumns: ["org_id", "definition_id", "revision_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  function_attempts: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("invocation_id"), integer("attempt_number"), integer("lease_epoch"), text("status"), text("sandbox_driver"), text("memory_tier"), integer("active_wall_ms"), integer("cpu_ms"), integer("allocated_memory_byte_ms"), integer("peak_rss_bytes"), integer("disk_read_bytes"), integer("disk_write_bytes"), integer("network_rx_bytes"), integer("network_tx_bytes"), integer("cold_start"), text("failure_owner", false), integer("billable"), integer("created_at_ms"), integer("started_at_ms", false), integer("finished_at_ms", false)],
    primaryKey: ["org_id", "id"], unique: [["org_id", "invocation_id", "id"], ["org_id", "invocation_id", "attempt_number"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "invocation_id"], referencesTable: "function_invocations", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  invocation_leases: {
    columns: [tenantId("org_id", 1), tenantId("invocation_id", 2), tenantId("attempt_id"), integer("lease_epoch"), text("worker_id"), integer("created_at_ms"), integer("heartbeat_at_ms"), integer("expires_at_ms")],
    primaryKey: ["org_id", "invocation_id"], unique: [["org_id", "invocation_id", "lease_epoch"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "invocation_id"], referencesTable: "function_invocations", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "invocation_id", "attempt_id"], referencesTable: "function_attempts", referencesColumns: ["org_id", "invocation_id", "id"], onDelete: "CASCADE" },
    ],
  },
  idempotency_records: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("scope_kind"), text("canvas_id", false), text("widget_instance_id", false), text("idempotency_key"), text("request_fingerprint_sha256"), tenantId("widget_definition_id"), tenantId("widget_revision_id"), tenantId("invocation_id"), integer("created_at_ms"), integer("expires_at_ms", false)],
    primaryKey: ["org_id", "id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "canvas_id"], referencesTable: "canvases", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "widget_instance_id"], referencesTable: "widget_instances", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "widget_definition_id", "widget_revision_id"], referencesTable: "widget_definition_revisions", referencesColumns: ["org_id", "definition_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "invocation_id"], referencesTable: "function_invocations", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  resource_write_permits: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("resource_id"), tenantId("invocation_id"), tenantId("attempt_id"), integer("lease_epoch"), text("operation_name"), text("status"), integer("issued_at_ms"), integer("expires_at_ms"), integer("consumed_at_ms", false)],
    primaryKey: ["org_id", "id"], unique: [["org_id", "resource_id", "id"], ["org_id", "resource_id", "invocation_id", "attempt_id", "operation_name"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "resource_id"], referencesTable: "resource_catalog", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "invocation_id"], referencesTable: "function_invocations", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "invocation_id", "attempt_id"], referencesTable: "function_attempts", referencesColumns: ["org_id", "invocation_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  scoped_events: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("topic"), integer("sequence"), text("event_type"), text("payload_json"), integer("created_at_ms"), integer("retain_until_ms", false)],
    primaryKey: ["org_id", "id"], unique: [["org_id", "topic", "sequence"]],
    foreignKeys: [{ columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" }],
  },
  usage_outbox: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("account_id"), text("attempt_id", false), text("resource_id", false), text("resource_permit_id", false), text("state"), text("outcome"), text("failure_owner", false), integer("billable"), integer("policy_version"), integer("active_wall_ms"), integer("cpu_ms"), integer("allocated_memory_byte_ms"), integer("peak_rss_bytes"), integer("disk_read_bytes"), integer("disk_write_bytes"), integer("network_rx_bytes"), integer("network_tx_bytes"), integer("created_at_ms"), integer("imported_at_ms", false)],
    primaryKey: ["org_id", "id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "account_id"], referencesTable: "organization_memberships", referencesColumns: ["org_id", "account_id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "attempt_id"], referencesTable: "function_attempts", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "resource_id", "resource_permit_id"], referencesTable: "resource_write_permits", referencesColumns: ["org_id", "resource_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  media_files: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("canvas_id", false), text("source_hash"), text("digest_sha256", false), text("mime_type"), integer("byte_size"), column("data", "BLOB", true, 0), integer("created_at_ms")],
    primaryKey: ["org_id", "id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "canvas_id"], referencesTable: "canvases", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
    ],
  },
  file_systems: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("name"), text("slug"), text("capability_ref"), text("relative_root"), text("description", false), text("status"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "name"], ["org_id", "slug"], ["org_id", "capability_ref"]],
    foreignKeys: [{ columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "RESTRICT" }],
  },
  tool_groups: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), text("name"), text("configuration_json", false), text("status"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "name"]],
    foreignKeys: [{ columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" }],
  },
  pty_session_metadata: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("account_id"), tenantId("file_system_id"), text("cwd_relative_path"), text("status"), integer("exit_code", false), integer("created_at_ms"), integer("closed_at_ms", false), integer("retain_until_ms", false)],
    primaryKey: ["org_id", "id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "account_id"], referencesTable: "organization_memberships", referencesColumns: ["org_id", "account_id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "file_system_id"], referencesTable: "file_systems", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  agent_chats: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("account_id"), text("canvas_id", false), text("name"), text("status"), text("workspace_relative_path"), text("history_relative_path"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "workspace_relative_path"], ["org_id", "history_relative_path"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "account_id"], referencesTable: "organization_memberships", referencesColumns: ["org_id", "account_id"], onDelete: "RESTRICT" },
      { columns: ["org_id", "canvas_id"], referencesTable: "canvases", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  agent_drafts: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("chat_id"), text("name"), text("status"), text("source_relative_path"), text("source_digest_sha256", false), text("last_error_json", false), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "chat_id", "source_relative_path"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "chat_id"], referencesTable: "agent_chats", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
    ],
  },
  agent_previews: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("draft_id"), text("artifact_id", false), text("artifact_kind", false), text("relative_path"), text("status"), text("last_error_json", false), integer("created_at_ms"), integer("updated_at_ms"), integer("expires_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "relative_path"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "draft_id"], referencesTable: "agent_drafts", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "artifact_id", "artifact_kind"], referencesTable: "artifact_references", referencesColumns: ["org_id", "id", "kind"], onDelete: "RESTRICT" },
    ],
  },
  legacy_actor_definitions: {
    columns: [tenantId("org_id", 1), text("name", true, 2), text("slug"), text("url", false), text("description", false), text("manifest_relative_path"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "name"], unique: [["org_id", "slug"]],
    foreignKeys: [{ columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" }],
  },
  legacy_actor_instances: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("canvas_id"), text("element_id"), text("actor_definition_name"), text("file_system_id", false), text("display_name"), text("status"), text("machine_state"), text("machine_context_json"), text("last_error_json", false), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "id"], unique: [["org_id", "canvas_id", "id"], ["org_id", "id", "actor_definition_name"], ["org_id", "canvas_id", "element_id"]],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "canvas_id"], referencesTable: "canvases", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "actor_definition_name"], referencesTable: "legacy_actor_definitions", referencesColumns: ["org_id", "name"], onDelete: "CASCADE" },
      { columns: ["org_id", "file_system_id"], referencesTable: "file_systems", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  legacy_actor_connections: {
    columns: [tenantId("org_id", 1), tenantId("id", 2), tenantId("canvas_id"), tenantId("source_actor_instance_id"), tenantId("target_actor_instance_id"), integer("enabled"), text("label", false), text("message_name_whitelist_json", false), text("style_json"), integer("created_at_ms")],
    primaryKey: ["org_id", "id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "canvas_id"], referencesTable: "canvases", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "canvas_id", "source_actor_instance_id"], referencesTable: "legacy_actor_instances", referencesColumns: ["org_id", "canvas_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "canvas_id", "target_actor_instance_id"], referencesTable: "legacy_actor_instances", referencesColumns: ["org_id", "canvas_id", "id"], onDelete: "CASCADE" },
    ],
  },
  legacy_actor_resource_bindings: {
    columns: [tenantId("org_id", 1), text("definition_name", true, 2), text("slot_name", true, 3), tenantId("resource_id"), integer("allow_read"), integer("allow_write"), integer("created_at_ms"), integer("updated_at_ms")],
    primaryKey: ["org_id", "definition_name", "slot_name"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "definition_name"], referencesTable: "legacy_actor_definitions", referencesColumns: ["org_id", "name"], onDelete: "CASCADE" },
      { columns: ["org_id", "resource_id"], referencesTable: "resource_catalog", referencesColumns: ["org_id", "id"], onDelete: "RESTRICT" },
    ],
  },
  legacy_actor_apply_results: {
    columns: [tenantId("org_id", 1), tenantId("apply_id", 2), tenantId("actor_instance_id", 3), text("actor_definition_name"), integer("was_running"), text("status"), text("error_json", false), integer("updated_at_ms")],
    primaryKey: ["org_id", "apply_id", "actor_instance_id"], unique: [],
    foreignKeys: [
      { columns: ["org_id"], referencesTable: "organizations", referencesColumns: ["id"], onDelete: "CASCADE" },
      { columns: ["org_id", "apply_id"], referencesTable: "db_resource_apply_runs", referencesColumns: ["org_id", "id"], onDelete: "CASCADE" },
      { columns: ["org_id", "actor_instance_id", "actor_definition_name"], referencesTable: "legacy_actor_instances", referencesColumns: ["org_id", "id", "actor_definition_name"], onDelete: "CASCADE" },
    ],
  },
  schema_migrations: {
    columns: [integer("version", false, 1), text("name"), text("checksum_sha256"), integer("applied_at_ms"), text("application_version")],
    primaryKey: ["version"], unique: [["name"]], foreignKeys: [],
  },
} satisfies Record<(typeof EXPECTED_APPLICATION_TABLES)[number], TExpectedTable>;

export const EXPECTED_SCHEMA = {
  ...EXPECTED_BASELINE_SCHEMA,
  widget_definitions: {
    ...EXPECTED_BASELINE_SCHEMA.widget_definitions,
    columns: [
      ...EXPECTED_BASELINE_SCHEMA.widget_definitions.columns,
      integer("next_revision_number"),
    ],
    requiredSqlFragments: [
      "next_revision_number INTEGER NOT NULL DEFAULT 1 CHECK (next_revision_number >= 1)",
    ],
  },
} satisfies Record<(typeof EXPECTED_APPLICATION_TABLES)[number], TExpectedTable>;

export const EXPECTED_INDEXES = {
  organization_memberships_account_idx: { table: "organization_memberships", columns: ["account_id", "org_id"], unique: false, partial: false },
  organization_memberships_status_idx: { table: "organization_memberships", columns: ["org_id", "status", "role"], unique: false, partial: false },
  canvases_creator_idx: { table: "canvases", columns: ["org_id", "created_by_account_id"], unique: false, partial: false },
  canvas_members_account_idx: { table: "canvas_members", columns: ["org_id", "account_id", "canvas_id"], unique: false, partial: false },
  artifact_references_retention_idx: { table: "artifact_references", columns: ["org_id", "retention_state", "retain_until_ms"], unique: false, partial: false },
  widget_definitions_active_revision_idx: { table: "widget_definitions", columns: ["org_id", "id", "active_revision_id"], unique: false, partial: false },
  widget_definition_revisions_lookup_idx: { table: "widget_definition_revisions", columns: ["org_id", "definition_id", "revision_number"], unique: false, partial: false },
  widget_definition_revisions_ui_artifact_idx: { table: "widget_definition_revisions", columns: ["org_id", "ui_artifact_id", "ui_artifact_kind"], unique: false, partial: false },
  widget_definition_revisions_server_artifact_idx: { table: "widget_definition_revisions", columns: ["org_id", "server_artifact_id", "server_artifact_kind"], unique: false, partial: false },
  widget_instances_definition_idx: { table: "widget_instances", columns: ["org_id", "definition_id", "revision_id"], unique: false, partial: false },
  collaboration_documents_partition_idx: { table: "collaboration_documents", columns: ["org_id", "partition_key", "id"], unique: false, partial: false },
  resource_catalog_status_idx: { table: "resource_catalog", columns: ["org_id", "status", "created_at_ms"], unique: false, partial: false },
  resource_catalog_kind_idx: { table: "resource_catalog", columns: ["org_id", "kind", "status"], unique: false, partial: false },
  resource_bindings_resource_idx: { table: "resource_bindings", columns: ["org_id", "resource_id", "resource_kind"], unique: false, partial: false },
  resource_placements_cell_idx: { table: "resource_placements", columns: ["org_id", "cell_id", "status"], unique: false, partial: false },
  db_resource_drafts_resource_idx: { table: "db_resource_drafts", columns: ["org_id", "resource_id", "status", "created_at_ms"], unique: false, partial: false },
  db_resource_drafts_resource_kind_idx: { table: "db_resource_drafts", columns: ["org_id", "resource_id", "resource_kind"], unique: false, partial: false },
  db_resource_drafts_one_active_idx: { table: "db_resource_drafts", columns: ["org_id", "resource_id"], unique: true, partial: true },
  db_resource_apply_runs_resource_idx: { table: "db_resource_apply_runs", columns: ["org_id", "resource_id", "status", "created_at_ms"], unique: false, partial: false },
  db_resource_apply_runs_draft_idx: { table: "db_resource_apply_runs", columns: ["org_id", "resource_id", "draft_id"], unique: false, partial: false },
  db_resource_apply_runs_source_idx: { table: "db_resource_apply_runs", columns: ["org_id", "resource_id", "source_apply_id"], unique: false, partial: false },
  db_resource_apply_runs_one_active_idx: { table: "db_resource_apply_runs", columns: ["org_id", "resource_id"], unique: true, partial: true },
  db_resource_backups_retention_idx: { table: "db_resource_backups", columns: ["org_id", "state", "delete_after_ms"], unique: false, partial: false },
  function_invocations_queue_idx: { table: "function_invocations", columns: ["org_id", "status", "created_at_ms"], unique: false, partial: false },
  function_invocations_revision_idx: { table: "function_invocations", columns: ["org_id", "widget_definition_id", "widget_revision_id", "created_at_ms"], unique: false, partial: false },
  function_invocations_account_idx: { table: "function_invocations", columns: ["org_id", "account_id", "created_at_ms"], unique: false, partial: false },
  function_invocations_instance_idx: { table: "function_invocations", columns: ["org_id", "widget_definition_id", "widget_revision_id", "widget_instance_id"], unique: false, partial: false },
  function_attempts_invocation_idx: { table: "function_attempts", columns: ["org_id", "invocation_id", "attempt_number"], unique: false, partial: false },
  invocation_leases_expiry_idx: { table: "invocation_leases", columns: ["expires_at_ms", "org_id"], unique: false, partial: false },
  invocation_leases_attempt_idx: { table: "invocation_leases", columns: ["org_id", "invocation_id", "attempt_id"], unique: false, partial: false },
  idempotency_records_org_key_idx: { table: "idempotency_records", columns: ["org_id", "idempotency_key"], unique: true, partial: true },
  idempotency_records_canvas_key_idx: { table: "idempotency_records", columns: ["org_id", "canvas_id", "idempotency_key"], unique: true, partial: true },
  idempotency_records_widget_key_idx: { table: "idempotency_records", columns: ["org_id", "widget_instance_id", "idempotency_key"], unique: true, partial: true },
  idempotency_records_expiry_idx: { table: "idempotency_records", columns: ["org_id", "expires_at_ms"], unique: false, partial: false },
  idempotency_records_revision_idx: { table: "idempotency_records", columns: ["org_id", "widget_definition_id", "widget_revision_id"], unique: false, partial: false },
  idempotency_records_invocation_idx: { table: "idempotency_records", columns: ["org_id", "invocation_id"], unique: false, partial: false },
  resource_write_permits_expiry_idx: { table: "resource_write_permits", columns: ["org_id", "status", "expires_at_ms"], unique: false, partial: false },
  resource_write_permits_attempt_idx: { table: "resource_write_permits", columns: ["org_id", "invocation_id", "attempt_id"], unique: false, partial: false },
  scoped_events_replay_idx: { table: "scoped_events", columns: ["org_id", "topic", "sequence"], unique: false, partial: false },
  scoped_events_retention_idx: { table: "scoped_events", columns: ["org_id", "retain_until_ms"], unique: false, partial: false },
  usage_outbox_attempt_receipt_idx: { table: "usage_outbox", columns: ["org_id", "attempt_id"], unique: true, partial: true },
  usage_outbox_resource_receipt_idx: { table: "usage_outbox", columns: ["org_id", "resource_permit_id"], unique: true, partial: true },
  usage_outbox_import_idx: { table: "usage_outbox", columns: ["org_id", "state", "created_at_ms"], unique: false, partial: false },
  usage_outbox_account_idx: { table: "usage_outbox", columns: ["org_id", "account_id", "created_at_ms"], unique: false, partial: false },
  usage_outbox_resource_permit_idx: { table: "usage_outbox", columns: ["org_id", "resource_id", "resource_permit_id"], unique: false, partial: false },
  media_files_canvas_idx: { table: "media_files", columns: ["org_id", "canvas_id", "created_at_ms"], unique: false, partial: false },
  media_files_source_hash_idx: { table: "media_files", columns: ["org_id", "source_hash"], unique: false, partial: false },
  media_files_digest_idx: { table: "media_files", columns: ["org_id", "digest_sha256"], unique: false, partial: false },
  pty_session_metadata_retention_idx: { table: "pty_session_metadata", columns: ["org_id", "status", "retain_until_ms"], unique: false, partial: false },
  pty_session_metadata_account_idx: { table: "pty_session_metadata", columns: ["org_id", "account_id", "created_at_ms"], unique: false, partial: false },
  pty_session_metadata_filesystem_idx: { table: "pty_session_metadata", columns: ["org_id", "file_system_id"], unique: false, partial: false },
  agent_chats_account_idx: { table: "agent_chats", columns: ["org_id", "account_id", "created_at_ms"], unique: false, partial: false },
  agent_chats_canvas_idx: { table: "agent_chats", columns: ["org_id", "canvas_id", "created_at_ms"], unique: false, partial: false },
  agent_drafts_chat_idx: { table: "agent_drafts", columns: ["org_id", "chat_id", "created_at_ms"], unique: false, partial: false },
  agent_previews_draft_idx: { table: "agent_previews", columns: ["org_id", "draft_id", "created_at_ms"], unique: false, partial: false },
  agent_previews_expiry_idx: { table: "agent_previews", columns: ["org_id", "status", "expires_at_ms"], unique: false, partial: false },
  agent_previews_artifact_idx: { table: "agent_previews", columns: ["org_id", "artifact_id", "artifact_kind"], unique: false, partial: false },
  legacy_actor_instances_definition_idx: { table: "legacy_actor_instances", columns: ["org_id", "actor_definition_name", "status"], unique: false, partial: false },
  legacy_actor_instances_filesystem_idx: { table: "legacy_actor_instances", columns: ["org_id", "file_system_id"], unique: false, partial: false },
  legacy_actor_connections_source_idx: { table: "legacy_actor_connections", columns: ["org_id", "source_actor_instance_id"], unique: false, partial: false },
  legacy_actor_connections_target_idx: { table: "legacy_actor_connections", columns: ["org_id", "target_actor_instance_id"], unique: false, partial: false },
  legacy_actor_connections_source_fk_idx: { table: "legacy_actor_connections", columns: ["org_id", "canvas_id", "source_actor_instance_id"], unique: false, partial: false },
  legacy_actor_connections_target_fk_idx: { table: "legacy_actor_connections", columns: ["org_id", "canvas_id", "target_actor_instance_id"], unique: false, partial: false },
  legacy_actor_resource_bindings_resource_idx: { table: "legacy_actor_resource_bindings", columns: ["org_id", "resource_id"], unique: false, partial: false },
  legacy_actor_apply_results_actor_idx: { table: "legacy_actor_apply_results", columns: ["org_id", "actor_instance_id", "updated_at_ms"], unique: false, partial: false },
  legacy_actor_apply_results_instance_fk_idx: { table: "legacy_actor_apply_results", columns: ["org_id", "actor_instance_id", "actor_definition_name"], unique: false, partial: false },
} satisfies Record<string, TExpectedIndex>;

export const EXPECTED_DATABASE_SCHEMA_CONTRACTS = Object.freeze([
  Object.freeze({
    fingerprintSha256: 'fe0edf0f26dc7d0093527bfc60e8780eaad4b2be6b30ecfa9630835ff4a8366a',
    indexes: EXPECTED_INDEXES,
    objects: EXPECTED_APPLICATION_SCHEMA_OBJECTS,
    tables: EXPECTED_BASELINE_SCHEMA,
    version: 0,
  }),
  Object.freeze({
    fingerprintSha256: '53c179a62377f2c2886c15b63f44dd367ba9f18acd763dc786051a42d79afb94',
    indexes: EXPECTED_INDEXES,
    objects: EXPECTED_APPLICATION_SCHEMA_OBJECTS,
    tables: EXPECTED_SCHEMA,
    version: 1,
  }),
]) satisfies readonly TExpectedDatabaseSchemaContract[];
