/** Public Effect-free Omnidraw theme surface. */

export {
  CANVAS_COLOR_CODES,
  CANVAS_COLOR_ROLES,
  CANVAS_FILL_COLOR_CODES,
  CANVAS_INK_COLOR_CODES,
  OMNIDRAW_THEME_APPEARANCE_ATTRIBUTE,
  OMNIDRAW_THEME_DARK_CLASS,
  OMNIDRAW_THEME_ID_ATTRIBUTE,
  OMNIDRAW_THEME_SCOPE_ATTRIBUTE,
  THEME_APPEARANCES,
  THEME_UI_COLOR_ROLES,
} from "./CONSTANTS.js";
export {
  fnAssertThemeDefinition,
  fnIsCanvasColorCode,
  fnIsCanvasInkColorCode,
  fnThemeDefinitionIssues,
  fnThemeSrgbColorValid,
} from "./fn.validation.js";
export {
  BUILTIN_THEMES,
  DEFAULT_THEME_ID,
  THEME_ID_DARK,
  THEME_ID_GRAPHITE,
  THEME_ID_LIGHT,
  THEME_ID_SEPIA,
} from "./builtins.js";
export { ThemeService, type TThemeServiceArgs } from "./ThemeService.js";
export type {
  IThemeService,
  TThemeChangeListener,
  TThemeRegistryChangeListener,
  TThemeRememberedStyleChangeListener,
} from "./interface.js";
export {
  applyThemeToElement,
  fnGetThemeCssVariables,
  fnThemeCssRule,
} from "./dom.js";
export {
  fnGetThemeColorPickerPalette,
  fnGetThemeColorValueMap,
  fnGetThemeStyle,
  fnIsThemeColorToken,
  fnResolveThemeCanvasColor,
  fnResolveThemeColor,
  fnThemeSrgbColorToCss,
} from "./styles.js";
export {
  fnCreateThemeStyleDefaults,
  THEME_CORNER_RADIUS_OPTIONS,
  THEME_CORNER_RADIUS_VALUE_MAP,
  THEME_FONT_SIZE_OPTIONS,
  THEME_FONT_SIZE_VALUE_MAP,
  THEME_STROKE_STYLE_OPTIONS,
  THEME_STROKE_WIDTH_OPTIONS,
  THEME_STROKE_WIDTH_VALUE_MAP,
  THEME_STYLE_DEFAULTS_BY_SCOPE,
  THEME_TEXT_ALIGN_OPTIONS,
  THEME_VERTICAL_ALIGN_OPTIONS,
} from "./style.shared.js";
export {
  THEME_CORNER_RADIUS_NAMES,
  THEME_FONT_SIZE_NAMES,
  THEME_STROKE_STYLES,
  THEME_STROKE_WIDTH_NAMES,
  THEME_STYLE_SCOPE_IDS,
  THEME_TEXT_ALIGNS,
  THEME_VERTICAL_ALIGNS,
  type ThemeId,
  type TCanvasColorCode,
  type TCanvasColorRole,
  type TCanvasFillColorCode,
  type TCanvasInkColorCode,
  type TCanvasThemeStyle,
  type TResolvedThemeCanvasStyle,
  type TThemeAppearance,
  type TThemeBuiltinStyleScopeId,
  type TThemeCanvasChrome,
  type TThemeCanvasColorPalette,
  type TThemeCanvasColorSwatch,
  type TThemeCanvasInkSwatch,
  type TThemeCanvasStyle,
  type TThemeCanvasViewport,
  type TThemeColorPickerPalette,
  type TThemeColorValueMap,
  type TThemeCornerRadiusName,
  type TThemeCornerRadiusOption,
  type TThemeCornerRadiusToken,
  type TThemeCornerRadiusValueMap,
  type TThemeDefinition,
  type TThemeDefinitionInheritance,
  type TThemeFontSizeName,
  type TThemeFontSizeOption,
  type TThemeFontSizeToken,
  type TThemeFontSizeValueMap,
  type TThemePathAppearance,
  type TThemeRegistration,
  type TThemeRememberedStyle,
  type TThemeRememberedStyleMap,
  type TThemeSelectionAppearance,
  type TThemeSnapshot,
  type TThemeSrgbColor,
  type TThemeStrokeStyle,
  type TThemeStrokeStyleOption,
  type TThemeStrokeWidthName,
  type TThemeStrokeWidthOption,
  type TThemeStrokeWidthToken,
  type TThemeStrokeWidthValueMap,
  type TThemeStyleDefaultsMap,
  type TThemeStyleScopeId,
  type TThemeTerminalColors,
  type TThemeTextAlign,
  type TThemeTextAlignOption,
  type TThemeTokenOption,
  type TThemeUiColorRole,
  type TThemeUiColors,
  type TThemeVerticalAlign,
  type TThemeVerticalAlignOption,
} from "./types.js";
