import type { Database } from "@tursodatabase/database"
import type { TTenantContext } from "@vibecanvas/tenant-core"
import type { TAccount } from "../model"
import { fnBooleanFromSql, fnTimestampFromMs } from "./fn.legacy-row"

type TPortal = {
  db: Database
}
type TArgs = { tenant: TTenantContext }

export async function fxAccountGetDefaultOwner(portal: TPortal, args: TArgs): Promise<TAccount | null> {
  const stmt = await portal.db.prepare(`
    SELECT accounts.id, accounts.kind, accounts.display_name,
      organization_memberships.role, accounts.is_autogenerated,
      accounts.created_at_ms, accounts.updated_at_ms
    FROM accounts
    INNER JOIN organization_memberships
      ON organization_memberships.account_id = accounts.id
      AND organization_memberships.org_id = ?
      AND organization_memberships.status = 'active'
    WHERE accounts.id = ? AND accounts.status = 'active'
  `)
  const row = await stmt.get(args.tenant.orgId, args.tenant.accountId) as {
    id: string
    kind: TAccount["kind"]
    display_name: string
    role: TAccount["role"]
    is_autogenerated: unknown
    created_at_ms: unknown
    updated_at_ms: unknown
  } | undefined
  if (!row) return null

  return {
    id: row.id,
    kind: row.kind,
    display_name: row.display_name,
    role: row.role,
    is_autogenerated: fnBooleanFromSql(row.is_autogenerated),
    created_at: fnTimestampFromMs(row.created_at_ms),
    updated_at: fnTimestampFromMs(row.updated_at_ms),
  }
}
