import type { Database } from "@tursodatabase/database"
import { DEFAULT_OSS_ACCOUNT_DISPLAY_NAME, DEFAULT_OSS_ACCOUNT_ID } from "../CONSTANTS"

type TPortal = {
  db: Database
}
type TArgs = {}

export async function txAccountEnsureDefaultOwner(portal: TPortal, args: TArgs) {
  await portal.db.exec(`
    INSERT OR IGNORE INTO accounts (id, kind, display_name, role, is_autogenerated)
    VALUES ('${DEFAULT_OSS_ACCOUNT_ID}', 'user', '${DEFAULT_OSS_ACCOUNT_DISPLAY_NAME}', 'owner', true);
  `)
  await portal.db.exec(`
    INSERT OR IGNORE INTO canvas_members (canvas_id, account_id, role, created_at, updated_at)
    SELECT id, '${DEFAULT_OSS_ACCOUNT_ID}', 'owner', datetime('now'), datetime('now') FROM canvas
  `);
}
