import type { Database } from "@tursodatabase/database"
import {
  DEFAULT_OSS_ACCOUNT_DISPLAY_NAME,
  DEFAULT_OSS_ACCOUNT_ID,
  DEFAULT_OSS_ORGANIZATION_ID,
} from "../CONSTANTS"

type TPortal = {
  db: Database
}
type TArgs = {}

export async function txAccountEnsureDefaultOwner(portal: TPortal, args: TArgs) {
  const nowSql = "CAST(unixepoch('subsec') * 1000 AS INTEGER)"
  await (await portal.db.prepare(`
    INSERT OR IGNORE INTO organizations (
      id, slug, name, status, created_at_ms, updated_at_ms
    ) VALUES (?, 'local', 'Local', 'active', ${nowSql}, ${nowSql})
  `)).run(DEFAULT_OSS_ORGANIZATION_ID)
  await (await portal.db.prepare(`
    INSERT OR IGNORE INTO accounts (
      id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms
    ) VALUES (?, 'user', ?, 'active', 1, ${nowSql}, ${nowSql})
  `)).run(DEFAULT_OSS_ACCOUNT_ID, DEFAULT_OSS_ACCOUNT_DISPLAY_NAME)
  await (await portal.db.prepare(`
    INSERT OR IGNORE INTO organization_memberships (
      org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
    ) VALUES (?, ?, 'owner', 'active', 1, ${nowSql}, ${nowSql})
  `)).run(DEFAULT_OSS_ORGANIZATION_ID, DEFAULT_OSS_ACCOUNT_ID)
  await (await portal.db.prepare(`
    INSERT OR IGNORE INTO canvas_members (
      org_id, canvas_id, account_id, role, created_at_ms, updated_at_ms
    )
    SELECT org_id, id, ?, 'owner', ${nowSql}, ${nowSql}
    FROM canvases
    WHERE org_id = ?
  `)).run(DEFAULT_OSS_ACCOUNT_ID, DEFAULT_OSS_ORGANIZATION_ID)
}
