/**
 * @file Public short-lived function runtime contract surface.
 */

export type {
  IExecutorCapacityAllocator,
  IFunctionControlStore,
  IFunctionRegistry,
  IInvocationLeaseAuthority,
  IInvocationStore,
  IResourceWritePermitAuthority,
  ISandboxDriver,
  IScheduler,
  IUsageSink,
} from './interface';
export type {
  TAttemptStatus,
  TExecutorCapacityLease,
  TExecutorCapacityRequest,
  TFailureOwner,
  TFunctionAttempt,
  TFunctionAttemptId,
  TFunctionDefinition,
  TFunctionFailure,
  TFunctionId,
  TFunctionInvocationEnvelope,
  TFunctionInvocationId,
  TFunctionInvocationSubject,
  TFunctionLimits,
  TFunctionMemoryTier,
  TFunctionName,
  TFunctionRetryPolicy,
  TFunctionResolutionPurpose,
  TFunctionRevisionRegistration,
  TInvocationAttemptCompletionRequest,
  TInvocationAttemptCompletionResult,
  TInvocationCancellationResult,
  TInvocationClaimRequest,
  TInvocationClaimResult,
  TInvocationCreateRequest,
  TInvocationCreateResult,
  TInvocationHeartbeatRequest,
  TInvocationIdempotencyScope,
  TInvocationLease,
  TInvocationLeaseMutationResult,
  TInvocationRecord,
  TInvocationRecoveryRequest,
  TInvocationRecoveryResult,
  TInvocationStatus,
  TResourceWritePermit,
  TResourceWritePermitAcquireRequest,
  TResourceWritePermitAcquireResult,
  TResourceWritePermitConsumeRequest,
  TResourceWritePermitConsumeResult,
  TResourceWritePermitStatus,
  TSandboxExecutionResult,
  TSandboxHandle,
  TSandboxStartRequest,
  TTerminalHistoryCompactionRequest,
  TTerminalHistoryCompactionResult,
  TUsageOutboxRecord,
  TUsageOutboxState,
  TUsageMetrics,
  TUsageReceipt,
} from './types';
export {
  fnAttemptCanTransition,
  fnAttemptIsTerminal,
  fnInvocationCanTransition,
  fnInvocationIsTerminal,
} from './core/fn.invocation-state';
export { fnFunctionAttemptShouldRetry, fnFunctionRetryDelayMs } from './core/fn.retry';
export { FUNCTION_PLATFORM_PRE_GUEST_MAX_ATTEMPTS } from './CONSTANTS';
