export type TCompatibilityStatus =
  | "compatible"
  | "adapter"
  | "engine-gap"
  | "release-gap"
  | "validation-gap";

export type TCompatibilityRow = {
  id: string;
  area: string;
  requirement: string;
  status: TCompatibilityStatus;
  owner: "canvas-engine" | "canvas" | "release" | "joint";
  evidence: string;
};

/**
 * The migration contract is intentionally about behavior used by Vibecanvas,
 * not every API exposed by canvas-engine.
 */
export const CANVAS_ENGINE_COMPATIBILITY_MATRIX = [
  {
    id: "package-public-api",
    area: "distribution",
    requirement: "Consume only documented package exports through a filesystem dependency",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "This suite imports the root, /backend, /geometry, and /testing exports.",
  },
  {
    id: "package-release",
    area: "distribution",
    requirement: "Build Vibecanvas in CI/release without a developer-machine absolute path",
    status: "compatible",
    owner: "release",
    evidence: "The exact audited 0.2.1 artifact is vendored behind a repository-relative filepath dependency.",
  },
  {
    id: "lifecycle",
    area: "runtime",
    requirement: "Create, resize, suspend, resume, render, and destroy one browser engine",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Public lifecycle is exercised with a public custom backend seam.",
  },
  {
    id: "scene-layers",
    area: "scene",
    requirement: "Background, world content, and screen/dynamic overlay ordering",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Layer nodes support roles and world/screen coordinate spaces.",
  },
  {
    id: "scene-transactions",
    area: "scene",
    requirement: "Atomic incremental upsert/update/remove/reparent/reorder and snapshots",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Public scene transaction, change set, rollback, and JSON snapshot checks pass.",
  },
  {
    id: "shape2d",
    area: "rendering",
    requirement: "Rectangle, ellipse, and diamond rendering with fill/stroke/opacity",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Rect, ellipse, and polygon nodes cover the current product primitives.",
  },
  {
    id: "shape1d",
    area: "rendering",
    requirement: "Straight/curved lines and arrows with caps and manual points",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Connector nodes support manual paths, curves, and start/end markers.",
  },
  {
    id: "pen",
    area: "rendering",
    requirement: "Pressure-shaped freehand strokes",
    status: "adapter",
    owner: "canvas",
    evidence: "The production pen projector converts perfect-freehand outline points into an engine polygon.",
  },
  {
    id: "text",
    area: "rendering",
    requirement: "Text layout, render, hit geometry, caret geometry, and DOM editing projection",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Text nodes and the public text/editing services cover the current mechanism.",
  },
  {
    id: "inline-text",
    area: "rendering",
    requirement: "Shape-owned inline text moves and transforms with its host",
    status: "adapter",
    owner: "canvas",
    evidence: "The production projector emits one semantic element root with derived shape/text children.",
  },
  {
    id: "images",
    area: "rendering",
    requirement: "URL/base64 image resources, fit/crop, replacement, and failure isolation",
    status: "compatible",
    owner: "joint",
    evidence: "Engine resources cover rendering while ElementService and image ports retain upload, clone, lifecycle-aware delete, and restore policy.",
  },
  {
    id: "image-import-host-commit",
    area: "editor",
    requirement: "Use Cangine clipboard/drop preparation while delegating durable upload and CRDT commit to the application",
    status: "engine-gap",
    owner: "canvas-engine",
    evidence: "The public image controllers commit directly to engine.scene and expose no host commit adapter.",
  },
  {
    id: "grid",
    area: "rendering",
    requirement: "Zoom-aware, world-anchored background grid",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "The production base-scene projection emits a zoom-aware background grid node.",
  },
  {
    id: "groups",
    area: "scene",
    requirement: "Nested grouping, inherited transforms, bounds, clipping, and subtree removal",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Projected group hierarchy plus product group transforms cover nested bounds, transforms, and subtree removal.",
  },
  {
    id: "render-order",
    area: "scene",
    requirement: "Stable persisted z-order and front/back/before/after operations",
    status: "compatible",
    owner: "joint",
    evidence: "Product order commands preserve the persisted string zIndex and project it unchanged to engine orderKey.",
  },
  {
    id: "camera",
    area: "interaction",
    requirement: "Pan, zoom, rotation, resize, fit, and named coordinate conversions",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Round-trip camera conversion is exercised by the contract suite.",
  },
  {
    id: "picking",
    area: "interaction",
    requirement: "Painted hit testing, thin-line tolerance, marquee, and nested hit paths",
    status: "compatible",
    owner: "joint",
    evidence: "Production selection uses indexed semantic hits and the engine marquee session; canvas retains selection-path policy.",
  },
  {
    id: "normalized-input",
    area: "interaction",
    requirement: "Pointer/wheel/key/gesture routing plus click and double-click product semantics",
    status: "compatible",
    owner: "joint",
    evidence: "Engine normalization and its opt-in recognizer validate click sequences; canvas maps recognized hits to product selection and editing policy.",
  },
  {
    id: "semantic-selection",
    area: "interaction",
    requirement: "Nested semantic selection, focus, mode, and selection filtering",
    status: "adapter",
    owner: "canvas",
    evidence: "Engine owns ID affordances while renderer-neutral canvas services retain product selection policy.",
  },
  {
    id: "box-transforms",
    area: "interaction",
    requirement: "Move, resize, rotate, snapping, multi-selection, and ephemeral preview",
    status: "compatible",
    owner: "joint",
    evidence: "Engine proposals/previews drive element, group, and mixed-selection transforms; canvas persists product patches through CRDT/history.",
  },
  {
    id: "point-editing",
    area: "interaction",
    requirement: "Application-defined line vertex and midpoint insertion handles",
    status: "adapter",
    owner: "canvas",
    evidence: "Production line point editing uses hit-tested screen transients, product bindings, active-session dependencies, and CRDT/history commits.",
  },
  {
    id: "transient-projection",
    area: "interaction",
    requirement: "Application-defined transient nodes without durable scene/journal mutation",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "engine.transients provides bounded owner-scoped world/screen forests and optional picking.",
  },
  {
    id: "clone-drag",
    area: "interaction",
    requirement: "Alt-drag clone preview while the source stays in place",
    status: "adapter",
    owner: "canvas",
    evidence: "Product IDs and clone policy stay in canvas while engine.transients.cloneFromScene preserves and remaps the durable render subtree.",
  },
  {
    id: "external-widget-drop",
    area: "interaction",
    requirement: "Sidebar-to-canvas widget placement ghost and asynchronous commit state",
    status: "adapter",
    owner: "canvas",
    evidence: "The production sidebar gesture drives a portal-free widget-frame transient through asynchronous durable handoff.",
  },
  {
    id: "widget-frame",
    area: "widgets",
    requirement: "Header/body/frame controls, resize parts, collapsed state, and content slot",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Widget-frame nodes expose stable part IDs and a portal content rectangle.",
  },
  {
    id: "html-portals",
    area: "widgets",
    requirement: "DOM widget projection through camera/group transforms, clipping, and input gates",
    status: "compatible",
    owner: "joint",
    evidence: "Portal manager owns geometry; canvas owns mount callbacks and widget content.",
  },
  {
    id: "widget-browser-smoke",
    area: "widgets",
    requirement: "Real hosted widget drag/resize/focus/fullscreen behavior in Vibecanvas",
    status: "validation-gap",
    owner: "joint",
    evidence: "A Chromium product smoke covered portal isolation and widget drag, resize, minimize, and fullscreen; the required three-browser, DPR, and input matrix is still absent.",
  },
  {
    id: "automerge-projection",
    area: "collaboration",
    requirement: "Project Automerge elements/groups incrementally without renderer objects",
    status: "adapter",
    owner: "canvas",
    evidence: "The production coordinator incrementally reprojects changed elements and applies semantic node/resource/portal diffs; group changes retain a bounded full-projection fallback.",
  },
  {
    id: "remote-gesture-conflicts",
    area: "collaboration",
    requirement: "Deterministic remote updates while local preview/edit gestures are active",
    status: "validation-gap",
    owner: "canvas",
    evidence: "Dependency-aware cancel/rebase policy and focused tests cover transform and point-edit conflicts; the required real two-client Automerge/browser matrix has not run.",
  },
  {
    id: "history",
    area: "collaboration",
    requirement: "Undo/redo grouping with CRDT writes and transform/tool command labels",
    status: "adapter",
    owner: "canvas",
    evidence: "Production HistoryService retains CRDT product commits for tools, transforms, deletion lifecycle, and coalesced style edits.",
  },
  {
    id: "context-menu",
    area: "product UI",
    requirement: "Canvas/item/selection/connection context menu providers",
    status: "adapter",
    owner: "canvas",
    evidence: "Production providers receive semantic hit IDs/parts and persisted targets while the Solid menu UI remains application-owned.",
  },
  {
    id: "style-menu",
    area: "product UI",
    requirement: "Merged element style schemas, theme tokens, and CRDT style mutations",
    status: "adapter",
    owner: "canvas",
    evidence: "Selection style changes write CRDT, remember selected/active-tool defaults, and coalesce continuous opacity input into one history entry.",
  },
  {
    id: "recorder",
    area: "diagnostics",
    requirement: "Capture raw input plus CRDT operations for product bug replay",
    status: "adapter",
    owner: "canvas",
    evidence: "The product recorder captures normalized input and CRDT operations while the engine journal covers scene commits.",
  },
  {
    id: "runtime-extensions",
    area: "extensibility",
    requirement: "Late plugin element definitions without renderer-native objects",
    status: "adapter",
    owner: "canvas",
    evidence: "Renderer-neutral element definitions register projection, transform, clone, lifecycle, menu, and portal product policy without renderer objects.",
  },
  {
    id: "accessibility",
    area: "product UI",
    requirement: "Canvas accessibility metadata without taking ownership of portal DOM",
    status: "compatible",
    owner: "joint",
    evidence: "Engine projection covers canvas nodes; widgets retain their own DOM accessibility.",
  },
  {
    id: "product-performance",
    area: "performance",
    requirement: "Meet engine gates with Automerge, Solid overlays, and hosted widgets attached",
    status: "validation-gap",
    owner: "joint",
    evidence: "At 5k, isolated one-element projection measured p50 1.580 ms, p95 2.434 ms, and p99 2.490 ms; full 5k/50k/100k browser statistics, combined-pipeline budgets, and clean soak evidence are still missing.",
  },
  {
    id: "managed-service-boundary",
    area: "architecture",
    requirement: "Keep browser rendering independent from managed function/resource topology",
    status: "compatible",
    owner: "canvas",
    evidence: "Engine has no backend/tenant dependency and preserves the browser-only widget host.",
  },
] as const satisfies readonly TCompatibilityRow[];
