export type TCompatibilityStatus =
  | "compatible"
  | "adapter"
  | "engine-gap"
  | "release-gap"
  | "validation-gap";

export type TCompatibilityRow = {
  id: string;
  area: string;
  requirement: string;
  status: TCompatibilityStatus;
  owner: "canvas-engine" | "canvas" | "release" | "joint";
  evidence: string;
};

/**
 * The migration contract is intentionally about behavior used by Vibecanvas,
 * not every API exposed by Konva or canvas-engine.
 */
export const CANVAS_ENGINE_COMPATIBILITY_MATRIX = [
  {
    id: "package-public-api",
    area: "distribution",
    requirement: "Consume only documented package exports through a filesystem dependency",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "This suite imports the root, /backend, /geometry, and /testing exports.",
  },
  {
    id: "package-release",
    area: "distribution",
    requirement: "Build Vibecanvas in CI/release without a developer-machine absolute path",
    status: "release-gap",
    owner: "release",
    evidence: "The packed ESM passes native Node and default Vitest; only the explicitly requested absolute PoC filepath remains machine-specific.",
  },
  {
    id: "lifecycle",
    area: "runtime",
    requirement: "Create, resize, suspend, resume, render, and destroy one browser engine",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Public lifecycle is exercised with a public custom backend seam.",
  },
  {
    id: "scene-layers",
    area: "scene",
    requirement: "Background, world content, and screen/dynamic overlay ordering",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Layer nodes support roles and world/screen coordinate spaces.",
  },
  {
    id: "scene-transactions",
    area: "scene",
    requirement: "Atomic incremental upsert/update/remove/reparent/reorder and snapshots",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Public scene transaction, change set, rollback, and JSON snapshot checks pass.",
  },
  {
    id: "shape2d",
    area: "rendering",
    requirement: "Rectangle, ellipse, and diamond rendering with fill/stroke/opacity",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Rect, ellipse, and polygon nodes cover the current product primitives.",
  },
  {
    id: "shape1d",
    area: "rendering",
    requirement: "Straight/curved lines and arrows with caps and manual points",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Connector nodes support manual paths, curves, and start/end markers.",
  },
  {
    id: "pen",
    area: "rendering",
    requirement: "Pressure-shaped freehand strokes",
    status: "adapter",
    owner: "canvas",
    evidence: "The PoC converts perfect-freehand outline points into an engine polygon.",
  },
  {
    id: "text",
    area: "rendering",
    requirement: "Text layout, render, hit geometry, caret geometry, and DOM editing projection",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Text nodes and the public text/editing services cover the current mechanism.",
  },
  {
    id: "inline-text",
    area: "rendering",
    requirement: "Shape-owned inline text moves and transforms with its host",
    status: "adapter",
    owner: "canvas",
    evidence: "Project one product element to a semantic group with shape and derived text children.",
  },
  {
    id: "images",
    area: "rendering",
    requirement: "URL/base64 image resources, fit/crop, replacement, and failure isolation",
    status: "compatible",
    owner: "joint",
    evidence: "Engine resources/images cover rendering; canvas retains upload/clone/delete policy.",
  },
  {
    id: "grid",
    area: "rendering",
    requirement: "Zoom-aware, world-anchored background grid",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Background grid node replaces the custom Konva grid shape.",
  },
  {
    id: "groups",
    area: "scene",
    requirement: "Nested grouping, inherited transforms, bounds, clipping, and subtree removal",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Group hierarchy and geometry services cover renderer behavior.",
  },
  {
    id: "render-order",
    area: "scene",
    requirement: "Stable persisted z-order and front/back/before/after operations",
    status: "compatible",
    owner: "joint",
    evidence: "Engine order keys and transaction helpers replace node zIndex mutation.",
  },
  {
    id: "camera",
    area: "interaction",
    requirement: "Pan, zoom, rotation, resize, fit, and named coordinate conversions",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Round-trip camera conversion is exercised by the contract suite.",
  },
  {
    id: "picking",
    area: "interaction",
    requirement: "Painted hit testing, thin-line tolerance, marquee, and nested hit paths",
    status: "compatible",
    owner: "joint",
    evidence: "Indexed hit/query services work; canvas chooses semantic tolerance and selection path.",
  },
  {
    id: "normalized-input",
    area: "interaction",
    requirement: "Pointer/wheel/key/gesture routing plus click and double-click product semantics",
    status: "adapter",
    owner: "canvas",
    evidence: "Engine normalizes low-level input; click/double-click remain app-derived DOM gestures.",
  },
  {
    id: "semantic-selection",
    area: "interaction",
    requirement: "Nested semantic selection, focus, mode, and selection filtering",
    status: "adapter",
    owner: "canvas",
    evidence: "Engine owns ID affordances; canvas must retain product selection policy.",
  },
  {
    id: "box-transforms",
    area: "interaction",
    requirement: "Move, resize, rotate, snapping, multi-selection, and ephemeral preview",
    status: "compatible",
    owner: "joint",
    evidence: "Engine proposals/previews cover standard transforms; canvas commits CRDT/history.",
  },
  {
    id: "point-editing",
    area: "interaction",
    requirement: "Application-defined line vertex and midpoint insertion handles",
    status: "adapter",
    owner: "canvas",
    evidence: "Use a hit-tested screen-overlay transient owner with semantic handle IDs.",
  },
  {
    id: "transient-projection",
    area: "interaction",
    requirement: "Application-defined transient nodes without durable scene/journal mutation",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "engine.transients provides bounded owner-scoped world/screen forests and optional picking.",
  },
  {
    id: "clone-drag",
    area: "interaction",
    requirement: "Alt-drag clone preview while the source stays in place",
    status: "adapter",
    owner: "canvas",
    evidence: "Project clone IDs through a world transient owner, then commit the same IDs atomically.",
  },
  {
    id: "external-widget-drop",
    area: "interaction",
    requirement: "Sidebar-to-canvas widget placement ghost and asynchronous commit state",
    status: "adapter",
    owner: "canvas",
    evidence: "Drive a portal-free transient widget-frame from the sidebar DOM pointer session.",
  },
  {
    id: "widget-frame",
    area: "widgets",
    requirement: "Header/body/frame controls, resize parts, collapsed state, and content slot",
    status: "compatible",
    owner: "canvas-engine",
    evidence: "Widget-frame nodes expose stable part IDs and a portal content rectangle.",
  },
  {
    id: "html-portals",
    area: "widgets",
    requirement: "DOM widget projection through camera/group transforms, clipping, and input gates",
    status: "compatible",
    owner: "joint",
    evidence: "Portal manager owns geometry; canvas owns mount callbacks and widget content.",
  },
  {
    id: "widget-browser-smoke",
    area: "widgets",
    requirement: "Real hosted widget drag/resize/focus/fullscreen behavior in Vibecanvas",
    status: "validation-gap",
    owner: "joint",
    evidence: "Engine portal tests exist, but no product host has been run on the new engine yet.",
  },
  {
    id: "automerge-projection",
    area: "collaboration",
    requirement: "Project Automerge elements/groups incrementally without renderer objects",
    status: "adapter",
    owner: "canvas",
    evidence: "The PoC projects a real TCanvasDoc shape into serializable engine nodes/resources.",
  },
  {
    id: "remote-gesture-conflicts",
    area: "collaboration",
    requirement: "Deterministic remote updates while local preview/edit gestures are active",
    status: "validation-gap",
    owner: "canvas",
    evidence: "Requires a product adapter policy and adversarial Automerge/browser tests.",
  },
  {
    id: "history",
    area: "collaboration",
    requirement: "Undo/redo grouping with CRDT writes and transform/tool command labels",
    status: "adapter",
    owner: "canvas",
    evidence: "Engine recorder is a mechanism; current HistoryService/CRDT policy stays app-owned.",
  },
  {
    id: "context-menu",
    area: "product UI",
    requirement: "Canvas/item/selection/connection context menu providers",
    status: "adapter",
    owner: "canvas",
    evidence: "Use hit IDs/parts as input to the existing provider policy and Solid UI.",
  },
  {
    id: "style-menu",
    area: "product UI",
    requirement: "Merged element style schemas, theme tokens, and CRDT style mutations",
    status: "adapter",
    owner: "canvas",
    evidence: "Engine renders resolved styles; canvas/theme services retain token and UI policy.",
  },
  {
    id: "recorder",
    area: "diagnostics",
    requirement: "Capture raw input plus CRDT operations for product bug replay",
    status: "adapter",
    owner: "canvas",
    evidence: "Engine journal covers scene commits; canvas must still record normalized input and CRDT.",
  },
  {
    id: "runtime-extensions",
    area: "extensibility",
    requirement: "Late plugin element definitions without renderer-native objects",
    status: "adapter",
    owner: "canvas",
    evidence: "Replace createNode/toElement callbacks with product-element to engine-node projections.",
  },
  {
    id: "accessibility",
    area: "product UI",
    requirement: "Canvas accessibility metadata without taking ownership of portal DOM",
    status: "compatible",
    owner: "joint",
    evidence: "Engine projection covers canvas nodes; widgets retain their own DOM accessibility.",
  },
  {
    id: "product-performance",
    area: "performance",
    requirement: "Meet engine gates with Automerge, Solid overlays, and hosted widgets attached",
    status: "validation-gap",
    owner: "joint",
    evidence: "Engine benchmarks pass upstream; product-integrated workload has not been measured.",
  },
  {
    id: "managed-service-boundary",
    area: "architecture",
    requirement: "Keep browser rendering independent from managed function/resource topology",
    status: "compatible",
    owner: "canvas",
    evidence: "Engine has no backend/tenant dependency and preserves the browser-only widget host.",
  },
] as const satisfies readonly TCompatibilityRow[];
