import { z } from 'zod';

export const ZJson: z.ZodType<unknown> = z.lazy(() => z.union([z.string(), z.number(), z.boolean(), z.null(), z.array(ZJson), z.record(z.string(), ZJson.optional())]));

export const ZAccountRole = z.enum(['owner', 'admin', 'member', 'viewer']);
export const ZCanvasMemberRole = z.enum(['owner', 'editor', 'viewer']);
export const ZFilesystemMemberRole = z.enum(['owner', 'writer', 'reader']);
export const ZActorStatus = z.enum(['created', 'starting', 'running', 'paused', 'stopping', 'stopped', 'error', 'blocked']);
export const ZActorInboxStatus = z.enum(['queued', 'claimed', 'processed', 'rejected', 'deadLettered']);
export const ZWorkflowRunStatus = z.enum(['starting', 'running', 'suspended', 'completed', 'failed', 'cancelled']);
export const ZWorkflowStepStatus = z.enum(['pending', 'claimed', 'running', 'succeeded', 'failed', 'skipped']);
export const ZWorkflowFunctionKind = z.enum(['fn', 'fx', 'tx']);
export const ZSandboxRunStatus = z.enum(['started', 'succeeded', 'failed', 'timedOut', 'killed']);
export const ZSandboxInstanceStatus = z.enum(['creating', 'running', 'stopped', 'missing', 'failed', 'obsolete']);
export const ZSandboxVolumeStatus = z.enum(['creating', 'ready', 'missing', 'failed', 'obsolete']);

export const ZCanvas = z.object({ id: z.string(), name: z.string(), automerge_url: z.string(), created_at: z.date() });
export const ZCanvasMember = z.object({ canvas_id: z.string(), account_id: z.string(), role: ZCanvasMemberRole, created_at: z.date(), updated_at: z.date() });
export const ZAccount = z.object({ id: z.string(), kind: z.string(), displayName: z.string(), role: ZAccountRole, isAutogenerated: z.boolean(), createdAt: z.date(), updatedAt: z.date() });
export const ZFile = z.object({ id: z.string(), hash: z.string(), format: z.enum(['image/jpeg', 'image/png', 'image/gif', 'image/webp']), base64: z.string(), created_at: z.date() });
export const ZFilesystem = z.object({ id: z.string(), label: z.string(), kind: z.enum(['local', 'remote']), machine_id: z.string(), home_path: z.string().nullable(), created_at: z.date(), updated_at: z.date() });
export const ZFilesystemMember = z.object({ filesystem_id: z.string(), account_id: z.string(), role: ZFilesystemMemberRole, created_at: z.date(), updated_at: z.date() });

export const ZActorDefinition = z.object({ id: z.string(), name: z.string(), slug: z.string(), version: z.number(), description: z.string().nullable(), functions_path: z.string(), machine_config: ZJson, input_schema: ZJson, output_schema: ZJson, server_manifest: ZJson, widget_config: ZJson, created_at: z.date(), updated_at: z.date() });
export const ZActorInstance = z.object({ id: z.string(), workspace_id: z.string().nullable(), canvas_id: z.string(), element_id: z.string(), actor_definition_id: z.string(), display_name: z.string(), status: ZActorStatus, machine_state: z.string(), machine_context: ZJson, workflow_run_id: z.string().nullable(), created_by_system_id: z.string(), created_at: z.date() });
export const ZActorConnection = z.object({ id: z.string(), canvas_id: z.string(), source_element_id: z.string(), source_actor_instance_id: z.string(), target_element_id: z.string(), target_actor_instance_id: z.string(), enabled: z.boolean(), label: z.string().nullable(), event_name_whitelist: ZJson.nullable(), style: ZJson, created_by_system_id: z.string(), created_at: z.date() });
export const ZActorInbox = z.object({ id: z.string(), workspace_id: z.string().nullable(), canvas_id: z.string(), actor_instance_id: z.string(), seq: z.number(), message_id: z.string(), correlation_id: z.string(), causation_id: z.string().nullable(), idempotency_key: z.string(), source_actor_instance_id: z.string().nullable(), source_output_id: z.string().nullable(), connection_id: z.string().nullable(), event_name: z.string(), params: ZJson, status: ZActorInboxStatus, claimed_by_run_id: z.string().nullable(), attempt: z.number(), created_at: z.date(), processed_at: z.date().nullable(), error: ZJson.nullable() });
export const ZActorOutput = z.object({ id: z.string(), workspace_id: z.string().nullable(), canvas_id: z.string(), actor_instance_id: z.string(), seq: z.number(), output_id: z.string(), message_id: z.string(), correlation_id: z.string(), causation_id: z.string().nullable(), output_name: z.string(), payload: ZJson, machine_state: z.string(), created_at: z.date(), workflow_run_id: z.string().nullable(), workflow_step_id: z.string().nullable(), commit_status: z.enum(['staged', 'committed', 'discarded']) });

export const ZWorkflowRun = z.object({ id: z.string(), workspace_id: z.string().nullable(), canvas_id: z.string().nullable(), run_id: z.string(), workflow_kind: z.string(), subject_id: z.string().nullable(), trigger_id: z.string().nullable(), correlation_id: z.string(), causation_id: z.string().nullable(), current_step_index: z.number(), step_count: z.number(), status: ZWorkflowRunStatus, started_at: z.date(), last_heartbeat_at: z.date().nullable(), completed_at: z.date().nullable(), error: ZJson.nullable() });
export const ZWorkflowStep = z.object({ id: z.string(), workflow_run_id: z.string(), sandbox_run_id: z.string().nullable(), step_key: z.string(), step_index: z.number(), phase: z.string().nullable(), function_kind: ZWorkflowFunctionKind, function_name: z.string(), idempotency_key: z.string(), portal_spec: ZJson, args: ZJson, status: ZWorkflowStepStatus, result: ZJson.nullable(), error: ZJson.nullable(), claimed_by_run_id: z.string().nullable(), claimed_at: z.date().nullable(), lease_expires_at: z.date().nullable(), attempt: z.number(), created_at: z.date(), started_at: z.date().nullable(), completed_at: z.date().nullable() });
export const ZSandboxRun = z.object({ id: z.string(), workflow_run_id: z.string().nullable(), workflow_step_id: z.string().nullable(), portal_kind: ZWorkflowFunctionKind, function_name: z.string(), idempotency_key: z.string().nullable(), portal_spec: ZJson, input: ZJson, sandbox_name: z.string(), status: ZSandboxRunStatus, started_at: z.date(), completed_at: z.date().nullable(), stdout_file_id: z.string().nullable(), stderr_file_id: z.string().nullable() });
export const ZSandboxInstance = z.object({ id: z.string(), namespace: z.string(), sandbox_name: z.string(), sandbox_tag: z.string(), image: z.string(), setup_hash: z.string(), status: ZSandboxInstanceStatus, metadata: ZJson, last_error: z.string().nullable(), host_checked_at: z.date().nullable(), created_at: z.date(), updated_at: z.date() });
export const ZSandboxVolume = z.object({ id: z.string(), sandbox_instance_id: z.string(), namespace: z.string(), volume_name: z.string(), volume_tag: z.string(), setup_hash: z.string(), status: ZSandboxVolumeStatus, reusable: z.boolean(), metadata: ZJson, last_error: z.string().nullable(), host_checked_at: z.date().nullable(), created_at: z.date(), updated_at: z.date() });

export type TAccountRole = z.infer<typeof ZAccountRole>;
export type TCanvasMemberRole = z.infer<typeof ZCanvasMemberRole>;
export type TFilesystemMemberRole = z.infer<typeof ZFilesystemMemberRole>;
export type TSandboxInstanceStatus = z.infer<typeof ZSandboxInstanceStatus>;
export type TSandboxVolumeStatus = z.infer<typeof ZSandboxVolumeStatus>;
export type TCanvas = z.infer<typeof ZCanvas>;
export type TCanvasMember = z.infer<typeof ZCanvasMember>;
export type TAccount = z.infer<typeof ZAccount>;
export type TFile = z.infer<typeof ZFile>;
export type TFilesystem = z.infer<typeof ZFilesystem>;
export type TFilesystemMember = z.infer<typeof ZFilesystemMember>;
export type TActorDefinition = z.infer<typeof ZActorDefinition>;
export type TActorInstance = z.infer<typeof ZActorInstance>;
export type TActorConnection = z.infer<typeof ZActorConnection>;
export type TActorInbox = z.infer<typeof ZActorInbox>;
export type TActorOutput = z.infer<typeof ZActorOutput>;
export type TWorkflowRun = z.infer<typeof ZWorkflowRun>;
export type TWorkflowStep = z.infer<typeof ZWorkflowStep>;
export type TSandboxRun = z.infer<typeof ZSandboxRun>;
export type TSandboxInstance = z.infer<typeof ZSandboxInstance>;
export type TSandboxVolume = z.infer<typeof ZSandboxVolume>;
