import { z } from 'zod';
import { MIME_TYPES } from './CONSTANTS';

const RELATIVE_NO_TRAVERSAL_PATH = /^[^\\:]+$/;

const ZManifestPath = z
  .string()
  .min(1)
  .refine((path) => !path.startsWith("/"), "Actor manifest path must be config-relative")
  .refine((path) => RELATIVE_NO_TRAVERSAL_PATH.test(path), "Actor manifest path must be a relative path without backslashes or drive letters")
  .refine((path) => {
    const segments = path.replace(/\\/g, "/").split("/");
    return !segments.some(segment => segment === ".." || segment === "." || segment === "");
  }, "Actor manifest path must not contain traversal segments")

export const ZJson: z.ZodType<unknown> = z.lazy(() => z.union([
  z.string(),
  z.number(),
  z.boolean(),
  z.null(),
  z.array(ZJson),
  z.record(z.string(), ZJson.optional()),
]));

export const ZTimestamp = z.string();
export const ZBlob = z.union([z.instanceof(Uint8Array), z.instanceof(ArrayBuffer)]);
export const ZSqlBoolean = z.union([z.boolean(), z.literal(0), z.literal(1)]).transform(Boolean);

export const ZAccountKind = z.enum(['user', 'service_account', 'system', 'anonymous']);
export const ZAccountRole = z.enum(['member', 'owner', 'admin', 'viewer']);
export const ZCanvasMemberRole = z.enum(['owner', 'editor', 'viewer']);
export const ZMimeType = z.enum(MIME_TYPES);
export const ZActorStatus = z.enum(['created', 'starting', 'running', 'paused', 'stopping', 'stopped', 'error', 'blocked']);
export const ZActorInboxStatus = z.enum(['queued', 'processing', 'processed', 'failed']);

export const ZWidgetErrorPhase = z.enum([
  'definition-discovery',
  'definition-sync',
  'definition-fetch',
  'instance-create',
  'instance-start',
  'instance-persist',
  'snapshot',
  'event-stream',
  'dom-render',
  'sandbox-compile',
  'sandbox-runtime',
]);

export const ZWidgetError = z.object({
  phase: ZWidgetErrorPhase,
  code: z.string(),
  message: z.string(),
  details: ZJson.optional(),
  retryable: z.boolean(),
  occurredAt: ZTimestamp.optional(),
});

export const ZAutomergeRepoData = z.object({
  key: z.string(),
  updated_at: ZTimestamp,
  data: ZBlob,
});

export const ZAccount = z.object({
  id: z.string(),
  kind: ZAccountKind,
  display_name: z.string(),
  role: ZAccountRole,
  is_autogenerated: ZSqlBoolean,
  created_at: ZTimestamp,
  updated_at: ZTimestamp,
});

export const ZCanvas = z.object({
  id: z.string(),
  name: z.string(),
  automerge_url: z.string(),
  created_at: ZTimestamp,
});

export const ZCanvasMember = z.object({
  canvas_id: z.string(),
  account_id: z.string(),
  role: ZCanvasMemberRole,
  created_at: ZTimestamp,
  updated_at: ZTimestamp,
});

export const ZMediaFile = z.object({
  id: z.string(),
  hash: z.string(),
  mime_type: ZMimeType,
  data: ZBlob,
  created_at: ZTimestamp,
});

export const ZFilesystem = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  path: z.string(),
  description: z.string().nullable(),
  created_at: ZTimestamp,
  updated_at: ZTimestamp,
});

export const ZActorDefinition = z.object({
  name: z.string(),
  slug: z.string(),
  url: z.string().nullable(),
  description: z.string().nullable(),
  manifest_path: ZManifestPath,
  created_at: ZTimestamp,
  updated_at: ZTimestamp,
});

export const ZActorInstance = z.object({
  id: z.string(),
  canvas_id: z.string(),
  element_id: z.string(),
  actor_definition_name: z.string(),
  filesystem_id: z.string().nullable(),
  display_name: z.string(),
  status: ZActorStatus,
  machine_state: z.string(),
  machine_context: ZJson,
  last_error: ZWidgetError.nullable(),
  created_at: ZTimestamp,
  updated_at: ZTimestamp,
});

export const ZActorConnection = z.object({
  id: z.string(),
  canvas_id: z.string(),
  source_actor_instance_id: z.string(),
  target_actor_instance_id: z.string(),
  enabled: ZSqlBoolean,
  label: z.string().nullable(),
  msg_name_whitelist: z.string().nullable(),
  style: ZJson,
  created_at: ZTimestamp,
});

export type TJson = z.infer<typeof ZJson>;
export type TKeyValue =
  | { name: string; type: "text"; value: string }
  | { name: string; type: "json"; value: TJson }
  | { name: string; type: "number"; value: number }
  | { name: string; type: "bool"; value: boolean };
export type TTimestamp = z.infer<typeof ZTimestamp>;
export type TBlob = z.infer<typeof ZBlob>;
export type TSqlBoolean = z.infer<typeof ZSqlBoolean>;
export type TAccountKind = z.infer<typeof ZAccountKind>;
export type TAccountRole = z.infer<typeof ZAccountRole>;
export type TCanvasMemberRole = z.infer<typeof ZCanvasMemberRole>;
export type TFileFormat = z.infer<typeof ZMimeType>;
export type TActorStatus = z.infer<typeof ZActorStatus>;
export type TActorInboxStatus = z.infer<typeof ZActorInboxStatus>;
export type TWidgetErrorPhase = z.infer<typeof ZWidgetErrorPhase>;
export type TWidgetError = z.infer<typeof ZWidgetError>;
export type TAutomergeRepoData = z.infer<typeof ZAutomergeRepoData>;
export type TAccount = z.infer<typeof ZAccount>;
export type TCanvas = z.infer<typeof ZCanvas>;
export type TCanvasMember = z.infer<typeof ZCanvasMember>;
export type TMediaFile = z.infer<typeof ZMediaFile>;
export type TFile = TMediaFile;
export type TFilesystem = z.infer<typeof ZFilesystem>;
export type TActorDefinition = z.infer<typeof ZActorDefinition>;
export type TActorInstance = z.infer<typeof ZActorInstance>;
export type TActorConnection = z.infer<typeof ZActorConnection>;
