import { sqliteTable, text, integer, real, blob, index, primaryKey } from 'drizzle-orm/sqlite-core';
import { createSelectSchema } from 'drizzle-zod';
import { sql } from 'drizzle-orm';

/**
 * @llm-hint DRIZZLE JSON DEFAULTS
 *
 * When using text({ mode: "json" }) columns with default values:
 * - WRONG: .default({}) or .default([]) - JS values are NOT JSON-encoded
 * - RIGHT: .default(sql`'{}'`) or .default(sql`'[]'`) - use sql template literal
 *
 * This applies to any non-primitive default (objects, arrays).
 * Primitives like .default(0), .default("str"), .default(false) work fine.
 *
 * Without sql``, drizzle-kit generates broken migrations where the JS value
 * becomes a string literal in INSERT...SELECT statements.
 *
 * @see https://orm.drizzle.team/docs/guides/empty-array-default-value
 */

export type TAccountRole = 'owner' | 'admin' | 'member' | 'viewer';
export type TCanvasMemberRole = 'owner' | 'editor' | 'viewer';
export type TFilesystemMemberRole = 'owner' | 'writer' | 'reader';

/**
 * Vibecanvas auth boundary tables.
 *
 * This schema intentionally does not include Better Auth core tables such as
 * user/session/account/verification. Hosted auth can live outside this repo and
 * sync only stable actor facts into this local authorization model.
 */
export const accounts = sqliteTable('accounts', {
  id: text('id').primaryKey(),
  kind: text('kind', { enum: ['user', 'service_account', 'system', 'anonymous'] }).notNull().default('user'),
  displayName: text('display_name').notNull().unique(),
  role: text('role', { enum: ['owner', 'admin', 'member', 'viewer'] }).$type<TAccountRole>().notNull().default('member'),
  isAutogenerated: integer('is_autogenerated', { mode: 'boolean' }).notNull().default(true),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('accounts_role_idx').on(table.role),
]);

export const filesystems = sqliteTable('filesystems', {
  id: text('id').primaryKey(),
  label: text('label').notNull(),
  kind: text('kind', { enum: ['local', 'remote'] }).notNull(),
  machine_id: text('machine_id').notNull(),
  home_path: text('home_path'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('filesystems_machine_id_idx').on(table.machine_id),
]);

export const filesystem_members = sqliteTable('filesystem_members', {
  filesystem_id: text('filesystem_id').notNull().references(() => filesystems.id, { onDelete: 'cascade' }),
  account_id: text('account_id').notNull().references(() => accounts.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['owner', 'writer', 'reader'] }).$type<TFilesystemMemberRole>().notNull().default('reader'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  primaryKey({ columns: [table.filesystem_id, table.account_id] }),
  index('filesystem_members_account_id_idx').on(table.account_id),
  index('filesystem_members_role_idx').on(table.role),
]);

export const canvas = sqliteTable('canvas', {
  id: text('id').primaryKey(),
  name: text('name').notNull().unique(),
  automerge_url: text('automerge_url').notNull(),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
});

export const canvas_members = sqliteTable('canvas_members', {
  canvas_id: text('canvas_id').notNull().references(() => canvas.id, { onDelete: 'cascade' }),
  account_id: text('account_id').notNull().references(() => accounts.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['owner', 'editor', 'viewer'] }).$type<TCanvasMemberRole>().notNull().default('viewer'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  primaryKey({ columns: [table.canvas_id, table.account_id] }),
  index('canvas_members_account_id_idx').on(table.account_id),
  index('canvas_members_role_idx').on(table.role),
]);

export const ZCanvasSelect = createSelectSchema(canvas);

export const files = sqliteTable('files', {
  id: text('id').primaryKey(),
  hash: text('hash').notNull(),
  format: text('format', { enum: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'] }).notNull(),
  base64: text('base64').notNull(),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('files_hash_idx').on(table.hash),
]);

export const ZFilesSelect = createSelectSchema(files);

export const workflow_runs = sqliteTable('workflow_runs', {
  id: text('id').primaryKey(),
  workspace_id: text('workspace_id'),
  canvas_id: text('canvas_id').references(() => canvas.id, { onDelete: 'set null' }),
  run_id: text('run_id').notNull().unique(),
  workflow_kind: text('workflow_kind').notNull(),
  subject_id: text('subject_id'),
  trigger_id: text('trigger_id'),
  correlation_id: text('correlation_id').notNull(),
  causation_id: text('causation_id'),
  current_step_index: integer('current_step_index').notNull().default(0),
  step_count: integer('step_count').notNull(),
  status: text('status', { enum: ['starting', 'running', 'suspended', 'completed', 'failed', 'cancelled'] }).notNull().default('starting'),
  started_at: integer('started_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  last_heartbeat_at: integer('last_heartbeat_at', { mode: 'timestamp' }),
  completed_at: integer('completed_at', { mode: 'timestamp' }),
  error: text('error', { mode: 'json' }),
}, (table) => [
  index('workflow_runs_status_idx').on(table.status),
  index('workflow_runs_kind_idx').on(table.workflow_kind),
]);

export const workflow_steps = sqliteTable('workflow_steps', {
  id: text('id').primaryKey(),
  workflow_run_id: text('workflow_run_id').notNull().references(() => workflow_runs.id, { onDelete: 'cascade' }),
  sandbox_run_id: text('sandbox_run_id'),
  step_key: text('step_key').notNull(),
  step_index: integer('step_index').notNull(),
  phase: text('phase'),
  function_kind: text('function_kind', { enum: ['fn', 'fx', 'tx'] }).notNull(),
  function_name: text('function_name').notNull(),
  idempotency_key: text('idempotency_key').notNull(),
  portal_spec: text('portal_spec', { mode: 'json' }).notNull().default(sql`'null'`),
  args: text('args', { mode: 'json' }).notNull().default(sql`'null'`),
  status: text('status', { enum: ['pending', 'claimed', 'running', 'succeeded', 'failed', 'skipped'] }).notNull().default('pending'),
  result: text('result', { mode: 'json' }),
  error: text('error', { mode: 'json' }),
  claimed_by_run_id: text('claimed_by_run_id'),
  claimed_at: integer('claimed_at', { mode: 'timestamp' }),
  lease_expires_at: integer('lease_expires_at', { mode: 'timestamp' }),
  attempt: integer('attempt').notNull().default(0),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  started_at: integer('started_at', { mode: 'timestamp' }),
  completed_at: integer('completed_at', { mode: 'timestamp' }),
}, (table) => [
  index('workflow_steps_run_index_idx').on(table.workflow_run_id, table.step_index),
  index('workflow_steps_tx_idempotency_idx').on(table.function_kind, table.idempotency_key),
]);

export const sandbox_runs = sqliteTable('sandbox_runs', {
  id: text('id').primaryKey(),
  workflow_run_id: text('workflow_run_id').references(() => workflow_runs.id, { onDelete: 'set null' }),
  workflow_step_id: text('workflow_step_id').references(() => workflow_steps.id, { onDelete: 'set null' }),
  portal_kind: text('portal_kind', { enum: ['fn', 'fx', 'tx'] }).notNull(),
  function_name: text('function_name').notNull(),
  idempotency_key: text('idempotency_key'),
  portal_spec: text('portal_spec', { mode: 'json' }).notNull().default(sql`'null'`),
  input: text('input', { mode: 'json' }).notNull().default(sql`'null'`),
  sandbox_name: text('sandbox_name').notNull(),
  status: text('status', { enum: ['started', 'succeeded', 'failed', 'timedOut', 'killed'] }).notNull(),
  started_at: integer('started_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  completed_at: integer('completed_at', { mode: 'timestamp' }),
  stdout_file_id: text('stdout_file_id').references(() => files.id, { onDelete: 'set null' }),
  stderr_file_id: text('stderr_file_id').references(() => files.id, { onDelete: 'set null' }),
}, (table) => [
  index('sandbox_runs_step_idx').on(table.workflow_step_id),
]);

export const automerge_repo_data = sqliteTable('automerge_repo_data', {
  key: text('key').notNull().primaryKey(),
  updated_at: text('updated_at').notNull().default(sql`(datetime())`),
  data: blob('data', { mode: 'buffer' }).notNull(),
}, (table) => [
  index('automerge_keys').on(table.key),
  index('automerge_updated_at').on(table.updated_at),
]);

// keep current schema export surface stable for Drizzle consumers
export const unused_real_for_compat = real;
