import { sqliteTable, text, integer, real, blob, index, primaryKey, uniqueIndex } from 'drizzle-orm/sqlite-core';
import { createSelectSchema } from 'drizzle-zod';
import { sql } from 'drizzle-orm';

/**
 * @llm-hint DRIZZLE JSON DEFAULTS
 *
 * When using text({ mode: "json" }) columns with default values:
 * - WRONG: .default({}) or .default([]) - JS values are NOT JSON-encoded
 * - RIGHT: .default(sql`'{}'`) or .default(sql`'[]'`) - use sql template literal
 *
 * This applies to any non-primitive default (objects, arrays).
 * Primitives like .default(0), .default("str"), .default(false) work fine.
 *
 * Without sql``, drizzle-kit generates broken migrations where the JS value
 * becomes a string literal in INSERT...SELECT statements.
 *
 * @see https://orm.drizzle.team/docs/guides/empty-array-default-value
 */

export type TAccountRole = 'owner' | 'admin' | 'member' | 'viewer';
export type TCanvasMemberRole = 'owner' | 'editor' | 'viewer';
export type TFilesystemMemberRole = 'owner' | 'writer' | 'reader';
export type TSandboxInstanceStatus = 'creating' | 'running' | 'stopped' | 'missing' | 'failed' | 'obsolete';
export type TSandboxVolumeStatus = 'creating' | 'ready' | 'missing' | 'failed' | 'obsolete';

/**
 * Vibecanvas auth boundary tables.
 *
 * This schema intentionally does not include Better Auth core tables such as
 * user/session/account/verification. Hosted auth can live outside this repo and
 * sync only stable actor facts into this local authorization model.
 */
export const accounts = sqliteTable('accounts', {
  id: text('id').primaryKey(),
  kind: text('kind', { enum: ['user', 'service_account', 'system', 'anonymous'] }).notNull().default('user'),
  displayName: text('display_name').notNull().unique(),
  role: text('role', { enum: ['owner', 'admin', 'member', 'viewer'] }).$type<TAccountRole>().notNull().default('member'),
  isAutogenerated: integer('is_autogenerated', { mode: 'boolean' }).notNull().default(true),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('accounts_role_idx').on(table.role),
]);

export const filesystems = sqliteTable('filesystems', {
  id: text('id').primaryKey(),
  label: text('label').notNull(),
  kind: text('kind', { enum: ['local', 'remote'] }).notNull(),
  machine_id: text('machine_id').notNull(),
  home_path: text('home_path'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('filesystems_machine_id_idx').on(table.machine_id),
]);

export const filesystem_members = sqliteTable('filesystem_members', {
  filesystem_id: text('filesystem_id').notNull().references(() => filesystems.id, { onDelete: 'cascade' }),
  account_id: text('account_id').notNull().references(() => accounts.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['owner', 'writer', 'reader'] }).$type<TFilesystemMemberRole>().notNull().default('reader'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  primaryKey({ columns: [table.filesystem_id, table.account_id] }),
  index('filesystem_members_account_id_idx').on(table.account_id),
  index('filesystem_members_role_idx').on(table.role),
]);

export const canvas = sqliteTable('canvas', {
  id: text('id').primaryKey(),
  name: text('name').notNull().unique(),
  automerge_url: text('automerge_url').notNull(),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
});

export const canvas_members = sqliteTable('canvas_members', {
  canvas_id: text('canvas_id').notNull().references(() => canvas.id, { onDelete: 'cascade' }),
  account_id: text('account_id').notNull().references(() => accounts.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['owner', 'editor', 'viewer'] }).$type<TCanvasMemberRole>().notNull().default('viewer'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  primaryKey({ columns: [table.canvas_id, table.account_id] }),
  index('canvas_members_account_id_idx').on(table.account_id),
  index('canvas_members_role_idx').on(table.role),
]);

export const ZCanvasSelect = createSelectSchema(canvas);

export const files = sqliteTable('files', {
  id: text('id').primaryKey(),
  hash: text('hash').notNull(),
  format: text('format', { enum: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'] }).notNull(),
  base64: text('base64').notNull(),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('files_hash_idx').on(table.hash),
]);

export const ZFilesSelect = createSelectSchema(files);

export const actor_definitions = sqliteTable('actor_definitions', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  description: text('description'),
  created_by_system_id: text('created_by_system_id').notNull().default('system'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('actor_definitions_slug_idx').on(table.slug),
]);

export const actor_revisions = sqliteTable('actor_revisions', {
  id: text('id').primaryKey(),
  actor_definition_id: text('actor_definition_id').notNull().references(() => actor_definitions.id, { onDelete: 'cascade' }),
  version: integer('version').notNull(),
  machine_schema: text('machine_schema', { mode: 'json' }).notNull().default(sql`'{}'`),
  machine_config: text('machine_config', { mode: 'json' }).notNull().default(sql`'{}'`),
  contract_schema: text('contract_schema', { mode: 'json' }).notNull().default(sql`'{}'`),
  output_schema: text('output_schema', { mode: 'json' }).notNull().default(sql`'{}'`),
  server_manifest: text('server_manifest', { mode: 'json' }).notNull().default(sql`'{}'`),
  ui_manifest: text('ui_manifest', { mode: 'json' }).notNull().default(sql`'{}'`),
  server_bundle_file_id: text('server_bundle_file_id').references(() => files.id, { onDelete: 'set null' }),
  ui_bundle_file_id: text('ui_bundle_file_id').references(() => files.id, { onDelete: 'set null' }),
  source_archive_file_id: text('source_archive_file_id').references(() => files.id, { onDelete: 'set null' }),
  created_by_system_id: text('created_by_system_id').notNull().default('system'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  uniqueIndex('actor_revisions_definition_version_idx').on(table.actor_definition_id, table.version),
]);

export const actor_instances = sqliteTable('actor_instances', {
  id: text('id').primaryKey(),
  workspace_id: text('workspace_id'),
  canvas_id: text('canvas_id').notNull().references(() => canvas.id, { onDelete: 'cascade' }),
  element_id: text('element_id').notNull(),
  actor_definition_id: text('actor_definition_id').notNull().references(() => actor_definitions.id, { onDelete: 'cascade' }),
  actor_revision_id: text('actor_revision_id').notNull().references(() => actor_revisions.id, { onDelete: 'cascade' }),
  display_name: text('display_name').notNull(),
  status: text('status', { enum: ['created', 'starting', 'running', 'paused', 'stopping', 'stopped', 'error', 'blocked'] }).notNull().default('created'),
  machine_state: text('machine_state').notNull(),
  machine_context: text('machine_context', { mode: 'json' }).notNull().default(sql`'{}'`),
  workflow_run_id: text('workflow_run_id').references(() => workflow_runs.id, { onDelete: 'set null' }),
  created_by_system_id: text('created_by_system_id').notNull().default('system'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('actor_instances_canvas_idx').on(table.canvas_id),
  index('actor_instances_status_idx').on(table.status),
]);

export const actor_connections = sqliteTable('actor_connections', {
  id: text('id').primaryKey(),
  canvas_id: text('canvas_id').notNull().references(() => canvas.id, { onDelete: 'cascade' }),
  source_element_id: text('source_element_id').notNull(),
  source_actor_instance_id: text('source_actor_instance_id').notNull().references(() => actor_instances.id, { onDelete: 'cascade' }),
  target_element_id: text('target_element_id').notNull(),
  target_actor_instance_id: text('target_actor_instance_id').notNull().references(() => actor_instances.id, { onDelete: 'cascade' }),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  label: text('label'),
  event_name_whitelist: text('event_name_whitelist', { mode: 'json' }),
  style: text('style', { mode: 'json' }).notNull().default(sql`'{}'`),
  created_by_system_id: text('created_by_system_id').notNull().default('system'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('actor_connections_source_idx').on(table.source_actor_instance_id),
  index('actor_connections_target_idx').on(table.target_actor_instance_id),
]);

export const actor_inbox = sqliteTable('actor_inbox', {
  id: text('id').primaryKey(),
  workspace_id: text('workspace_id'),
  canvas_id: text('canvas_id').notNull().references(() => canvas.id, { onDelete: 'cascade' }),
  actor_instance_id: text('actor_instance_id').notNull().references(() => actor_instances.id, { onDelete: 'cascade' }),
  seq: integer('seq').notNull(),
  message_id: text('message_id').notNull().unique(),
  correlation_id: text('correlation_id').notNull(),
  causation_id: text('causation_id'),
  idempotency_key: text('idempotency_key').notNull().unique(),
  source_actor_instance_id: text('source_actor_instance_id').references(() => actor_instances.id, { onDelete: 'cascade' }),
  source_output_id: text('source_output_id'),
  connection_id: text('connection_id').references(() => actor_connections.id, { onDelete: 'cascade' }),
  event_name: text('event_name').notNull(),
  params: text('params', { mode: 'json' }).notNull().default(sql`'{}'`),
  status: text('status', { enum: ['queued', 'claimed', 'processed', 'rejected', 'deadLettered'] }).notNull().default('queued'),
  claimed_by_run_id: text('claimed_by_run_id'),
  attempt: integer('attempt').notNull().default(0),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  processed_at: integer('processed_at', { mode: 'timestamp' }),
  error: text('error', { mode: 'json' }),
}, (table) => [
  index('actor_inbox_queue_idx').on(table.status, table.created_at),
  index('actor_inbox_actor_seq_idx').on(table.actor_instance_id, table.seq),
]);

export const actor_outputs = sqliteTable('actor_outputs', {
  id: text('id').primaryKey(),
  workspace_id: text('workspace_id'),
  canvas_id: text('canvas_id').notNull().references(() => canvas.id, { onDelete: 'cascade' }),
  actor_instance_id: text('actor_instance_id').notNull().references(() => actor_instances.id, { onDelete: 'cascade' }),
  seq: integer('seq').notNull(),
  output_id: text('output_id').notNull().unique(),
  message_id: text('message_id').notNull(),
  correlation_id: text('correlation_id').notNull(),
  causation_id: text('causation_id'),
  output_name: text('output_name').notNull(),
  payload: text('payload', { mode: 'json' }).notNull().default(sql`'{}'`),
  machine_state: text('machine_state').notNull(),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  workflow_run_id: text('workflow_run_id').references(() => workflow_runs.id, { onDelete: 'set null' }),
  workflow_step_id: text('workflow_step_id').references(() => workflow_steps.id, { onDelete: 'set null' }),
  commit_status: text('commit_status', { enum: ['staged', 'committed', 'discarded'] }).notNull().default('committed'),
}, (table) => [
  index('actor_outputs_actor_seq_idx').on(table.actor_instance_id, table.seq),
  index('actor_outputs_message_idx').on(table.message_id),
]);

export const workflow_runs = sqliteTable('workflow_runs', {
  id: text('id').primaryKey(),
  workspace_id: text('workspace_id'),
  canvas_id: text('canvas_id').references(() => canvas.id, { onDelete: 'set null' }),
  run_id: text('run_id').notNull().unique(),
  workflow_kind: text('workflow_kind').notNull(),
  subject_id: text('subject_id'),
  trigger_id: text('trigger_id'),
  correlation_id: text('correlation_id').notNull(),
  causation_id: text('causation_id'),
  current_step_index: integer('current_step_index').notNull().default(0),
  step_count: integer('step_count').notNull(),
  status: text('status', { enum: ['starting', 'running', 'suspended', 'completed', 'failed', 'cancelled'] }).notNull().default('starting'),
  started_at: integer('started_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  last_heartbeat_at: integer('last_heartbeat_at', { mode: 'timestamp' }),
  completed_at: integer('completed_at', { mode: 'timestamp' }),
  error: text('error', { mode: 'json' }),
}, (table) => [
  index('workflow_runs_status_idx').on(table.status),
  index('workflow_runs_kind_idx').on(table.workflow_kind),
]);

export const workflow_steps = sqliteTable('workflow_steps', {
  id: text('id').primaryKey(),
  workflow_run_id: text('workflow_run_id').notNull().references(() => workflow_runs.id, { onDelete: 'cascade' }),
  sandbox_run_id: text('sandbox_run_id'),
  step_key: text('step_key').notNull(),
  step_index: integer('step_index').notNull(),
  phase: text('phase'),
  function_kind: text('function_kind', { enum: ['fn', 'fx', 'tx'] }).notNull(),
  function_name: text('function_name').notNull(),
  idempotency_key: text('idempotency_key').notNull(),
  portal_spec: text('portal_spec', { mode: 'json' }).notNull().default(sql`'null'`),
  args: text('args', { mode: 'json' }).notNull().default(sql`'null'`),
  status: text('status', { enum: ['pending', 'claimed', 'running', 'succeeded', 'failed', 'skipped'] }).notNull().default('pending'),
  result: text('result', { mode: 'json' }),
  error: text('error', { mode: 'json' }),
  claimed_by_run_id: text('claimed_by_run_id'),
  claimed_at: integer('claimed_at', { mode: 'timestamp' }),
  lease_expires_at: integer('lease_expires_at', { mode: 'timestamp' }),
  attempt: integer('attempt').notNull().default(0),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  started_at: integer('started_at', { mode: 'timestamp' }),
  completed_at: integer('completed_at', { mode: 'timestamp' }),
}, (table) => [
  index('workflow_steps_run_index_idx').on(table.workflow_run_id, table.step_index),
  index('workflow_steps_tx_idempotency_idx').on(table.function_kind, table.idempotency_key),
]);

export const sandbox_runs = sqliteTable('sandbox_runs', {
  id: text('id').primaryKey(),
  workflow_run_id: text('workflow_run_id').references(() => workflow_runs.id, { onDelete: 'set null' }),
  workflow_step_id: text('workflow_step_id').references(() => workflow_steps.id, { onDelete: 'set null' }),
  portal_kind: text('portal_kind', { enum: ['fn', 'fx', 'tx'] }).notNull(),
  function_name: text('function_name').notNull(),
  idempotency_key: text('idempotency_key'),
  portal_spec: text('portal_spec', { mode: 'json' }).notNull().default(sql`'null'`),
  input: text('input', { mode: 'json' }).notNull().default(sql`'null'`),
  sandbox_name: text('sandbox_name').notNull(),
  status: text('status', { enum: ['started', 'succeeded', 'failed', 'timedOut', 'killed'] }).notNull(),
  started_at: integer('started_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  completed_at: integer('completed_at', { mode: 'timestamp' }),
  stdout_file_id: text('stdout_file_id').references(() => files.id, { onDelete: 'set null' }),
  stderr_file_id: text('stderr_file_id').references(() => files.id, { onDelete: 'set null' }),
}, (table) => [
  index('sandbox_runs_step_idx').on(table.workflow_step_id),
]);

export const sandbox_instances = sqliteTable('sandbox_instances', {
  id: text('id').primaryKey(),
  namespace: text('namespace').notNull().default('default'),
  sandbox_name: text('sandbox_name').notNull().unique(),
  sandbox_tag: text('sandbox_tag').notNull(),
  image: text('image').notNull(),
  setup_hash: text('setup_hash').notNull(),
  status: text('status', { enum: ['creating', 'running', 'stopped', 'missing', 'failed', 'obsolete'] }).$type<TSandboxInstanceStatus>().notNull().default('creating'),
  metadata: text('metadata', { mode: 'json' }).notNull().default(sql`'{}'`),
  last_error: text('last_error'),
  host_checked_at: integer('host_checked_at', { mode: 'timestamp' }),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('sandbox_instances_tag_idx').on(table.namespace, table.sandbox_tag, table.status),
  index('sandbox_instances_image_idx').on(table.image),
]);

export const sandbox_volumes = sqliteTable('sandbox_volumes', {
  id: text('id').primaryKey(),
  sandbox_instance_id: text('sandbox_instance_id').notNull().references(() => sandbox_instances.id, { onDelete: 'cascade' }),
  namespace: text('namespace').notNull().default('default'),
  volume_name: text('volume_name').notNull().unique(),
  volume_tag: text('volume_tag').notNull(),
  setup_hash: text('setup_hash').notNull(),
  status: text('status', { enum: ['creating', 'ready', 'missing', 'failed', 'obsolete'] }).$type<TSandboxVolumeStatus>().notNull().default('creating'),
  reusable: integer('reusable', { mode: 'boolean' }).notNull().default(false),
  metadata: text('metadata', { mode: 'json' }).notNull().default(sql`'{}'`),
  last_error: text('last_error'),
  host_checked_at: integer('host_checked_at', { mode: 'timestamp' }),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('sandbox_volumes_instance_idx').on(table.sandbox_instance_id),
  index('sandbox_volumes_tag_idx').on(table.namespace, table.volume_tag, table.status),
]);

export const automerge_repo_data = sqliteTable('automerge_repo_data', {
  key: text('key').notNull().primaryKey(),
  updated_at: text('updated_at').notNull().default(sql`(datetime())`),
  data: blob('data', { mode: 'buffer' }).notNull(),
}, (table) => [
  index('automerge_keys').on(table.key),
  index('automerge_updated_at').on(table.updated_at),
]);

// keep current schema export surface stable for Drizzle consumers
export const unused_real_for_compat = real;
