import { sqliteTable, text, integer, real, blob, index, primaryKey } from 'drizzle-orm/sqlite-core';
import { createSelectSchema } from 'drizzle-zod';
import { sql } from 'drizzle-orm';

/**
 * @llm-hint DRIZZLE JSON DEFAULTS
 *
 * When using text({ mode: "json" }) columns with default values:
 * - WRONG: .default({}) or .default([]) - JS values are NOT JSON-encoded
 * - RIGHT: .default(sql`'{}'`) or .default(sql`'[]'`) - use sql template literal
 *
 * This applies to any non-primitive default (objects, arrays).
 * Primitives like .default(0), .default("str"), .default(false) work fine.
 *
 * Without sql``, drizzle-kit generates broken migrations where the JS value
 * becomes a string literal in INSERT...SELECT statements.
 *
 * @see https://orm.drizzle.team/docs/guides/empty-array-default-value
 */

export type TAccountRole = 'owner' | 'admin' | 'member' | 'viewer';
export type TCanvasMemberRole = 'owner' | 'editor' | 'viewer';
export type TFilesystemMemberRole = 'owner' | 'writer' | 'reader';

/**
 * Vibecanvas auth boundary tables.
 *
 * This schema intentionally does not include Better Auth core tables such as
 * user/session/account/verification. Hosted auth can live outside this repo and
 * sync only stable actor facts into this local authorization model.
 */
export const accounts = sqliteTable('accounts', {
  id: text('id').primaryKey(),
  kind: text('kind', { enum: ['user', 'service_account', 'system', 'anonymous'] }).notNull().default('user'),
  displayName: text('display_name').notNull().unique(),
  role: text('role', { enum: ['owner', 'admin', 'member', 'viewer'] }).$type<TAccountRole>().notNull().default('member'),
  isAutogenerated: integer('is_autogenerated', { mode: 'boolean' }).notNull().default(true),
  createdAt: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updatedAt: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('accounts_role_idx').on(table.role),
]);

export const filesystems = sqliteTable('filesystems', {
  id: text('id').primaryKey(),
  label: text('label').notNull(),
  kind: text('kind', { enum: ['local', 'remote'] }).notNull(),
  machine_id: text('machine_id').notNull(),
  home_path: text('home_path'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('filesystems_machine_id_idx').on(table.machine_id),
]);

export const filesystem_members = sqliteTable('filesystem_members', {
  filesystem_id: text('filesystem_id').notNull().references(() => filesystems.id, { onDelete: 'cascade' }),
  account_id: text('account_id').notNull().references(() => accounts.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['owner', 'writer', 'reader'] }).$type<TFilesystemMemberRole>().notNull().default('reader'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  primaryKey({ columns: [table.filesystem_id, table.account_id] }),
  index('filesystem_members_account_id_idx').on(table.account_id),
  index('filesystem_members_role_idx').on(table.role),
]);

export const canvas = sqliteTable('canvas', {
  id: text('id').primaryKey(),
  name: text('name').notNull().unique(),
  automerge_url: text('automerge_url').notNull(),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
});

export const canvas_members = sqliteTable('canvas_members', {
  canvas_id: text('canvas_id').notNull().references(() => canvas.id, { onDelete: 'cascade' }),
  account_id: text('account_id').notNull().references(() => accounts.id, { onDelete: 'cascade' }),
  role: text('role', { enum: ['owner', 'editor', 'viewer'] }).$type<TCanvasMemberRole>().notNull().default('viewer'),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
  updated_at: integer('updated_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  primaryKey({ columns: [table.canvas_id, table.account_id] }),
  index('canvas_members_account_id_idx').on(table.account_id),
  index('canvas_members_role_idx').on(table.role),
]);

export const ZCanvasSelect = createSelectSchema(canvas);

export const files = sqliteTable('files', {
  id: text('id').primaryKey(),
  hash: text('hash').notNull(),
  format: text('format', { enum: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'] }).notNull(),
  base64: text('base64').notNull(),
  created_at: integer('created_at', { mode: 'timestamp' }).notNull().default(sql`(unixepoch())`),
}, (table) => [
  index('files_hash_idx').on(table.hash),
]);

export const ZFilesSelect = createSelectSchema(files);

export const automerge_repo_data = sqliteTable('automerge_repo_data', {
  key: text('key').notNull().primaryKey(),
  updated_at: text('updated_at').notNull().default(sql`(datetime())`),
  data: blob('data', { mode: 'buffer' }).notNull(),
}, (table) => [
  index('automerge_keys').on(table.key),
  index('automerge_updated_at').on(table.updated_at),
]);

// keep current schema export surface stable for Drizzle consumers
export const unused_real_for_compat = real;
