import { afterEach, describe, expect, test } from 'bun:test';
import { cp, mkdir, mkdtemp, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { DbResource, ResourceStoreService } from '@omnidraw/resource-runtime/local';
import type { TTenantContext } from '@omnidraw/tenant-core';
import type { TWidgetArtifactDescriptor } from '@omnidraw/widget-contract';
import { LocalWidgetArtifactStore } from '@omnidraw/widget-contract/local';
import {
  DATABASE_APPLICATION_ID,
  DATABASE_SCHEMA_VERSION,
  DEFAULT_OSS_ACCOUNT_ID,
  DEFAULT_OSS_CELL_ID,
  DEFAULT_OSS_ORGANIZATION_ID,
} from '../CONSTANTS';
import { DbServiceTurso } from '../DbServiceTurso/DbServiceTurso';
import { fnSerializeDatabaseSchemaFingerprint } from '../DbServiceTurso/fn.database-schema-fingerprint';
import { Database } from '../DbServiceTurso/turso-native';
import { ResourceControlStoreTurso } from '../ResourceControlStoreTurso';
import { EXPECTED_DATABASE_SCHEMA_CONTRACTS } from '../schema/expected-schema';

const RESOURCE_ID = '00000000-0000-4000-8000-000000000070';
const KEY_ID = '00000000-0000-4000-8000-000000000071';
const ARTIFACT_ID = '00000000-0000-4000-8000-000000000072';
const FOREIGN_ORGANIZATION_ID = '00000000-0000-4000-8000-000000000073';
const FOREIGN_ACCOUNT_ID = '00000000-0000-4000-8000-000000000074';
const ARTIFACT_BYTES = new TextEncoder().encode('managed recovery immutable widget artifact');
const temporaryRoots: string[] = [];

const DEFAULT_TENANT: TTenantContext = Object.freeze({
  orgId: DEFAULT_OSS_ORGANIZATION_ID,
  accountId: DEFAULT_OSS_ACCOUNT_ID,
  cellId: DEFAULT_OSS_CELL_ID,
  placementEpoch: 1,
  roles: Object.freeze(['owner']),
  capabilities: Object.freeze(['*']),
  requestId: 'managed-recovery-default',
});

const FOREIGN_TENANT: TTenantContext = Object.freeze({
  orgId: FOREIGN_ORGANIZATION_ID,
  accountId: FOREIGN_ACCOUNT_ID,
  cellId: DEFAULT_OSS_CELL_ID,
  placementEpoch: 1,
  roles: Object.freeze(['owner']),
  capabilities: Object.freeze(['*']),
  requestId: 'managed-recovery-foreign',
});

async function temporaryRoot(label: string): Promise<string> {
  const root = await mkdtemp(path.join(tmpdir(), `omnidraw-${label}-`));
  temporaryRoots.push(root);
  return root;
}

async function waitForPath(targetPath: string, timeoutMs = 10_000): Promise<void> {
  const startedAt = Date.now();
  while (Date.now() - startedAt < timeoutMs) {
    if (await stat(targetPath).then(() => true).catch(() => false)) return;
    await Bun.sleep(10);
  }
  throw new Error(`Timed out waiting for ${targetPath}.`);
}

async function openNative(databasePath: string, readonly = false): Promise<Database> {
  const database = new Database(databasePath, {
    readonly,
    fileMustExist: readonly,
    experimental: ['custom_types', 'triggers', 'index_method', 'generated_columns', 'multiprocess_wal'],
  });
  await database.connect();
  await database.exec('PRAGMA foreign_keys = ON');
  return database;
}

async function databaseSchemaFingerprint(database: Database): Promise<string> {
  const rows = await (await database.prepare(`
    SELECT type, name, tbl_name AS table_name, sql
    FROM sqlite_schema
    WHERE type IN ('table', 'index', 'view', 'trigger')
      AND name NOT GLOB 'sqlite_*'
    ORDER BY type, name, tbl_name
  `)).all() as Array<{
    type: 'index' | 'table' | 'trigger' | 'view';
    name: string;
    table_name: string;
    sql: string | null;
  }>;
  return new Bun.CryptoHasher('sha256')
    .update(fnSerializeDatabaseSchemaFingerprint(rows.map((row) => ({
      type: row.type,
      name: row.name,
      tableName: row.table_name,
      sql: row.sql,
    }))))
    .digest('hex');
}

async function migrationIdentity(database: Database): Promise<readonly Record<string, unknown>[]> {
  return (await (await database.prepare(`
    SELECT version, name, checksum_sha256
    FROM schema_migrations
    ORDER BY version
  `)).all()) as Record<string, unknown>[];
}

async function representativeRows(database: Database): Promise<Readonly<Record<string, readonly unknown[]>>> {
  const queries = {
    accounts: `
      SELECT id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms
      FROM accounts ORDER BY id
    `,
    artifact_references: `
      SELECT org_id, id, kind, digest_sha256, byte_size, retention_state, retain_until_ms, created_at_ms
      FROM artifact_references ORDER BY org_id, id
    `,
    organization_memberships: `
      SELECT org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
      FROM organization_memberships ORDER BY org_id, account_id
    `,
    organizations: `
      SELECT id, slug, name, status, created_at_ms, updated_at_ms
      FROM organizations ORDER BY id
    `,
    resource_catalog: `
      SELECT org_id, id, kind, name, status, last_error_json, created_at_ms, updated_at_ms
      FROM resource_catalog ORDER BY org_id, id
    `,
    resource_encryption_keys: `
      SELECT org_id, id, resource_id, purpose, algorithm,
        hex(key_material) AS key_material_hex, created_at_ms
      FROM resource_encryption_keys ORDER BY org_id, id
    `,
    resource_placements: `
      SELECT org_id, resource_id, cell_id, placement_epoch, relative_path,
        status, created_at_ms, updated_at_ms
      FROM resource_placements ORDER BY org_id, resource_id
    `,
  } as const;
  const rows = await Promise.all(Object.entries(queries).map(async ([name, sql]) => (
    [name, await (await database.prepare(sql)).all()] as const
  )));
  return Object.freeze(Object.fromEntries(rows));
}

async function assertDatabaseIntegrity(database: Database): Promise<void> {
  expect(await (await database.prepare('PRAGMA integrity_check')).all()).toEqual([
    { integrity_check: 'ok' },
  ]);
}

async function assertFileDatabaseIntegrity(
  databasePath: string,
  assertRecovered: (database: Database) => Promise<void>,
): Promise<void> {
  const database = await openNative(databasePath, true);
  try {
    await assertDatabaseIntegrity(database);
    await assertRecovered(database);
  } finally {
    await database.close();
  }
}

afterEach(async () => {
  await Promise.all(temporaryRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe('managed baseline recovery', () => {
  test('WAL recovery retains committed rows and rolls back a killed in-flight writer', async () => {
    const root = await temporaryRoot('wal-recovery');
    const databasePath = path.join(root, 'writer.db');
    const readyPath = path.join(root, 'uncommitted.ready');
    const fixturePath = path.join(import.meta.dir, 'fixtures', 'wal-interrupted-writer.ts');
    const bunExecutable = Bun.which('bun') ?? process.execPath;
    const writer = Bun.spawn([bunExecutable, fixturePath, databasePath, readyPath], {
      cwd: path.resolve(import.meta.dir, '../../../..'),
      stdout: 'pipe',
      stderr: 'pipe',
    });

    try {
      await waitForPath(readyPath);
    } finally {
      writer.kill(9);
      await writer.exited;
    }

    const recovered = await openNative(databasePath);
    try {
      expect(await (await recovered.prepare('PRAGMA integrity_check')).get()).toEqual({ integrity_check: 'ok' });
      expect(await (await recovered.prepare('SELECT id, value FROM recovery_rows ORDER BY id')).all()).toEqual([
        { id: 1, value: 'committed' },
      ]);
    } finally {
      await recovered.close();
    }
  });

  test('whole-home backup and restore preserve schema, artifact, resource data, and tenant isolation', async () => {
    const root = await temporaryRoot('backup-restore');
    const home = path.join(root, 'home');
    const backup = path.join(root, 'backup');
    const restored = path.join(root, 'restored');
    await mkdir(home, { recursive: true });

    const service = new DbServiceTurso({
      databasePath: path.join(home, 'main.db'),
      dataDir: home,
      cacheDir: path.join(home, 'cache'),
      silentMigrations: true,
    });
    let sourceRunning = false;
    try {
      await service.start();
      sourceRunning = true;

    await (await service.db.prepare(`
      INSERT INTO organizations (
        id, slug, name, status, created_at_ms, updated_at_ms
      ) VALUES (?, 'foreign-recovery', 'Foreign recovery tenant', 'active', 1, 1)
    `)).run(FOREIGN_ORGANIZATION_ID);
    await (await service.db.prepare(`
      INSERT INTO accounts (
        id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms
      ) VALUES (?, 'user', 'Foreign recovery owner', 'active', 0, 1, 1)
    `)).run(FOREIGN_ACCOUNT_ID);
    await (await service.db.prepare(`
      INSERT INTO organization_memberships (
        org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
      ) VALUES (?, ?, 'owner', 'active', 1, 1, 1)
    `)).run(FOREIGN_ORGANIZATION_ID, FOREIGN_ACCOUNT_ID);

    const relativeResourcePath = `${RESOURCE_ID}/data.db`;
    await (await service.db.prepare(`
      INSERT INTO resource_catalog (
        org_id, id, kind, name, status, last_error_json, created_at_ms, updated_at_ms
      ) VALUES (?, ?, 'db', 'Recovery database', 'ready', NULL, 1, 1)
    `)).run(DEFAULT_OSS_ORGANIZATION_ID, RESOURCE_ID);
    await (await service.db.prepare(`
      INSERT INTO resource_placements (
        org_id, resource_id, cell_id, placement_epoch, relative_path, status, created_at_ms, updated_at_ms
      ) VALUES (?, ?, ?, 1, ?, 'active', 1, 1)
    `)).run(DEFAULT_OSS_ORGANIZATION_ID, RESOURCE_ID, DEFAULT_OSS_CELL_ID, relativeResourcePath);
    await (await service.db.prepare(`
      INSERT INTO resource_encryption_keys (
        org_id, id, resource_id, purpose, algorithm, key_material, created_at_ms
      ) VALUES (?, ?, ?, 'resource-data', 'aegis-256', ?, 1)
    `)).run(DEFAULT_OSS_ORGANIZATION_ID, KEY_ID, RESOURCE_ID, new Uint8Array(32).fill(7));

    const artifactsRoot = path.join(
      home,
      'organizations',
      DEFAULT_OSS_ORGANIZATION_ID,
      'artifacts',
    );
    const artifactStore = new LocalWidgetArtifactStore({
      orgId: DEFAULT_OSS_ORGANIZATION_ID,
      artifactsRoot,
      createNonce: () => 'managed-recovery-artifact',
    });
    const storedArtifact = await artifactStore.writeArtifact({
      kind: 'ui',
      bytes: ARTIFACT_BYTES,
    });
    const artifactDescriptor: TWidgetArtifactDescriptor = Object.freeze({
      orgId: DEFAULT_OSS_ORGANIZATION_ID,
      id: ARTIFACT_ID,
      kind: 'ui',
      digestSha256: storedArtifact.digestSha256,
      byteSize: storedArtifact.byteSize,
      retentionState: 'pinned',
      retainUntilMs: null,
      createdAtMs: 1,
    });
    await (await service.db.prepare(`
      INSERT INTO artifact_references (
        org_id, id, kind, digest_sha256, byte_size,
        retention_state, retain_until_ms, created_at_ms
      ) VALUES (?, ?, 'ui', ?, ?, 'pinned', NULL, 1)
    `)).run(
      DEFAULT_OSS_ORGANIZATION_ID,
      ARTIFACT_ID,
      storedArtifact.digestSha256,
      storedArtifact.byteSize,
    );

    const expectedSchema = EXPECTED_DATABASE_SCHEMA_CONTRACTS[DATABASE_SCHEMA_VERSION];
    expect(expectedSchema).toBeDefined();
    const sourceSchemaFingerprint = await databaseSchemaFingerprint(service.db);
    expect(sourceSchemaFingerprint).toBe(expectedSchema!.fingerprintSha256);
    const sourceMigrationIdentity = await migrationIdentity(service.db);
    const sourceRepresentativeRows = await representativeRows(service.db);
    await assertDatabaseIntegrity(service.db);
    expect(Buffer.from(await artifactStore.readArtifact(artifactDescriptor))).toEqual(Buffer.from(ARTIFACT_BYTES));
    await service.stop();
    sourceRunning = false;

    const resourceDirectory = path.join(
      home,
      'organizations',
      DEFAULT_OSS_ORGANIZATION_ID,
      'resources',
      RESOURCE_ID,
    );
    await mkdir(resourceDirectory, { recursive: true });
    const resource = await openNative(path.join(resourceDirectory, 'data.db'));
    try {
      await resource.exec(`
        CREATE TABLE notebooks (
          id INTEGER PRIMARY KEY,
          name TEXT NOT NULL
        ) STRICT;
        CREATE TABLE notes (
          id INTEGER PRIMARY KEY,
          notebook_id INTEGER NOT NULL REFERENCES notebooks (id) ON DELETE RESTRICT,
          title TEXT NOT NULL
        ) STRICT;
      `);
      await (await resource.prepare("INSERT INTO notebooks (id, name) VALUES (1, 'Recovery')")).run();
      await (await resource.prepare(
        "INSERT INTO notes (id, notebook_id, title) VALUES (1, 1, 'preserved')",
      )).run();
      await assertDatabaseIntegrity(resource);
    } finally {
      await resource.close();
    }

    await cp(home, backup, { recursive: true, errorOnExist: true });
    await cp(backup, restored, { recursive: true, errorOnExist: true });

    const restoredService = new DbServiceTurso({
      databasePath: path.join(restored, 'main.db'),
      dataDir: restored,
      cacheDir: path.join(restored, 'cache'),
      silentMigrations: true,
    });
    await restoredService.start();
    try {
      expect(await (await restoredService.db.prepare('PRAGMA application_id')).get()).toEqual({
        application_id: DATABASE_APPLICATION_ID,
      });
      expect(await (await restoredService.db.prepare('PRAGMA user_version')).get()).toEqual({
        user_version: DATABASE_SCHEMA_VERSION,
      });
      expect(await (await restoredService.db.prepare('SELECT count(*) AS count FROM schema_migrations')).get())
        .toEqual({ count: DATABASE_SCHEMA_VERSION + 1 });
      expect(await databaseSchemaFingerprint(restoredService.db)).toBe(sourceSchemaFingerprint);
      expect(await migrationIdentity(restoredService.db)).toEqual(sourceMigrationIdentity);
      expect(await representativeRows(restoredService.db)).toEqual(sourceRepresentativeRows);
      await assertDatabaseIntegrity(restoredService.db);
      expect(await (await restoredService.db.prepare(`
        SELECT relative_path FROM resource_placements WHERE org_id = ? AND resource_id = ?
      `)).get(DEFAULT_OSS_ORGANIZATION_ID, RESOURCE_ID)).toEqual({ relative_path: relativeResourcePath });
      expect(await (await restoredService.db.prepare(`
        SELECT length(key_material) AS key_bytes FROM resource_encryption_keys
        WHERE org_id = ? AND resource_id = ?
      `)).get(DEFAULT_OSS_ORGANIZATION_ID, RESOURCE_ID)).toEqual({ key_bytes: 32 });
      expect(await (await restoredService.db.prepare(`
        SELECT id, kind, digest_sha256, byte_size, retention_state
        FROM artifact_references WHERE org_id = ? AND id = ?
      `)).get(DEFAULT_OSS_ORGANIZATION_ID, ARTIFACT_ID)).toEqual({
        id: ARTIFACT_ID,
        kind: 'ui',
        digest_sha256: storedArtifact.digestSha256,
        byte_size: storedArtifact.byteSize,
        retention_state: 'pinned',
      });
      expect(await restoredService.resourceEncryptionKey.get(DEFAULT_TENANT, {
        resourceId: RESOURCE_ID,
      })).toMatchObject({ id: KEY_ID });
      expect(await restoredService.resourceEncryptionKey.get(FOREIGN_TENANT, {
        resourceId: RESOURCE_ID,
      })).toBeNull();

      const restoredDbResource = new DbResource({
        db: restoredService.forTenant(DEFAULT_TENANT),
        dataRoot: path.join(
          restored,
          'organizations',
          DEFAULT_OSS_ORGANIZATION_ID,
          'resources',
        ),
        databaseFactory: (databasePath, options) => new Database(databasePath, options),
      });
      const restoredStore = new ResourceStoreService({
        controlStore: new ResourceControlStoreTurso(restoredService.db),
        providers: [restoredDbResource],
      });
      const recoveryCall = {
        slot: 'recovery',
        resourceId: RESOURCE_ID,
        kind: 'db' as const,
        requirement: {
          slot: 'recovery',
          kind: 'db' as const,
          effect: 'read' as const,
          required: true,
          arbitrarySql: true,
        },
        operation: 'query',
        effect: 'read' as const,
        input: {
          sql: `
            SELECT notes.id, notes.notebook_id, notebooks.name AS notebook, notes.title
            FROM notes INNER JOIN notebooks ON notebooks.id = notes.notebook_id
          `,
        },
      };
      try {
        expect((await restoredStore.call(DEFAULT_TENANT, recoveryCall)).output).toEqual([
          { id: 1n, notebook_id: 1n, notebook: 'Recovery', title: 'preserved' },
        ]);
        await expect(restoredStore.call(FOREIGN_TENANT, recoveryCall)).rejects.toMatchObject({
          code: 'RESOURCE_NOT_FOUND',
        });
      } finally {
        await restoredStore.close();
      }
    } finally {
      await restoredService.stop();
    }
    await assertFileDatabaseIntegrity(path.join(restored, 'main.db'), async (database) => {
      expect(await databaseSchemaFingerprint(database)).toBe(sourceSchemaFingerprint);
      expect(await migrationIdentity(database)).toEqual(sourceMigrationIdentity);
      expect(await representativeRows(database)).toEqual(sourceRepresentativeRows);
    });

    const restoredArtifactStore = new LocalWidgetArtifactStore({
      orgId: DEFAULT_OSS_ORGANIZATION_ID,
      artifactsRoot: path.join(
        restored,
        'organizations',
        DEFAULT_OSS_ORGANIZATION_ID,
        'artifacts',
      ),
    });
    expect(Buffer.from(await restoredArtifactStore.readArtifact(artifactDescriptor)))
      .toEqual(Buffer.from(ARTIFACT_BYTES));
    await expect(restoredArtifactStore.readArtifact({
      ...artifactDescriptor,
      orgId: FOREIGN_ORGANIZATION_ID,
    })).rejects.toMatchObject({ code: 'WIDGET_ARTIFACT_NOT_FOUND' });

    const restoredResource = await openNative(path.join(
      restored,
      'organizations',
      DEFAULT_OSS_ORGANIZATION_ID,
      'resources',
      RESOURCE_ID,
      'data.db',
    ), true);
    try {
      await assertDatabaseIntegrity(restoredResource);
      expect(await (await restoredResource.prepare(`
        SELECT notes.id, notes.notebook_id, notebooks.name AS notebook, notes.title
        FROM notes INNER JOIN notebooks ON notebooks.id = notes.notebook_id
      `)).all()).toEqual([
        { id: 1, notebook_id: 1, notebook: 'Recovery', title: 'preserved' },
      ]);
    } finally {
      await restoredResource.close();
    }
    await assertFileDatabaseIntegrity(path.join(
      restored,
      'organizations',
      DEFAULT_OSS_ORGANIZATION_ID,
      'resources',
      RESOURCE_ID,
      'data.db',
    ), async (database) => {
      expect(await (await database.prepare(`
        SELECT notes.id, notes.notebook_id, notebooks.name AS notebook, notes.title
        FROM notes INNER JOIN notebooks ON notebooks.id = notes.notebook_id
      `)).all()).toEqual([
        { id: 1, notebook_id: 1, notebook: 'Recovery', title: 'preserved' },
      ]);
    });
    } finally {
      if (sourceRunning) await service.stop();
    }
  });
});
