import { afterEach, describe, expect, test } from "bun:test";
import { connect, type Database } from "@tursodatabase/database";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import {
  WIDGET_CAPSULE_ARTIFACT_HASH,
  WIDGET_CAPSULE_BUILD_IDENTITY_JSON,
  WIDGET_CAPSULE_BUILD_POLICY_ID,
  WIDGET_CAPSULE_CAPABILITY_DIGEST,
  WIDGET_CAPSULE_CHANNEL_DIGEST,
  WIDGET_CAPSULE_RUNTIME_JSON,
  widgetManifestV3Json,
} from "../tests/widget-capsule-fixture";

const ORG_A = "00000000-0000-4000-8000-000000000001";
const ACCOUNT_A = "00000000-0000-4000-8000-000000000002";
const ORG_B = "00000000-0000-4000-8000-000000000010";
const ACCOUNT_B = "00000000-0000-4000-8000-000000000011";
const CANVAS_A = "00000000-0000-4000-8000-000000000020";
const CANVAS_B = "00000000-0000-4000-8000-000000000021";
const UI_ARTIFACT_A = "00000000-0000-4000-8000-000000000030";
const SERVER_ARTIFACT_A = "00000000-0000-4000-8000-000000000031";
const DEFINITION_A = "00000000-0000-4000-8000-000000000032";
const REVISION_A = "00000000-0000-4000-8000-000000000033";
const INSTANCE_A = "00000000-0000-4000-8000-000000000034";
const UI_ARTIFACT_B = "00000000-0000-4000-8000-000000000035";
const DEFINITION_B = "00000000-0000-4000-8000-000000000036";
const REVISION_B = "00000000-0000-4000-8000-000000000037";
const RESOURCE_A = "00000000-0000-4000-8000-000000000040";
const RESOURCE_B = "00000000-0000-4000-8000-000000000041";
const DRAFT_A = "00000000-0000-4000-8000-000000000042";
const DRAFT_B = "00000000-0000-4000-8000-000000000043";
const APPLY_A = "00000000-0000-4000-8000-000000000044";
const APPLY_B = "00000000-0000-4000-8000-000000000045";
const INVOCATION_A = "00000000-0000-4000-8000-000000000050";
const ATTEMPT_A = "00000000-0000-4000-8000-000000000051";
const ATTEMPT_B = "00000000-0000-4000-8000-000000000052";

const temporaryRoots: string[] = [];
const databases: Database[] = [];
const digest = (character: string) => character.repeat(64);

async function openBaseline() {
  const root = await mkdtemp(path.join(tmpdir(), "vibecanvas-baseline-constraints-"));
  const db = await connect(path.join(root, "main.db"), {
    experimental: ["custom_types", "generated_columns"] as never,
  });
  temporaryRoots.push(root);
  databases.push(db);
  await db.exec("PRAGMA foreign_keys = ON");
  await db.exec("PRAGMA ignore_check_constraints = 0");
  const migrations = await Promise.all([
    Bun.file(new URL("../migrations/000-initial.sql", import.meta.url)).text(),
    Bun.file(new URL("../migrations/001-widget-revision-sequence.sql", import.meta.url)).text(),
  ]);
  for (const sql of migrations) await db.exec(sql);
  return db;
}

async function run(db: Database, sql: string, ...values: unknown[]) {
  return (await db.prepare(sql)).run(...values);
}

async function expectRejected(action: Promise<unknown>) {
  await expect(action).rejects.toThrow();
}

async function seedSecondTenant(db: Database) {
  await run(
    db,
    "INSERT INTO organizations (id, slug, name, status, created_at_ms, updated_at_ms) VALUES (?, 'second', 'Second', 'active', 0, 0)",
    ORG_B,
  );
  await run(
    db,
    "INSERT INTO accounts (id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms) VALUES (?, 'user', 'Second Owner', 'active', 0, 0, 0)",
    ACCOUNT_B,
  );
  await run(
    db,
    "INSERT INTO organization_memberships (org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms) VALUES (?, ?, 'owner', 'active', 1, 0, 0)",
    ORG_B,
    ACCOUNT_B,
  );
}

async function seedCanvas(db: Database, orgId = ORG_A, accountId = ACCOUNT_A, canvasId = CANVAS_A, name = "Canvas") {
  await run(
    db,
    "INSERT INTO canvases (org_id, id, name, access_policy, created_by_account_id, created_at_ms, updated_at_ms) VALUES (?, ?, ?, 'restricted', ?, 1, 1)",
    orgId,
    canvasId,
    name,
    accountId,
  );
}

async function seedWidget(db: Database) {
  await seedCanvas(db);
  await run(
    db,
    "INSERT INTO artifact_references (org_id, id, kind, digest_sha256, byte_size, retention_state, retain_until_ms, created_at_ms) VALUES (?, ?, 'ui', ?, 10, 'pinned', NULL, 1)",
    ORG_A,
    UI_ARTIFACT_A,
    digest("a"),
  );
  await run(
    db,
    "INSERT INTO artifact_references (org_id, id, kind, digest_sha256, byte_size, retention_state, retain_until_ms, created_at_ms) VALUES (?, ?, 'server', ?, 10, 'pinned', NULL, 1)",
    ORG_A,
    SERVER_ARTIFACT_A,
    digest("b"),
  );
  await run(
    db,
    "INSERT INTO widget_definitions (org_id, id, slug, name, status, active_revision_id, created_at_ms, updated_at_ms) VALUES (?, ?, 'weather', 'Weather', 'draft', NULL, 1, 1)",
    ORG_A,
    DEFINITION_A,
  );
  await run(
    db,
    "INSERT INTO widget_definition_revisions (org_id, id, definition_id, revision_number, ui_artifact_id, ui_artifact_kind, server_artifact_id, server_artifact_kind, manifest_json, contract_digest_sha256, created_at_ms, ui_runtime_json, capsule_artifact_hash, capability_contract_digest_sha256, channel_contract_digest_sha256, capsule_build_identity_json, build_policy_id, server_runtime_abi, contract_format_version) VALUES (?, ?, ?, 1, ?, 'ui', ?, 'server', ?, ?, 1, ?, ?, ?, ?, ?, ?, 'vibecanvas:1', 3)",
    ORG_A,
    REVISION_A,
    DEFINITION_A,
    UI_ARTIFACT_A,
    SERVER_ARTIFACT_A,
    widgetManifestV3Json({
      name: "Weather",
      slug: "weather",
      serverRuntimeAbi: "vibecanvas:1",
    }),
    digest("c"),
    WIDGET_CAPSULE_RUNTIME_JSON,
    WIDGET_CAPSULE_ARTIFACT_HASH,
    WIDGET_CAPSULE_CAPABILITY_DIGEST,
    WIDGET_CAPSULE_CHANNEL_DIGEST,
    WIDGET_CAPSULE_BUILD_IDENTITY_JSON,
    WIDGET_CAPSULE_BUILD_POLICY_ID,
  );
  await run(
    db,
    "UPDATE widget_definitions SET status = 'published', active_revision_id = ?, updated_at_ms = 2 WHERE org_id = ? AND id = ?",
    REVISION_A,
    ORG_A,
    DEFINITION_A,
  );
  await run(
    db,
    "INSERT INTO widget_instances (org_id, id, canvas_id, element_id, definition_id, revision_id, status, created_at_ms, updated_at_ms) VALUES (?, ?, ?, 'element-a', ?, ?, 'active', 2, 2)",
    ORG_A,
    INSTANCE_A,
    CANVAS_A,
    DEFINITION_A,
    REVISION_A,
  );
}

async function seedResource(db: Database, orgId = ORG_A, resourceId = RESOURCE_A, name = "Database") {
  await run(
    db,
    "INSERT INTO resource_catalog (org_id, id, kind, name, status, last_error_json, created_at_ms, updated_at_ms) VALUES (?, ?, 'db', ?, 'ready', NULL, 1, 1)",
    orgId,
    resourceId,
    name,
  );
}

async function seedInvocation(db: Database) {
  await seedWidget(db);
  await run(
    db,
    `INSERT INTO function_invocations (
      org_id, id, account_id, subject_kind, canvas_id,
      widget_definition_id, widget_revision_id, widget_instance_id,
      function_id, function_name, definition_revision, artifact_digest_sha256,
      contract_digest_sha256, runtime_abi, tenant_cell_id, tenant_placement_epoch,
      tenant_request_id, tenant_roles_json, tenant_capabilities_json, input_json,
      input_digest_sha256, idempotency_key, policy_version, priority, timeout_ms,
      memory_tier, output_byte_limit, log_byte_limit, retry_mode, max_attempts,
      initial_backoff_ms, max_backoff_ms, status, result_json, failure_json,
      result_digest_sha256, output_byte_size, log_byte_size, body_state,
      retains_revision, created_at_ms, available_at_ms, deadline_at_ms,
      cancel_requested_at_ms, started_at_ms, finished_at_ms, bodies_compacted_at_ms
    ) VALUES (
      ?, ?, ?, 'widget_instance', ?, ?, ?, ?,
      'refresh', 'refresh', 1, ?, ?, 'test-runtime',
      '00000000-0000-4000-8000-000000000003', 1, 'constraint-test',
      '[]', '[]', '{}', ?, 'refresh-once', 1, 0, 100,
      'small', 100, 100, 'none', 1, 0, 0, 'queued', NULL, NULL, NULL,
      0, 0, 'full', 1, 3, 3, 100, NULL, NULL, NULL, NULL
    )`,
    ORG_A,
    INVOCATION_A,
    ACCOUNT_A,
    CANVAS_A,
    DEFINITION_A,
    REVISION_A,
    INSTANCE_A,
    digest("a"),
    digest("b"),
    digest("1"),
  );
}

async function insertAttempt(
  db: Database,
  id: string,
  attemptNumber: number,
  status = "succeeded",
  leaseEpoch = 1,
) {
  const terminal = ["succeeded", "failed", "cancelled", "timed_out", "lost"].includes(status);
  const starting = status === "starting";
  const failureOwner = status === "succeeded" || status === "running" || status === "starting"
    ? null
    : "platform";
  await run(
    db,
    "INSERT INTO function_attempts (org_id, id, invocation_id, attempt_number, lease_epoch, status, sandbox_driver, memory_tier, active_wall_ms, cpu_ms, allocated_memory_byte_ms, peak_rss_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, output_byte_size, log_byte_size, cold_start, failure_owner, failure_json, billable, created_at_ms, started_at_ms, finished_at_ms) VALUES (?, ?, ?, ?, ?, ?, 'microsandbox', 'small', 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, ?, NULL, 1, 4, ?, ?)",
    ORG_A,
    id,
    INVOCATION_A,
    attemptNumber,
    leaseEpoch,
    status,
    failureOwner,
    starting ? null : 5,
    terminal ? 6 : null,
  );
}

async function completeAttemptWithLeaseFence(db: Database, attemptId: string, leaseEpoch: number) {
  const complete = db.transaction(async () => {
    const attempt = await run(
      db,
      `UPDATE function_attempts
       SET status = 'succeeded', finished_at_ms = 8, failure_owner = NULL
       WHERE org_id = ? AND id = ? AND invocation_id = ?
         AND status = 'running' AND lease_epoch = ?
         AND EXISTS (
           SELECT 1 FROM invocation_leases
           WHERE invocation_leases.org_id = function_attempts.org_id
             AND invocation_leases.invocation_id = function_attempts.invocation_id
             AND invocation_leases.attempt_id = function_attempts.id
             AND invocation_leases.lease_epoch = ?
         )`,
      ORG_A,
      attemptId,
      INVOCATION_A,
      leaseEpoch,
      leaseEpoch,
    ) as { changes: number | bigint };
    if (Number(attempt.changes) !== 1) throw new Error("stale invocation lease");
    const invocation = await run(
      db,
      "UPDATE function_invocations SET status = 'succeeded', finished_at_ms = 8 WHERE org_id = ? AND id = ? AND status = 'running'",
      ORG_A,
      INVOCATION_A,
    ) as { changes: number | bigint };
    if (Number(invocation.changes) !== 1) throw new Error("invocation state conflict");
  });
  await complete();
}

afterEach(async () => {
  await Promise.all(databases.splice(0).map((db) => db.close()));
  await Promise.all(temporaryRoots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

describe("managed schema constraints", () => {
  test("defaults and constrains the durable widget revision sequence", async () => {
    const db = await openBaseline();
    await run(
      db,
      "INSERT INTO widget_definitions (org_id, id, slug, name, status, active_revision_id, created_at_ms, updated_at_ms) VALUES (?, ?, 'sequence', 'Sequence', 'draft', NULL, 1, 1)",
      ORG_A,
      DEFINITION_A,
    );
    expect(await (await db.prepare(`
      SELECT next_revision_number FROM widget_definitions WHERE org_id = ? AND id = ?
    `)).get(ORG_A, DEFINITION_A)).toEqual({ next_revision_number: 1 });
    await expectRejected(run(
      db,
      "UPDATE widget_definitions SET next_revision_number = 0 WHERE org_id = ? AND id = ?",
      ORG_A,
      DEFINITION_A,
    ));
  });

  test("allows arbitrary non-null IDs while rejecting null IDs, bad values, invalid JSON, and bad digests", async () => {
    const db = await openBaseline();

    await run(
      db,
      "INSERT INTO organizations (id, slug, name, status, created_at_ms, updated_at_ms) VALUES ('NOT-A-UUID', 'bad', 'Bad', 'active', 0, 0)",
    );
    expect(await (await db.prepare("SELECT id FROM organizations WHERE slug = 'bad'")).get())
      .toEqual({ id: "NOT-A-UUID" });
    await expectRejected(run(
      db,
      "INSERT INTO key_values (org_id, name, kind, text_value, json_value, number_value, bool_value, blob_value, created_at_ms, updated_at_ms) VALUES (NULL, 'key', 'text', 'value', NULL, NULL, NULL, NULL, 0, 0)",
    ));
    await expectRejected(run(
      db,
      "INSERT INTO key_values (org_id, name, kind, text_value, json_value, number_value, bool_value, blob_value, created_at_ms, updated_at_ms) VALUES (?, 'key', 'bool', NULL, NULL, NULL, 2, NULL, 0, 0)",
      ORG_A,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO key_values (org_id, name, kind, text_value, json_value, number_value, bool_value, blob_value, created_at_ms, updated_at_ms) VALUES (?, 'key', 'json', NULL, 'not-json', NULL, NULL, NULL, 0, 0)",
      ORG_A,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO key_values (org_id, name, kind, text_value, json_value, number_value, bool_value, blob_value, created_at_ms, updated_at_ms) VALUES (?, 'key', 'text', 'value', '{}', NULL, NULL, NULL, 0, 0)",
      ORG_A,
    ));
    await expectRejected(run(db, "UPDATE organizations SET status = 'unknown' WHERE id = ?", ORG_A));
    await expectRejected(run(db, "UPDATE organizations SET updated_at_ms = -1 WHERE id = ?", ORG_A));
    await expectRejected(run(
      db,
      "INSERT INTO artifact_references (org_id, id, kind, digest_sha256, byte_size, retention_state, retain_until_ms, created_at_ms) VALUES (?, ?, 'ui', 'ABC', -1, 'pinned', NULL, 0)",
      ORG_A,
      UI_ARTIFACT_A,
    ));
  });

  test("enforces tenant membership and tenant-qualified uniqueness while allowing same names across organizations", async () => {
    const db = await openBaseline();
    await seedSecondTenant(db);
    await seedCanvas(db, ORG_A, ACCOUNT_A, CANVAS_A, "Shared name");
    await seedCanvas(db, ORG_B, ACCOUNT_B, CANVAS_B, "Shared name");

    await expectRejected(seedCanvas(
      db,
      ORG_A,
      ACCOUNT_A,
      "00000000-0000-4000-8000-000000000022",
      "Shared name",
    ));
    await expectRejected(run(
      db,
      "INSERT INTO canvases (org_id, id, name, access_policy, created_by_account_id, created_at_ms, updated_at_ms) VALUES (?, ?, 'Foreign creator', 'restricted', ?, 1, 1)",
      ORG_A,
      "00000000-0000-4000-8000-000000000023",
      ACCOUNT_B,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO canvas_members (org_id, canvas_id, account_id, role, created_at_ms, updated_at_ms) VALUES (?, ?, ?, 'viewer', 1, 1)",
      ORG_A,
      CANVAS_A,
      ACCOUNT_B,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO canvas_members (org_id, canvas_id, account_id, role, created_at_ms, updated_at_ms) VALUES (?, ?, ?, 'viewer', 1, 1)",
      ORG_B,
      CANVAS_A,
      ACCOUNT_B,
    ));
    expect(await (await db.prepare("SELECT org_id, name FROM canvases ORDER BY org_id")).all()).toEqual([
      { org_id: ORG_A, name: "Shared name" },
      { org_id: ORG_B, name: "Shared name" },
    ]);
  });

  test("pins revisions and artifacts to one definition and organization", async () => {
    const db = await openBaseline();
    await seedWidget(db);
    await seedSecondTenant(db);
    await run(
      db,
      "INSERT INTO artifact_references (org_id, id, kind, digest_sha256, byte_size, retention_state, retain_until_ms, created_at_ms) VALUES (?, ?, 'ui', ?, 10, 'pinned', NULL, 1)",
      ORG_B,
      UI_ARTIFACT_B,
      digest("a"),
    );
    await run(
      db,
      "INSERT INTO widget_definitions (org_id, id, slug, name, status, active_revision_id, created_at_ms, updated_at_ms) VALUES (?, ?, 'other', 'Other', 'draft', NULL, 1, 1)",
      ORG_A,
      DEFINITION_B,
    );
    await run(
      db,
      "INSERT INTO widget_definition_revisions (org_id, id, definition_id, revision_number, ui_artifact_id, ui_artifact_kind, server_artifact_id, server_artifact_kind, manifest_json, contract_digest_sha256, created_at_ms, ui_runtime_json, capsule_artifact_hash, capability_contract_digest_sha256, channel_contract_digest_sha256, capsule_build_identity_json, build_policy_id, server_runtime_abi, contract_format_version) VALUES (?, ?, ?, 1, ?, 'ui', NULL, NULL, ?, ?, 1, ?, ?, ?, ?, ?, ?, NULL, 3)",
      ORG_A,
      REVISION_B,
      DEFINITION_B,
      UI_ARTIFACT_A,
      widgetManifestV3Json({ name: "Other", slug: "other" }),
      digest("d"),
      WIDGET_CAPSULE_RUNTIME_JSON,
      WIDGET_CAPSULE_ARTIFACT_HASH,
      WIDGET_CAPSULE_CAPABILITY_DIGEST,
      WIDGET_CAPSULE_CHANNEL_DIGEST,
      WIDGET_CAPSULE_BUILD_IDENTITY_JSON,
      WIDGET_CAPSULE_BUILD_POLICY_ID,
    );

    await expectRejected(run(
      db,
      "UPDATE widget_definitions SET status = 'published', active_revision_id = ? WHERE org_id = ? AND id = ?",
      REVISION_B,
      ORG_A,
      DEFINITION_A,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO widget_definition_revisions (org_id, id, definition_id, revision_number, ui_artifact_id, ui_artifact_kind, server_artifact_id, server_artifact_kind, manifest_json, contract_digest_sha256, created_at_ms, ui_runtime_json, capsule_artifact_hash, capability_contract_digest_sha256, channel_contract_digest_sha256, capsule_build_identity_json, build_policy_id, server_runtime_abi, contract_format_version) VALUES (?, ?, ?, 2, ?, 'ui', NULL, NULL, ?, ?, 2, ?, ?, ?, ?, ?, ?, NULL, 3)",
      ORG_A,
      "00000000-0000-4000-8000-000000000038",
      DEFINITION_A,
      UI_ARTIFACT_B,
      widgetManifestV3Json({ name: "Weather", slug: "weather" }),
      digest("e"),
      WIDGET_CAPSULE_RUNTIME_JSON,
      WIDGET_CAPSULE_ARTIFACT_HASH,
      WIDGET_CAPSULE_CAPABILITY_DIGEST,
      WIDGET_CAPSULE_CHANNEL_DIGEST,
      WIDGET_CAPSULE_BUILD_IDENTITY_JSON,
      WIDGET_CAPSULE_BUILD_POLICY_ID,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO widget_definition_revisions (org_id, id, definition_id, revision_number, ui_artifact_id, ui_artifact_kind, server_artifact_id, server_artifact_kind, manifest_json, contract_digest_sha256, created_at_ms, ui_runtime_json, capsule_artifact_hash, capability_contract_digest_sha256, channel_contract_digest_sha256, capsule_build_identity_json, build_policy_id, server_runtime_abi, contract_format_version) VALUES (?, ?, ?, 2, ?, 'ui', NULL, NULL, ?, ?, 2, ?, ?, ?, ?, ?, ?, NULL, 3)",
      ORG_A,
      "00000000-0000-4000-8000-000000000039",
      DEFINITION_A,
      SERVER_ARTIFACT_A,
      widgetManifestV3Json({ name: "Weather", slug: "weather" }),
      digest("f"),
      WIDGET_CAPSULE_RUNTIME_JSON,
      WIDGET_CAPSULE_ARTIFACT_HASH,
      WIDGET_CAPSULE_CAPABILITY_DIGEST,
      WIDGET_CAPSULE_CHANNEL_DIGEST,
      WIDGET_CAPSULE_BUILD_IDENTITY_JSON,
      WIDGET_CAPSULE_BUILD_POLICY_ID,
    ));
    expect(await (await db.prepare("SELECT count(*) AS count FROM artifact_references WHERE digest_sha256 = ?")).get(digest("a")))
      .toEqual({ count: 2 });
  });

  test("enforces resource scope, active draft/apply cardinality, encryption size, and safe paths", async () => {
    const db = await openBaseline();
    await seedWidget(db);
    await seedSecondTenant(db);
    await seedResource(db);
    await seedResource(db, ORG_B, RESOURCE_B, "Database");

    await expectRejected(run(
      db,
      "INSERT INTO resource_bindings (org_id, definition_id, revision_id, slot_name, resource_id, resource_kind, is_required, manifest_allow_read, manifest_allow_write, allow_read, allow_write, created_at_ms, updated_at_ms) VALUES (?, ?, ?, 'db', ?, 'db', 1, 1, 0, 1, 1, 1, 1)",
      ORG_A,
      DEFINITION_A,
      REVISION_A,
      RESOURCE_A,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO resource_bindings (org_id, definition_id, revision_id, slot_name, resource_id, resource_kind, is_required, manifest_allow_read, manifest_allow_write, allow_read, allow_write, created_at_ms, updated_at_ms) VALUES (?, ?, ?, 'db', ?, 'db', 1, 1, 1, 1, 0, 1, 1)",
      ORG_A,
      DEFINITION_A,
      REVISION_A,
      RESOURCE_B,
    ));
    await run(
      db,
      "INSERT INTO db_resource_drafts (org_id, id, resource_id, resource_kind, name, status, last_error_json, created_at_ms, updated_at_ms, applied_at_ms) VALUES (?, ?, ?, 'db', 'One', 'editing', NULL, 1, 1, NULL)",
      ORG_A,
      DRAFT_A,
      RESOURCE_A,
    );
    await expectRejected(run(
      db,
      "INSERT INTO db_resource_drafts (org_id, id, resource_id, resource_kind, name, status, last_error_json, created_at_ms, updated_at_ms, applied_at_ms) VALUES (?, ?, ?, 'db', 'Two', 'editing', NULL, 1, 1, NULL)",
      ORG_A,
      DRAFT_B,
      RESOURCE_A,
    ));
    await run(
      db,
      "INSERT INTO db_resource_apply_runs (org_id, id, resource_id, draft_id, source_apply_id, status, last_error_json, backup_retained, created_at_ms, completed_at_ms) VALUES (?, ?, ?, NULL, NULL, 'preparing', NULL, 0, 1, NULL)",
      ORG_A,
      APPLY_A,
      RESOURCE_A,
    );
    await expectRejected(run(
      db,
      "INSERT INTO db_resource_apply_runs (org_id, id, resource_id, draft_id, source_apply_id, status, last_error_json, backup_retained, created_at_ms, completed_at_ms) VALUES (?, ?, ?, NULL, NULL, 'applying', NULL, 0, 1, NULL)",
      ORG_A,
      APPLY_B,
      RESOURCE_A,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO resource_encryption_keys (org_id, id, resource_id, purpose, algorithm, key_material, created_at_ms) VALUES (?, ?, ?, 'resource-data', 'aegis-256', ?, 1)",
      ORG_A,
      "00000000-0000-4000-8000-000000000046",
      RESOURCE_A,
      new Uint8Array(31),
    ));
    for (const relativePath of ["/absolute/data.db", "../escape/data.db", "safe/../escape.db", "C:/data.db", "safe\\data.db"]) {
      await expectRejected(run(
        db,
        "INSERT INTO resource_placements (org_id, resource_id, cell_id, placement_epoch, relative_path, status, created_at_ms, updated_at_ms) VALUES (?, ?, ?, 1, ?, 'active', 1, 1)",
        ORG_A,
        RESOURCE_A,
        "00000000-0000-4000-8000-000000000003",
        relativePath,
      ));
    }
  });

  test("rejects invalid invocation lifecycles, duplicate attempts and idempotency keys", async () => {
    const db = await openBaseline();
    await seedInvocation(db);

    await expectRejected(run(
      db,
      "UPDATE function_invocations SET status = 'succeeded', started_at_ms = 4 WHERE org_id = ? AND id = ?",
      ORG_A,
      INVOCATION_A,
    ));
    await expectRejected(run(
      db,
      "UPDATE function_invocations SET started_at_ms = 4 WHERE org_id = ? AND id = ?",
      ORG_A,
      INVOCATION_A,
    ));
    await expectRejected(run(
      db,
      "UPDATE function_invocations SET output_byte_size = -1 WHERE org_id = ? AND id = ?",
      ORG_A,
      INVOCATION_A,
    ));

    await insertAttempt(db, ATTEMPT_A, 1);
    await expectRejected(insertAttempt(db, ATTEMPT_B, 1));
    await insertAttempt(db, ATTEMPT_B, 2, "succeeded", 2);
    await run(
      db,
      "INSERT INTO invocation_leases (org_id, invocation_id, attempt_id, lease_epoch, worker_id, created_at_ms, heartbeat_at_ms, expires_at_ms) VALUES (?, ?, ?, 1, 'worker-a', 4, 5, 10)",
      ORG_A,
      INVOCATION_A,
      ATTEMPT_A,
    );
    await expectRejected(run(
      db,
      "INSERT INTO invocation_leases (org_id, invocation_id, attempt_id, lease_epoch, worker_id, created_at_ms, heartbeat_at_ms, expires_at_ms) VALUES (?, ?, ?, 2, 'worker-b', 4, 5, 10)",
      ORG_A,
      INVOCATION_A,
      ATTEMPT_B,
    ));

    await run(
      db,
      "INSERT INTO idempotency_records (org_id, id, function_id, scope_kind, canvas_id, widget_instance_id, idempotency_key, request_fingerprint_sha256, widget_definition_id, widget_revision_id, invocation_id, created_at_ms, expires_at_ms) VALUES (?, ?, 'refresh', 'organization', NULL, NULL, 'refresh-once', ?, ?, ?, ?, 3, NULL)",
      ORG_A,
      "00000000-0000-4000-8000-000000000054",
      digest("3"),
      DEFINITION_A,
      REVISION_A,
      INVOCATION_A,
    );
    await expectRejected(run(
      db,
      "INSERT INTO idempotency_records (org_id, id, function_id, scope_kind, canvas_id, widget_instance_id, idempotency_key, request_fingerprint_sha256, widget_definition_id, widget_revision_id, invocation_id, created_at_ms, expires_at_ms) VALUES (?, ?, 'refresh', 'organization', NULL, NULL, 'refresh-once', ?, ?, ?, ?, 3, NULL)",
      ORG_A,
      "00000000-0000-4000-8000-000000000055",
      digest("4"),
      DEFINITION_A,
      REVISION_A,
      INVOCATION_A,
    ));
  });

  test("rejects stale lease-epoch completion and atomically accepts only the current attempt", async () => {
    const db = await openBaseline();
    await seedInvocation(db);
    await run(
      db,
      "UPDATE function_invocations SET status = 'running', started_at_ms = 4 WHERE org_id = ? AND id = ?",
      ORG_A,
      INVOCATION_A,
    );
    await insertAttempt(db, ATTEMPT_A, 1, "running", 1);
    await insertAttempt(db, ATTEMPT_B, 2, "running", 2);
    await run(
      db,
      "INSERT INTO invocation_leases (org_id, invocation_id, attempt_id, lease_epoch, worker_id, created_at_ms, heartbeat_at_ms, expires_at_ms) VALUES (?, ?, ?, 2, 'worker-current', 4, 5, 10)",
      ORG_A,
      INVOCATION_A,
      ATTEMPT_B,
    );

    await expect(completeAttemptWithLeaseFence(db, ATTEMPT_A, 1)).rejects.toThrow("stale invocation lease");
    expect(await (await db.prepare("SELECT status, finished_at_ms FROM function_attempts WHERE org_id = ? AND id = ?")).get(ORG_A, ATTEMPT_A))
      .toEqual({ status: "running", finished_at_ms: null });
    expect(await (await db.prepare("SELECT status, finished_at_ms FROM function_invocations WHERE org_id = ? AND id = ?")).get(ORG_A, INVOCATION_A))
      .toEqual({ status: "running", finished_at_ms: null });

    await completeAttemptWithLeaseFence(db, ATTEMPT_B, 2);
    expect(await (await db.prepare("SELECT status, finished_at_ms FROM function_attempts WHERE org_id = ? AND id = ?")).get(ORG_A, ATTEMPT_B))
      .toEqual({ status: "succeeded", finished_at_ms: 8 });
    expect(await (await db.prepare("SELECT status, finished_at_ms FROM function_invocations WHERE org_id = ? AND id = ?")).get(ORG_A, INVOCATION_A))
      .toEqual({ status: "succeeded", finished_at_ms: 8 });
  });

  test("rejects negative usage and duplicate receipts", async () => {
    const db = await openBaseline();
    await seedInvocation(db);
    await insertAttempt(db, ATTEMPT_A, 1);

    await run(
      db,
      "INSERT INTO usage_outbox (org_id, id, account_id, attempt_id, invocation_id, function_id, definition_revision, sandbox_driver, memory_tier, queued_at_ms, started_at_ms, finished_at_ms, cold_start, resource_id, resource_permit_id, state, outcome, failure_owner, billable, policy_version, active_wall_ms, cpu_ms, allocated_memory_byte_ms, peak_rss_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, created_at_ms, imported_at_ms) VALUES (?, ?, ?, ?, ?, 'refresh', 1, 'microsandbox', 'small', 3, 5, 6, 0, NULL, NULL, 'pending', 'succeeded', NULL, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 6, NULL)",
      ORG_A,
      "00000000-0000-4000-8000-000000000056",
      ACCOUNT_A,
      ATTEMPT_A,
      INVOCATION_A,
    );
    await expectRejected(run(
      db,
      "INSERT INTO usage_outbox (org_id, id, account_id, attempt_id, invocation_id, function_id, definition_revision, sandbox_driver, memory_tier, queued_at_ms, started_at_ms, finished_at_ms, cold_start, resource_id, resource_permit_id, state, outcome, failure_owner, billable, policy_version, active_wall_ms, cpu_ms, allocated_memory_byte_ms, peak_rss_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, created_at_ms, imported_at_ms) VALUES (?, ?, ?, ?, ?, 'refresh', 1, 'microsandbox', 'small', 3, 5, 6, 0, NULL, NULL, 'pending', 'succeeded', NULL, 1, 1, 1, -1, 1, 1, 0, 0, 0, 0, 6, NULL)",
      ORG_A,
      "00000000-0000-4000-8000-000000000057",
      ACCOUNT_A,
      ATTEMPT_B,
      INVOCATION_A,
    ));
    await expectRejected(run(
      db,
      "INSERT INTO usage_outbox (org_id, id, account_id, attempt_id, invocation_id, function_id, definition_revision, sandbox_driver, memory_tier, queued_at_ms, started_at_ms, finished_at_ms, cold_start, resource_id, resource_permit_id, state, outcome, failure_owner, billable, policy_version, active_wall_ms, cpu_ms, allocated_memory_byte_ms, peak_rss_bytes, disk_read_bytes, disk_write_bytes, network_rx_bytes, network_tx_bytes, created_at_ms, imported_at_ms) VALUES (?, ?, ?, ?, ?, 'refresh', 1, 'microsandbox', 'small', 3, 5, 6, 0, NULL, NULL, 'pending', 'succeeded', NULL, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 6, NULL)",
      ORG_A,
      "00000000-0000-4000-8000-000000000058",
      ACCOUNT_A,
      ATTEMPT_A,
      INVOCATION_A,
    ));
  });

  test("allows only validated boundSql metadata on SQL draft changes", async () => {
    const db = await openBaseline();
    await seedResource(db);
    await run(
      db,
      "INSERT INTO db_resource_drafts (org_id, id, resource_id, resource_kind, name, status, last_error_json, created_at_ms, updated_at_ms, applied_at_ms) VALUES (?, ?, ?, 'db', 'Bound SQL', 'editing', NULL, 1, 1, NULL)",
      ORG_A,
      DRAFT_A,
      RESOURCE_A,
    );

    const insert = async (sequence: number, kind: string, operation: string | null) => run(
      db,
      "INSERT INTO db_resource_draft_changes (org_id, draft_id, sequence, kind, operation_json, sql_text, created_at_ms) VALUES (?, ?, ?, ?, ?, 'SELECT 1', 2)",
      ORG_A,
      DRAFT_A,
      sequence,
      kind,
      operation,
    );
    await insert(1, "structure", JSON.stringify({ type: "createTable" }));
    await insert(2, "sql", null);
    await insert(3, "sql", JSON.stringify({ type: "boundSql", parameters: [1, "two", null] }));
    await expectRejected(insert(4, "sql", JSON.stringify({})));
    await expectRejected(insert(4, "sql", JSON.stringify({ type: "other", parameters: [] })));
    await expectRejected(insert(4, "sql", JSON.stringify({ type: "boundSql" })));
    await expectRejected(insert(4, "sql", JSON.stringify({ type: "boundSql", parameters: {} })));
    await expectRejected(insert(4, "structure", null));
    await expectRejected(insert(4, "structure", JSON.stringify([])));
  });
});
