import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { fnFreezeTenantContext, type TTenantContext } from '@vibecanvas/tenant-core';
import {
  DbServiceTurso,
  type TTenantDb,
} from '../DbServiceTurso/DbServiceTurso';
import { TEST_TENANT } from '../tests/tenant.fixture';

const uuid = (value: number) => `10000000-0000-4000-8000-${String(value).padStart(12, '0')}`;
const ORG_B = uuid(1);
const ACCOUNT_B = uuid(2);
const UNKNOWN_ID = uuid(999);

const TENANT_B: TTenantContext = fnFreezeTenantContext({
  orgId: ORG_B,
  accountId: ACCOUNT_B,
  cellId: TEST_TENANT.cellId,
  placementEpoch: TEST_TENANT.placementEpoch,
  roles: ['owner'],
  capabilities: ['*'],
  requestId: 'repository-isolation-b',
});

async function seedSecondTenant(service: DbServiceTurso): Promise<void> {
  const now = 1;
  await (await service.db.prepare(`
    INSERT INTO organizations (id, slug, name, status, created_at_ms, updated_at_ms)
    VALUES (?, 'tenant-b', 'Tenant B', 'active', ?, ?)
  `)).run(ORG_B, now, now);
  await (await service.db.prepare(`
    INSERT INTO accounts (
      id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms
    ) VALUES (?, 'user', 'Tenant B owner', 'active', 0, ?, ?)
  `)).run(ACCOUNT_B, now, now);
  await (await service.db.prepare(`
    INSERT INTO organization_memberships (
      org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
    ) VALUES (?, ?, 'owner', 'active', 1, ?, ?)
  `)).run(ORG_B, ACCOUNT_B, now, now);
}

async function rejectionMessage(action: Promise<unknown>): Promise<string> {
  try {
    await action;
    throw new Error('Expected rejection.');
  } catch (error) {
    return error instanceof Error ? error.message : String(error);
  }
}

describe('tenant-qualified DB repositories', () => {
  let service!: DbServiceTurso;
  let tenantA!: TTenantDb;
  let tenantB!: TTenantDb;

  beforeEach(async () => {
    service = new DbServiceTurso({
      databasePath: ':memory:',
      dataDir: import.meta.dir,
      cacheDir: import.meta.dir,
      silentMigrations: true,
    });
    await service.start();
    await seedSecondTenant(service);
    tenantA = service.forTenant(TEST_TENANT);
    tenantB = service.forTenant(TENANT_B);
  });

  afterEach(async () => {
    await service.stop();
  });

  test('isolates canvas, media, filesystem, key-value, and tool-group collisions', async () => {
    await expect(tenantA.account.getDefaultOwner()).resolves.toMatchObject({ id: TEST_TENANT.accountId });
    await expect(tenantB.account.getDefaultOwner()).resolves.toMatchObject({ id: TENANT_B.accountId });

    const sharedCanvasId = uuid(10);
    const foreignCanvasId = uuid(11);
    await tenantA.canvas.create({
      id: sharedCanvasId,
      name: 'Shared canvas',
      automerge_url: 'automerge:tenant-a-shared',
    });
    await tenantB.canvas.create({
      id: sharedCanvasId,
      name: 'Shared canvas',
      automerge_url: 'automerge:tenant-b-shared',
    });
    await tenantA.canvas.create({
      id: foreignCanvasId,
      name: 'Tenant A only',
      automerge_url: 'automerge:tenant-a-only',
    });

    await expect(tenantA.canvas.findById({ id: sharedCanvasId })).resolves.toMatchObject({
      automerge_url: 'automerge:tenant-a-shared',
    });
    await expect(tenantB.canvas.findById({ id: sharedCanvasId })).resolves.toMatchObject({
      automerge_url: 'automerge:tenant-b-shared',
    });
    await expect(tenantB.canvas.findById({ id: foreignCanvasId })).resolves.toBeNull();
    await expect(tenantB.canvas.findById({ id: UNKNOWN_ID })).resolves.toBeNull();
    await expect(tenantB.canvas.renameById({ id: foreignCanvasId, name: 'Denied' })).resolves.toBeNull();
    await expect(tenantB.canvas.renameById({ id: UNKNOWN_ID, name: 'Denied' })).resolves.toBeNull();
    await expect(tenantB.canvas.deleteById({ id: foreignCanvasId })).resolves.toEqual([]);
    await expect(tenantB.canvas.deleteById({ id: UNKNOWN_ID })).resolves.toEqual([]);
    await expect(tenantA.canvas.findById({ id: foreignCanvasId })).resolves.toMatchObject({
      name: 'Tenant A only',
    });
    expect((await tenantA.canvas.listAll()).map((canvas) => canvas.id).sort()).toEqual([
      foreignCanvasId,
      sharedCanvasId,
    ].sort());
    expect((await tenantB.canvas.listAll()).map((canvas) => canvas.id)).toEqual([sharedCanvasId]);

    const sharedFileId = uuid(20);
    const foreignFileId = uuid(21);
    await tenantA.file.create({
      id: sharedFileId,
      hash: 'hash-a',
      mime_type: 'image/png',
      data: new Uint8Array([1]),
    });
    await tenantB.file.create({
      id: sharedFileId,
      hash: 'hash-b',
      mime_type: 'image/png',
      data: new Uint8Array([2]),
    });
    await tenantA.file.create({
      id: foreignFileId,
      hash: 'foreign-a',
      mime_type: 'image/png',
      data: new Uint8Array([3]),
    });
    await expect(tenantA.file.getById({ id: sharedFileId })).resolves.toMatchObject({ hash: 'hash-a' });
    await expect(tenantB.file.getById({ id: sharedFileId })).resolves.toMatchObject({ hash: 'hash-b' });
    await expect(tenantB.file.getById({ id: foreignFileId })).resolves.toBeNull();
    await expect(tenantB.file.getById({ id: UNKNOWN_ID })).resolves.toBeNull();
    await tenantB.file.deleteById({ id: foreignFileId });
    await tenantB.file.deleteById({ id: UNKNOWN_ID });
    await expect(tenantA.file.getById({ id: foreignFileId })).resolves.not.toBeNull();

    const sharedFilesystemId = uuid(30);
    const foreignFilesystemId = uuid(31);
    await tenantA.filesystem.create({
      id: sharedFilesystemId,
      name: 'Workspace',
      slug: 'workspace',
      path: 'capability:a',
      description: 'A',
    });
    await tenantB.filesystem.create({
      id: sharedFilesystemId,
      name: 'Workspace',
      slug: 'workspace',
      path: 'capability:b',
      description: 'B',
    });
    await tenantA.filesystem.create({
      id: foreignFilesystemId,
      name: 'Private workspace',
      slug: 'private-workspace',
      path: 'capability:private-a',
      description: null,
    });
    await expect(tenantA.filesystem.findById({ id: sharedFilesystemId })).resolves.toMatchObject({ path: 'capability:a' });
    await expect(tenantB.filesystem.findById({ id: sharedFilesystemId })).resolves.toMatchObject({ path: 'capability:b' });
    await expect(tenantB.filesystem.findById({ id: foreignFilesystemId })).resolves.toBeNull();
    await expect(tenantB.filesystem.findById({ id: UNKNOWN_ID })).resolves.toBeNull();
    expect(await tenantB.filesystem.listAll()).toHaveLength(1);

    await tenantA.keyValue.add({ name: 'shared-key', type: 'text', value: 'A' });
    await tenantB.keyValue.add({ name: 'shared-key', type: 'text', value: 'B' });
    await tenantA.keyValue.add({ name: 'foreign-key', type: 'text', value: 'A only' });
    await expect(tenantA.keyValue.get({ name: 'shared-key' })).resolves.toMatchObject({ value: 'A' });
    await expect(tenantB.keyValue.get({ name: 'shared-key' })).resolves.toMatchObject({ value: 'B' });
    await expect(tenantB.keyValue.get({ name: 'foreign-key' })).resolves.toBeNull();
    await expect(tenantB.keyValue.get({ name: 'unknown-key' })).resolves.toBeNull();
    await tenantB.keyValue.remove({ name: 'foreign-key' });
    await tenantB.keyValue.remove({ name: 'unknown-key' });
    await expect(tenantA.keyValue.get({ name: 'foreign-key' })).resolves.not.toBeNull();

    await tenantA.toolGroup.create({ name: 'Shared tools', json: { tenant: 'A' } });
    await tenantB.toolGroup.create({ name: 'Shared tools', json: { tenant: 'B' } });
    await tenantA.toolGroup.create({ name: 'Foreign tools', json: null });
    await expect(tenantA.toolGroup.getByName({ name: 'Shared tools' })).resolves.toMatchObject({ json: { tenant: 'A' } });
    await expect(tenantB.toolGroup.getByName({ name: 'Shared tools' })).resolves.toMatchObject({ json: { tenant: 'B' } });
    await expect(tenantB.toolGroup.getByName({ name: 'Foreign tools' })).resolves.toBeNull();
    await expect(tenantB.toolGroup.getByName({ name: 'Unknown tools' })).resolves.toBeNull();
    await expect(tenantB.toolGroup.remove({ name: 'Foreign tools' })).resolves.toBeNull();
    await expect(tenantB.toolGroup.remove({ name: 'Unknown tools' })).resolves.toBeNull();
    await expect(tenantA.toolGroup.getByName({ name: 'Foreign tools' })).resolves.not.toBeNull();
  });

  test('isolates legacy actors, resource bindings, and encryption keys', async () => {
    const canvasId = uuid(40);
    await tenantA.canvas.create({ id: canvasId, name: 'Actors', automerge_url: 'automerge:actors-a' });
    await tenantB.canvas.create({ id: canvasId, name: 'Actors', automerge_url: 'automerge:actors-b' });
    await tenantA.actor.insertDefinition({
      name: 'Shared actor', slug: 'shared-actor-a', url: null, description: 'A', manifest_path: 'actors/a/vibecanvas.json',
    });
    await tenantB.actor.insertDefinition({
      name: 'Shared actor', slug: 'shared-actor-b', url: null, description: 'B', manifest_path: 'actors/b/vibecanvas.json',
    });
    await tenantA.actor.insertDefinition({
      name: 'Foreign actor', slug: 'foreign-actor', url: null, description: null, manifest_path: 'actors/foreign/vibecanvas.json',
    });
    await expect(tenantA.actor.getDefinition('Shared actor')).resolves.toMatchObject({ description: 'A' });
    await expect(tenantB.actor.getDefinition('Shared actor')).resolves.toMatchObject({ description: 'B' });
    await expect(tenantB.actor.getDefinition('Foreign actor')).resolves.toBeNull();
    await expect(tenantB.actor.getDefinition('Unknown actor')).resolves.toBeNull();
    await tenantB.actor.deleteDefinition('Foreign actor');
    await tenantB.actor.deleteDefinition('Unknown actor');
    await expect(tenantA.actor.getDefinition('Foreign actor')).resolves.not.toBeNull();

    const sharedInstanceId = uuid(41);
    const foreignInstanceId = uuid(42);
    const instance = (id: string, label: string) => ({
      id,
      canvas_id: canvasId,
      element_id: `element-${label}`,
      actor_definition_name: 'Shared actor',
      filesystem_id: null,
      display_name: label,
      status: 'created' as const,
      machine_state: 'idle',
      machine_context: { tenant: label },
    });
    await tenantA.actor.insertInstance(instance(sharedInstanceId, 'A'));
    await tenantB.actor.insertInstance(instance(sharedInstanceId, 'B'));
    await tenantA.actor.insertInstance(instance(foreignInstanceId, 'A-only'));
    await expect(tenantA.actor.getInstanceById(sharedInstanceId)).resolves.toMatchObject({ display_name: 'A' });
    await expect(tenantB.actor.getInstanceById(sharedInstanceId)).resolves.toMatchObject({ display_name: 'B' });
    await expect(tenantB.actor.getInstanceById(foreignInstanceId)).resolves.toBeNull();
    await expect(tenantB.actor.getInstanceById(UNKNOWN_ID)).resolves.toBeNull();
    await expect(tenantB.actor.updateInstanceStatus({ id: foreignInstanceId, status: 'running' })).resolves.toBeNull();
    await expect(tenantB.actor.updateInstanceStatus({ id: UNKNOWN_ID, status: 'running' })).resolves.toBeNull();
    await tenantB.actor.deleteInstance(foreignInstanceId);
    await tenantB.actor.deleteInstance(UNKNOWN_ID);
    await expect(tenantA.actor.getInstanceById(foreignInstanceId)).resolves.not.toBeNull();

    const sharedResourceId = uuid(50);
    const foreignResourceId = uuid(51);
    await tenantA.actorResource.create({ id: sharedResourceId, kind: 'secretStore', name: 'Shared secret', status: 'ready' });
    await tenantB.actorResource.create({ id: sharedResourceId, kind: 'secretStore', name: 'Shared secret', status: 'ready' });
    await tenantA.actorResource.create({ id: foreignResourceId, kind: 'secretStore', name: 'Foreign secret', status: 'ready' });
    await expect(tenantB.actorResource.get({ id: foreignResourceId })).resolves.toBeNull();
    await expect(tenantB.actorResource.get({ id: UNKNOWN_ID })).resolves.toBeNull();
    await expect(tenantB.actorResource.beginDelete({ id: foreignResourceId })).resolves.toBeNull();
    await expect(tenantB.actorResource.beginDelete({ id: UNKNOWN_ID })).resolves.toBeNull();

    await tenantA.actorResource.upsertBinding({
      definitionName: 'Shared actor', slotName: 'secret', resourceId: sharedResourceId, allowRead: true, allowWrite: false,
    });
    await tenantB.actorResource.upsertBinding({
      definitionName: 'Shared actor', slotName: 'secret', resourceId: sharedResourceId, allowRead: true, allowWrite: true,
    });
    await expect(tenantA.actorResource.listBindingsForDefinition({ definitionName: 'Shared actor' }))
      .resolves.toMatchObject([{ allow_write: false }]);
    await expect(tenantB.actorResource.listBindingsForDefinition({ definitionName: 'Shared actor' }))
      .resolves.toMatchObject([{ allow_write: true }]);
    await expect(tenantB.actorResource.listBindingsForDefinition({ definitionName: 'Foreign actor' })).resolves.toEqual([]);
    await expect(tenantB.actorResource.listBindingsForDefinition({ definitionName: 'Unknown actor' })).resolves.toEqual([]);

    const sharedKeyId = uuid(52);
    const keyArgs = (resourceId: string, keyHex: string) => ({
      resourceId,
      keyId: sharedKeyId,
      purpose: 'actor-resource-secret-store',
      algorithm: 'aegis256',
      keyHex,
    });
    await tenantA.actorResourceEncryptionKey.getOrCreate(keyArgs(sharedResourceId, '11'.repeat(32)));
    await tenantB.actorResourceEncryptionKey.getOrCreate(keyArgs(sharedResourceId, '22'.repeat(32)));
    await expect(tenantA.actorResourceEncryptionKey.get({ resourceId: sharedResourceId }))
      .resolves.toMatchObject({ key_hex: '11'.repeat(32) });
    await expect(tenantB.actorResourceEncryptionKey.get({ resourceId: sharedResourceId }))
      .resolves.toMatchObject({ key_hex: '22'.repeat(32) });
    await expect(tenantB.actorResourceEncryptionKey.get({ resourceId: foreignResourceId })).resolves.toBeNull();
    await expect(tenantB.actorResourceEncryptionKey.get({ resourceId: UNKNOWN_ID })).resolves.toBeNull();
    const foreignError = await rejectionMessage(
      tenantB.actorResourceEncryptionKey.getOrCreate(keyArgs(foreignResourceId, '33'.repeat(32))),
    );
    const unknownError = await rejectionMessage(
      tenantB.actorResourceEncryptionKey.getOrCreate(keyArgs(UNKNOWN_ID, '33'.repeat(32))),
    );
    expect(foreignError).toBe(unknownError);
  });

  test('isolates resource draft and apply IDs, lists, and foreign mutations', async () => {
    const sharedResourceId = uuid(60);
    const sharedDraftId = uuid(61);
    const foreignDraftId = uuid(62);
    const sharedApplyId = uuid(63);
    const foreignApplyId = uuid(64);
    await tenantA.actorResource.create({ id: sharedResourceId, kind: 'db', name: 'Shared DB', status: 'ready' });
    await tenantB.actorResource.create({ id: sharedResourceId, kind: 'db', name: 'Shared DB', status: 'ready' });
    await tenantA.dbResource.draft.create({ id: sharedDraftId, resourceId: sharedResourceId, name: 'Draft A' });
    await tenantB.dbResource.draft.create({ id: sharedDraftId, resourceId: sharedResourceId, name: 'Draft B' });
    await tenantA.dbResource.draft.discard({ id: sharedDraftId });
    await tenantA.dbResource.draft.create({ id: foreignDraftId, resourceId: sharedResourceId, name: 'A only draft' });

    await expect(tenantA.dbResource.draft.get({ id: sharedDraftId })).resolves.toMatchObject({ name: 'Draft A' });
    await expect(tenantB.dbResource.draft.get({ id: sharedDraftId })).resolves.toMatchObject({ name: 'Draft B' });
    await expect(tenantB.dbResource.draft.get({ id: foreignDraftId })).resolves.toBeNull();
    await expect(tenantB.dbResource.draft.get({ id: UNKNOWN_ID })).resolves.toBeNull();
    await expect(tenantB.dbResource.draft.rename({ id: foreignDraftId, name: 'Denied' })).resolves.toBeNull();
    await expect(tenantB.dbResource.draft.rename({ id: UNKNOWN_ID, name: 'Denied' })).resolves.toBeNull();
    expect((await tenantA.dbResource.draft.list({ resourceId: sharedResourceId })).map((draft) => draft.id).sort())
      .toEqual([foreignDraftId, sharedDraftId].sort());
    expect((await tenantB.dbResource.draft.list({ resourceId: sharedResourceId })).map((draft) => draft.id))
      .toEqual([sharedDraftId]);

    await tenantA.dbResource.apply.create({ id: sharedApplyId, resourceId: sharedResourceId });
    await tenantB.dbResource.apply.create({ id: sharedApplyId, resourceId: sharedResourceId });
    await tenantA.dbResource.apply.update({ id: sharedApplyId, status: 'succeeded' });
    await tenantA.dbResource.apply.create({ id: foreignApplyId, resourceId: sharedResourceId });
    await expect(tenantA.dbResource.apply.get({ id: sharedApplyId })).resolves.toMatchObject({ resource_id: sharedResourceId });
    await expect(tenantB.dbResource.apply.get({ id: sharedApplyId })).resolves.toMatchObject({ resource_id: sharedResourceId });
    await expect(tenantB.dbResource.apply.get({ id: foreignApplyId })).resolves.toBeNull();
    await expect(tenantB.dbResource.apply.get({ id: UNKNOWN_ID })).resolves.toBeNull();
    await expect(tenantB.dbResource.apply.update({ id: foreignApplyId, status: 'failed' })).resolves.toBeNull();
    await expect(tenantB.dbResource.apply.update({ id: UNKNOWN_ID, status: 'failed' })).resolves.toBeNull();
    await expect(tenantA.dbResource.apply.get({ id: foreignApplyId })).resolves.toMatchObject({ status: 'preparing' });
    expect((await tenantA.dbResource.apply.list({ resourceId: sharedResourceId })).map((apply) => apply.id).sort())
      .toEqual([foreignApplyId, sharedApplyId].sort());
    expect((await tenantB.dbResource.apply.list({ resourceId: sharedResourceId })).map((apply) => apply.id))
      .toEqual([sharedApplyId]);
  });
});
