import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import { fnFreezeTenantContext, type TTenantContext } from '@vibecanvas/tenant-core';
import {
  DbServiceTurso,
  type TTenantDb,
} from '../DbServiceTurso/DbServiceTurso';
import { TEST_TENANT } from '../tests/tenant.fixture';

const uuid = (value: number) => `10000000-0000-4000-8000-${String(value).padStart(12, '0')}`;
const ORG_B = uuid(1);
const ACCOUNT_B = uuid(2);
const UNKNOWN_ID = uuid(999);

const TENANT_B: TTenantContext = fnFreezeTenantContext({
  orgId: ORG_B,
  accountId: ACCOUNT_B,
  cellId: TEST_TENANT.cellId,
  placementEpoch: TEST_TENANT.placementEpoch,
  roles: ['owner'],
  capabilities: ['*'],
  requestId: 'repository-isolation-b',
});

async function seedSecondTenant(service: DbServiceTurso): Promise<void> {
  const now = 1;
  await (await service.db.prepare(`
    INSERT INTO organizations (id, slug, name, status, created_at_ms, updated_at_ms)
    VALUES (?, 'tenant-b', 'Tenant B', 'active', ?, ?)
  `)).run(ORG_B, now, now);
  await (await service.db.prepare(`
    INSERT INTO accounts (
      id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms
    ) VALUES (?, 'user', 'Tenant B owner', 'active', 0, ?, ?)
  `)).run(ACCOUNT_B, now, now);
  await (await service.db.prepare(`
    INSERT INTO organization_memberships (
      org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
    ) VALUES (?, ?, 'owner', 'active', 1, ?, ?)
  `)).run(ORG_B, ACCOUNT_B, now, now);
}

describe('tenant-qualified DB repositories', () => {
  let service!: DbServiceTurso;
  let tenantA!: TTenantDb;
  let tenantB!: TTenantDb;

  beforeEach(async () => {
    service = new DbServiceTurso({
      databasePath: ':memory:',
      dataDir: import.meta.dir,
      cacheDir: import.meta.dir,
      silentMigrations: true,
    });
    await service.start();
    await seedSecondTenant(service);
    tenantA = service.forTenant(TEST_TENANT);
    tenantB = service.forTenant(TENANT_B);
  });

  afterEach(async () => {
    await service.stop();
  });

  test('isolates canvas, media, key-value, and tool-group collisions', async () => {
    await expect(tenantA.account.getDefaultOwner()).resolves.toMatchObject({ id: TEST_TENANT.accountId });
    await expect(tenantB.account.getDefaultOwner()).resolves.toMatchObject({ id: TENANT_B.accountId });

    const sharedCanvasId = uuid(10);
    const foreignCanvasId = uuid(11);
    await tenantA.canvas.create({
      id: sharedCanvasId,
      name: 'Shared canvas',
      automerge_url: 'automerge:tenant-a-shared',
    });
    await tenantB.canvas.create({
      id: sharedCanvasId,
      name: 'Shared canvas',
      automerge_url: 'automerge:tenant-b-shared',
    });
    await tenantA.canvas.create({
      id: foreignCanvasId,
      name: 'Tenant A only',
      automerge_url: 'automerge:tenant-a-only',
    });

    await expect(tenantA.canvas.findById({ id: sharedCanvasId })).resolves.toMatchObject({
      automerge_url: 'automerge:tenant-a-shared',
    });
    await expect(tenantB.canvas.findById({ id: sharedCanvasId })).resolves.toMatchObject({
      automerge_url: 'automerge:tenant-b-shared',
    });
    await expect(tenantB.canvas.findById({ id: foreignCanvasId })).resolves.toBeNull();
    await expect(tenantB.canvas.findById({ id: UNKNOWN_ID })).resolves.toBeNull();
    await expect(tenantB.canvas.renameById({ id: foreignCanvasId, name: 'Denied' })).resolves.toBeNull();
    await expect(tenantB.canvas.renameById({ id: UNKNOWN_ID, name: 'Denied' })).resolves.toBeNull();
    await expect(tenantB.canvas.deleteById({ id: foreignCanvasId })).resolves.toEqual([]);
    await expect(tenantB.canvas.deleteById({ id: UNKNOWN_ID })).resolves.toEqual([]);
    await expect(tenantA.canvas.findById({ id: foreignCanvasId })).resolves.toMatchObject({
      name: 'Tenant A only',
    });
    expect((await tenantA.canvas.listAll()).map((canvas) => canvas.id).sort()).toEqual([
      foreignCanvasId,
      sharedCanvasId,
    ].sort());
    expect((await tenantB.canvas.listAll()).map((canvas) => canvas.id)).toEqual([sharedCanvasId]);

    const sharedFileId = uuid(20);
    const foreignFileId = uuid(21);
    await tenantA.file.create({
      id: sharedFileId,
      hash: 'hash-a',
      mime_type: 'image/png',
      data: new Uint8Array([1]),
    });
    await tenantB.file.create({
      id: sharedFileId,
      hash: 'hash-b',
      mime_type: 'image/png',
      data: new Uint8Array([2]),
    });
    await tenantA.file.create({
      id: foreignFileId,
      hash: 'foreign-a',
      mime_type: 'image/png',
      data: new Uint8Array([3]),
    });
    await expect(tenantA.file.getById({ id: sharedFileId })).resolves.toMatchObject({ hash: 'hash-a' });
    await expect(tenantB.file.getById({ id: sharedFileId })).resolves.toMatchObject({ hash: 'hash-b' });
    await expect(tenantB.file.getById({ id: foreignFileId })).resolves.toBeNull();
    await expect(tenantB.file.getById({ id: UNKNOWN_ID })).resolves.toBeNull();
    await tenantB.file.deleteById({ id: foreignFileId });
    await tenantB.file.deleteById({ id: UNKNOWN_ID });
    await expect(tenantA.file.getById({ id: foreignFileId })).resolves.not.toBeNull();

    await tenantA.keyValue.add({ name: 'shared-key', type: 'text', value: 'A' });
    await tenantB.keyValue.add({ name: 'shared-key', type: 'text', value: 'B' });
    await tenantA.keyValue.add({ name: 'foreign-key', type: 'text', value: 'A only' });
    await expect(tenantA.keyValue.get({ name: 'shared-key' })).resolves.toMatchObject({ value: 'A' });
    await expect(tenantB.keyValue.get({ name: 'shared-key' })).resolves.toMatchObject({ value: 'B' });
    await expect(tenantB.keyValue.get({ name: 'foreign-key' })).resolves.toBeNull();
    await expect(tenantB.keyValue.get({ name: 'unknown-key' })).resolves.toBeNull();
    await tenantB.keyValue.remove({ name: 'foreign-key' });
    await tenantB.keyValue.remove({ name: 'unknown-key' });
    await expect(tenantA.keyValue.get({ name: 'foreign-key' })).resolves.not.toBeNull();

    await tenantA.toolGroup.create({ name: 'Shared tools', json: { tenant: 'A' } });
    await tenantB.toolGroup.create({ name: 'Shared tools', json: { tenant: 'B' } });
    await tenantA.toolGroup.create({ name: 'Foreign tools', json: null });
    await expect(tenantA.toolGroup.getByName({ name: 'Shared tools' })).resolves.toMatchObject({ json: { tenant: 'A' } });
    await expect(tenantB.toolGroup.getByName({ name: 'Shared tools' })).resolves.toMatchObject({ json: { tenant: 'B' } });
    await expect(tenantB.toolGroup.getByName({ name: 'Foreign tools' })).resolves.toBeNull();
    await expect(tenantB.toolGroup.getByName({ name: 'Unknown tools' })).resolves.toBeNull();
    await expect(tenantB.toolGroup.remove({ name: 'Foreign tools' })).resolves.toBeNull();
    await expect(tenantB.toolGroup.remove({ name: 'Unknown tools' })).resolves.toBeNull();
    await expect(tenantA.toolGroup.getByName({ name: 'Foreign tools' })).resolves.not.toBeNull();
  });

  test('isolates resource draft and apply IDs, lists, and foreign mutations', async () => {
    const sharedResourceId = uuid(60);
    const sharedDraftId = uuid(61);
    const foreignDraftId = uuid(62);
    const sharedApplyId = uuid(63);
    const foreignApplyId = uuid(64);
    for (const tenant of [TEST_TENANT, TENANT_B]) {
      await (await service.db.prepare(`
        INSERT INTO resource_catalog (
          org_id, id, kind, name, status, last_error_json, created_at_ms, updated_at_ms
        ) VALUES (?, ?, 'db', 'Shared DB', 'ready', NULL, 1, 1)
      `)).run(tenant.orgId, sharedResourceId);
    }
    await tenantA.dbResource.draft.create({ id: sharedDraftId, resourceId: sharedResourceId, name: 'Draft A' });
    await tenantB.dbResource.draft.create({ id: sharedDraftId, resourceId: sharedResourceId, name: 'Draft B' });
    await tenantA.dbResource.draft.discard({ id: sharedDraftId });
    await tenantA.dbResource.draft.create({ id: foreignDraftId, resourceId: sharedResourceId, name: 'A only draft' });

    await expect(tenantA.dbResource.draft.get({ id: sharedDraftId })).resolves.toMatchObject({ name: 'Draft A' });
    await expect(tenantB.dbResource.draft.get({ id: sharedDraftId })).resolves.toMatchObject({ name: 'Draft B' });
    await expect(tenantB.dbResource.draft.get({ id: foreignDraftId })).resolves.toBeNull();
    await expect(tenantB.dbResource.draft.get({ id: UNKNOWN_ID })).resolves.toBeNull();
    await expect(tenantB.dbResource.draft.rename({ id: foreignDraftId, name: 'Denied' })).resolves.toBeNull();
    await expect(tenantB.dbResource.draft.rename({ id: UNKNOWN_ID, name: 'Denied' })).resolves.toBeNull();
    expect((await tenantA.dbResource.draft.list({ resourceId: sharedResourceId })).map((draft) => draft.id).sort())
      .toEqual([foreignDraftId, sharedDraftId].sort());
    expect((await tenantB.dbResource.draft.list({ resourceId: sharedResourceId })).map((draft) => draft.id))
      .toEqual([sharedDraftId]);

    await tenantA.dbResource.apply.create({ id: sharedApplyId, resourceId: sharedResourceId });
    await tenantB.dbResource.apply.create({ id: sharedApplyId, resourceId: sharedResourceId });
    await tenantA.dbResource.apply.update({ id: sharedApplyId, status: 'succeeded' });
    await tenantA.dbResource.apply.create({ id: foreignApplyId, resourceId: sharedResourceId });
    await expect(tenantA.dbResource.apply.get({ id: sharedApplyId })).resolves.toMatchObject({ resource_id: sharedResourceId });
    await expect(tenantB.dbResource.apply.get({ id: sharedApplyId })).resolves.toMatchObject({ resource_id: sharedResourceId });
    await expect(tenantB.dbResource.apply.get({ id: foreignApplyId })).resolves.toBeNull();
    await expect(tenantB.dbResource.apply.get({ id: UNKNOWN_ID })).resolves.toBeNull();
    await expect(tenantB.dbResource.apply.update({ id: foreignApplyId, status: 'failed' })).resolves.toBeNull();
    await expect(tenantB.dbResource.apply.update({ id: UNKNOWN_ID, status: 'failed' })).resolves.toBeNull();
    await expect(tenantA.dbResource.apply.get({ id: foreignApplyId })).resolves.toMatchObject({ status: 'preparing' });
    expect((await tenantA.dbResource.apply.list({ resourceId: sharedResourceId })).map((apply) => apply.id).sort())
      .toEqual([foreignApplyId, sharedApplyId].sort());
    expect((await tenantB.dbResource.apply.list({ resourceId: sharedResourceId })).map((apply) => apply.id))
      .toEqual([sharedApplyId]);
  });
});
