export { fnMapCapsuleHostError, fnMapCapsuleMountError } from './fn.error';

export {
  CAPSULE_MOUNT_ERROR_FORMAT,
  CapsuleHostError,
  CapsuleMemoryArtifactCache,
  createCapsuleHost,
  createDefaultCapsuleBrowserPlatform,
} from '@omnidraw/capsule';
export type {
  CapsuleArtifactCache,
  CapsuleArtifactCacheDiagnostics,
  CapsuleArtifactSource,
  CapsuleBrowserPlatform,
  CapsuleCapabilityBinding,
  CapsuleCapabilityRegistration,
  CapsuleDefaultBrowserPlatformOptions,
  CapsuleHandle,
  CapsuleHandleFreezeOptions,
  CapsuleHandleResumeOptions,
  CapsuleHost,
  CapsuleHostDiagnostics,
  CapsuleHostErrorCode,
  CapsuleHostRuntimePolicy,
  CapsuleMemoryArtifactCacheOptions,
  CapsuleMountDiagnostics,
  CapsuleMountErrorCategory,
  CapsuleMountErrorCode,
  CapsuleMountErrorEvent,
  CapsuleMountGuestChannels,
  CapsuleMountLifecycleEvent,
  CapsuleMountOptions,
  CapsulePlatformSupport,
  CapsuleSchemaRegistration,
  CapsuleSubscription,
  CapsuleTelemetryDiagnostics,
  CapsuleTelemetrySink,
  CapsuleViewport,
  CreateCapsuleHostOptions,
} from '@omnidraw/capsule';
