import { PRIVATE_OPERATION_MANIFEST } from '../apps/backend/src/shell/transport/operation-contract';

const outputPath = new URL(
  '../apps/frontend/src/core/app/private-operation-manifest.generated.ts',
  import.meta.url,
);

function quotedList(values: readonly string[]): string {
  return values.map((value) => `  ${JSON.stringify(value)},`).join('\n');
}

function quotedRecord(entries: readonly (readonly [string, string])[]): string {
  return entries.map(([key, value]) => `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`).join('\n');
}

export function renderPrivateOperationManifest(): string {
  const requests = PRIVATE_OPERATION_MANIFEST.filter((entry) => entry.mode === 'request');
  const streams = PRIVATE_OPERATION_MANIFEST.filter((entry) => entry.mode === 'stream');
  const idempotency = requests.flatMap((entry) => entry.idempotencyInputKey === null
    ? []
    : [[entry.path, entry.idempotencyInputKey] as const]);
  const cursors = streams.flatMap((entry) => entry.cursorInputKey === null
    ? []
    : [[entry.path, entry.cursorInputKey] as const]);
  return `/* Generated by scripts/generate-private-operation-manifest.ts. Do not edit. */

export const PRIVATE_REQUEST_PATHS = Object.freeze([
${quotedList(requests.map((entry) => entry.path))}
] as const);

export const PRIVATE_STREAM_PATHS = Object.freeze([
${quotedList(streams.map((entry) => entry.path))}
] as const);

export const PRIVATE_IDEMPOTENCY_INPUT_KEYS = Object.freeze({
${quotedRecord(idempotency)}
} as const);

export const PRIVATE_CURSOR_INPUT_KEYS = Object.freeze({
${quotedRecord(cursors)}
} as const);
`;
}

const expected = renderPrivateOperationManifest();
if (process.argv.includes('--write')) {
  await Bun.write(outputPath, expected);
} else {
  const actual = await Bun.file(outputPath).text();
  if (actual !== expected) {
    throw new Error('Frontend private operation manifest is stale. Run this script with --write.');
  }
}
