#!/usr/bin/env bun

/**
 * @file Generates FILES.md from workspace files and top-of-file JSDoc summaries.
 */

import { readdir } from "node:fs/promises"

const ROOT_URL = new URL("../", import.meta.url)
const OUTPUT_URL = new URL("../FILES.md", import.meta.url)
const ROOTS = ["scripts", "apps", "packages"] as const
const SKIPPED_DIRECTORIES = new Set(["node_modules", "dist", "assets", ".turbo", ".vite", "test", "tests"])
const SKIPPED_FILENAMES = new Set([".DS_Store"])
const TEXT_EXTENSIONS = new Set([
  ".css",
  ".cjs",
  ".html",
  ".js",
  ".json",
  ".jsx",
  ".md",
  ".mjs",
  ".mts",
  ".sh",
  ".ts",
  ".tsx",
])

type TFileEntry = {
  path: string
  jsdoc: string
}

async function main(): Promise<void> {
  const workspacePaths = await listWorkspacePaths()
  const entries = await Promise.all(
    workspacePaths.filter(shouldIncludePath).map(async (path) => ({
      path,
      jsdoc: await readFileJsdocSummary(path),
    })),
  )

  await Bun.write(OUTPUT_URL, renderMarkdown(entries))
}

async function listWorkspacePaths(): Promise<string[]> {
  const paths: string[] = []

  for (const root of ROOTS) {
    paths.push(...(await listFiles(root)))
  }

  return paths
}

async function listFiles(relativeDir: string): Promise<string[]> {
  const entries = await readdir(new URL(`${relativeDir}/`, ROOT_URL), { withFileTypes: true })
  const paths: string[] = []

  for (const entry of entries) {
    const relativePath = `${relativeDir}/${entry.name}`

    if (entry.isDirectory()) {
      if (SKIPPED_DIRECTORIES.has(entry.name)) {
        continue
      }

      paths.push(...(await listFiles(relativePath)))
      continue
    }

    if (entry.isFile() && !shouldSkipFile(entry.name)) {
      paths.push(relativePath)
    }
  }

  return paths
}

function shouldIncludePath(path: string): boolean {
  const parts = path.split("/")

  if (!ROOTS.some((root) => parts[0] === root)) {
    return false
  }

  if (parts.some((part) => part === "test" || part === "tests")) {
    return false
  }

  if (path.endsWith(".test.ts") || path.endsWith(".test.tsx")) {
    return false
  }

  if (path.endsWith(".tsbuildinfo")) {
    return false
  }

  return true
}

function shouldSkipFile(filename: string): boolean {
  return SKIPPED_FILENAMES.has(filename)
}

async function readFileJsdocSummary(path: string): Promise<string> {
  if (!isTextPath(path)) {
    return ""
  }

  const file = Bun.file(new URL(path, ROOT_URL))

  if (!(await file.exists())) {
    return ""
  }

  const text = await file.text()
  return getFileJsdocSummary(text)
}

function isTextPath(path: string): boolean {
  const extension = getExtension(path)
  return TEXT_EXTENSIONS.has(extension)
}

function getExtension(path: string): string {
  const filename = path.split("/").at(-1) ?? ""
  const dotIndex = filename.lastIndexOf(".")
  return dotIndex === -1 ? "" : filename.slice(dotIndex)
}

function getFileJsdocSummary(text: string): string {
  const withoutBom = text.replace(/^\uFEFF/, "")
  const withoutShebang = withoutBom.replace(/^#![^\n]*(?:\n|$)/, "")
  const leadingTrimmed = withoutShebang.trimStart()
  const blockMatch = leadingTrimmed.match(/^\/\*\*([\s\S]*?)\*\//)
  const hashBlockMatch = leadingTrimmed.match(/^#\s*\/\*\*([\s\S]*?)^#\s*\*\//m)

  if (blockMatch === null && hashBlockMatch === null) {
    return ""
  }

  const blockText = blockMatch?.[1] ?? hashBlockMatch?.[1].replace(/^\s*#\s?/gm, "") ?? ""
  const lines = blockText
    .split("\n")
    .map((line) => line.replace(/^\s*\*\s?/, "").trimEnd())
  const summaryLines: string[] = []
  let isCapturingFileTag = false

  for (const line of lines) {
    const trimmed = line.trim()

    if (trimmed.startsWith("@file") || trimmed.startsWith("@summary")) {
      isCapturingFileTag = true
      const tagText = trimmed.replace(/^@(file|summary)\b\s*:?\s?/, "").trim()

      if (tagText.length > 0) {
        summaryLines.push(tagText)
      }

      continue
    }

    if (trimmed.startsWith("@")) {
      if (isCapturingFileTag) {
        break
      }

      continue
    }

    if (isCapturingFileTag) {
      if (trimmed.length === 0) {
        break
      }

      summaryLines.push(trimmed)
      continue
    }

    if (trimmed.length > 0) {
      summaryLines.push(trimmed)
    } else if (summaryLines.length > 0) {
      break
    }
  }

  return normalizeTableText(summaryLines.join(" "))
}

function normalizeTableText(value: string): string {
  return value.replace(/\s+/g, " ").replace(/\|/g, "\\|").trim()
}

function renderMarkdown(entries: TFileEntry[]): string {
  const groupedEntries = groupEntries(entries)
  const lines = [
    "# FILE LIST",
    "",
    "Generated by `bun run scripts/generate-files-md.ts`.",
    "",
    "Only workspace files under `scripts/`, `apps/`, and `packages/` are included.",
    "Test folders (`test/`, `tests/`) and `*.test.ts` / `*.test.tsx` files are skipped.",
    "",
    "JSDoc convention for autoparsing:",
    "",
    "```ts",
    "/**",
    " * @file One sentence describing when to use this file.",
    " * @remarks Optional extra context for humans; ignored by this table.",
    " */",
    "```",
    "",
    "The generator reads the first top-of-file JSDoc block, preferring `@file` or `@summary` text.",
    "",
  ]

  for (const [section, sectionEntries] of groupedEntries) {
    lines.push(`## ${section}`, "", "| path | jsdocs |", "|---|---|")

    for (const entry of sectionEntries) {
      lines.push(`| [${entry.path}](${entry.path}) | ${entry.jsdoc} |`)
    }

    lines.push("")
  }

  return `${lines.join("\n").trimEnd()}\n`
}

function groupEntries(entries: TFileEntry[]): Map<string, TFileEntry[]> {
  const groups = new Map<string, TFileEntry[]>()
  const sortedEntries = [...entries].sort((left, right) => left.path.localeCompare(right.path))

  for (const entry of sortedEntries) {
    const section = getSection(entry.path)
    const sectionEntries = groups.get(section) ?? []
    sectionEntries.push(entry)
    groups.set(section, sectionEntries)
  }

  return groups
}

function getSection(path: string): string {
  const [root, name] = path.split("/")

  if (root === "scripts") {
    return "scripts"
  }

  return `${root}/${name}`
}

await main()
