import { afterEach, beforeEach, describe, expect, test } from 'bun:test';
import {
  DEFAULT_OSS_ACCOUNT_ID,
  DEFAULT_OSS_CELL_ID,
  DEFAULT_OSS_ORGANIZATION_ID,
} from '@vibecanvas/service-db/CONSTANTS';
import { DbServiceTurso } from '@vibecanvas/service-db/DbServiceTurso/DbServiceTurso';
import { fnFreezeTenantContext, type TTenantContext } from '@vibecanvas/tenant-core';
import type { TApiContext } from './context';
import { router } from './router';

const uuid = (value: number) => `20000000-0000-4000-8000-${String(value).padStart(12, '0')}`;

const ORG_B = uuid(1);
const ACCOUNT_B = uuid(2);
const SHARED_CANVAS_ID = uuid(10);
const FOREIGN_CANVAS_ID = uuid(11);
const SHARED_FILE_ID = uuid(20);
const FOREIGN_FILE_ID = uuid(21);
const SHARED_FILESYSTEM_ID = uuid(30);
const FOREIGN_FILESYSTEM_ID = uuid(31);
const SHARED_INSTANCE_ID = uuid(40);
const FOREIGN_INSTANCE_ID = uuid(41);
const UNKNOWN_ID = uuid(999);
const FOREIGN_DIGEST = 'a'.repeat(64);
const UNKNOWN_DIGEST = 'f'.repeat(64);

const tenantA = fnFreezeTenantContext({
  orgId: DEFAULT_OSS_ORGANIZATION_ID,
  accountId: DEFAULT_OSS_ACCOUNT_ID,
  cellId: DEFAULT_OSS_CELL_ID,
  placementEpoch: 1,
  roles: ['owner'],
  capabilities: ['*'],
  requestId: 'api-isolation-a',
});

const tenantB = fnFreezeTenantContext({
  ...tenantA,
  orgId: ORG_B,
  accountId: ACCOUNT_B,
  requestId: 'api-isolation-b',
});

type TCapabilityCalls = {
  automerge: TTenantContext[];
  filesystem: TTenantContext[];
  pty: TTenantContext[];
};

async function seedSecondTenant(service: DbServiceTurso): Promise<void> {
  const now = 1;
  await (await service.db.prepare(`
    INSERT INTO organizations (id, slug, name, status, created_at_ms, updated_at_ms)
    VALUES (?, 'tenant-b-api', 'Tenant B API', 'active', ?, ?)
  `)).run(ORG_B, now, now);
  await (await service.db.prepare(`
    INSERT INTO accounts (
      id, kind, display_name, status, is_autogenerated, created_at_ms, updated_at_ms
    ) VALUES (?, 'user', 'Tenant B API owner', 'active', 0, ?, ?)
  `)).run(ACCOUNT_B, now, now);
  await (await service.db.prepare(`
    INSERT INTO organization_memberships (
      org_id, account_id, role, status, is_billable_seat, created_at_ms, updated_at_ms
    ) VALUES (?, ?, 'owner', 'active', 1, ?, ?)
  `)).run(ORG_B, ACCOUNT_B, now, now);
}

async function rejectionSignature(action: Promise<unknown>): Promise<{ code: string | null; message: string }> {
  try {
    await action;
    throw new Error('Expected rejection.');
  } catch (error) {
    return {
      code: error !== null && typeof error === 'object' && 'code' in error
        ? String(error.code)
        : null,
      message: error instanceof Error ? error.message : String(error),
    };
  }
}

describe('API tenant authority forwarding', () => {
  let service!: DbServiceTurso;
  let calls!: TCapabilityCalls;

  function context(tenant: TTenantContext): TApiContext {
    return {
      tenant,
      db: service,
      automerge: {
        deleteDocument: async (receivedTenant: TTenantContext) => {
          calls.automerge.push(receivedTenant);
        },
      },
      filesystem: {
        homeDir: (receivedTenant: TTenantContext) => {
          calls.filesystem.push(receivedTenant);
          return '';
        },
      },
      pty: {
        list: (receivedTenant: TTenantContext) => {
          calls.pty.push(receivedTenant);
          return [];
        },
      },
    } as unknown as TApiContext;
  }

  beforeEach(async () => {
    service = new DbServiceTurso({
      databasePath: ':memory:',
      dataDir: import.meta.dir,
      cacheDir: import.meta.dir,
      silentMigrations: true,
    });
    await service.start();
    await seedSecondTenant(service);
    calls = { automerge: [], filesystem: [], pty: [] };

    await service.canvas.create(tenantA, {
      id: SHARED_CANVAS_ID,
      name: 'Canvas A',
      automerge_url: 'automerge:api-a',
    });
    await service.canvas.create(tenantB, {
      id: SHARED_CANVAS_ID,
      name: 'Canvas B',
      automerge_url: 'automerge:api-b',
    });
    await service.canvas.create(tenantA, {
      id: FOREIGN_CANVAS_ID,
      name: 'Canvas A only',
      automerge_url: 'automerge:api-a-only',
    });

    await service.file.create(tenantA, {
      id: SHARED_FILE_ID,
      hash: 'hash-a',
      mime_type: 'image/png',
      data: new Uint8Array([1]),
    });
    await service.file.create(tenantB, {
      id: SHARED_FILE_ID,
      hash: 'hash-b',
      mime_type: 'image/png',
      data: new Uint8Array([2]),
    });
    await service.file.create(tenantA, {
      id: FOREIGN_FILE_ID,
      hash: FOREIGN_DIGEST,
      mime_type: 'image/png',
      data: new Uint8Array([3]),
    });

    await service.filesystem.create(tenantA, {
      id: SHARED_FILESYSTEM_ID,
      name: 'Workspace',
      slug: 'workspace',
      path: 'host-capability-a',
      description: 'Tenant A',
    });
    await service.filesystem.create(tenantB, {
      id: SHARED_FILESYSTEM_ID,
      name: 'Workspace',
      slug: 'workspace',
      path: 'host-capability-b',
      description: 'Tenant B',
    });
    await service.filesystem.create(tenantA, {
      id: FOREIGN_FILESYSTEM_ID,
      name: 'Private workspace',
      slug: 'private-workspace',
      path: 'host-capability-a-only',
      description: null,
    });

    await service.toolGroup.create(tenantA, { name: 'Shared tools', json: null });
    await service.toolGroup.create(tenantB, { name: 'Shared tools', json: { svgIcon: '<svg>B</svg>' } });
    await service.toolGroup.create(tenantA, { name: 'Tenant A tools', json: null });

    await service.actor.insertDefinition(tenantA, {
      name: 'Shared actor',
      slug: 'shared-actor-a',
      url: null,
      description: 'A',
      manifest_path: 'actors/a/vibecanvas.json',
    });
    await service.actor.insertDefinition(tenantB, {
      name: 'Shared actor',
      slug: 'shared-actor-b',
      url: null,
      description: 'B',
      manifest_path: 'actors/b/vibecanvas.json',
    });
    const instance = (id: string, label: string) => ({
      id,
      canvas_id: SHARED_CANVAS_ID,
      element_id: `element-${label}`,
      actor_definition_name: 'Shared actor',
      filesystem_id: null,
      display_name: label,
      status: 'created' as const,
      machine_state: `state-${label}`,
      machine_context: { tenant: label },
    });
    await service.actor.insertInstance(tenantA, instance(SHARED_INSTANCE_ID, 'A'));
    await service.actor.insertInstance(tenantB, instance(SHARED_INSTANCE_ID, 'B'));
    await service.actor.insertInstance(tenantA, instance(FOREIGN_INSTANCE_ID, 'A-only'));
  });

  afterEach(async () => {
    await service.stop();
  });

  test('routes same-ID records and edge capabilities through the supplied tenant', async () => {
    const getCanvasA = router.api.canvas.get.callable({ context: context(tenantA) });
    const getCanvasB = router.api.canvas.get.callable({ context: context(tenantB) });
    expect((await getCanvasA({ params: { id: SHARED_CANVAS_ID } })).canvas[0]?.name).toBe('Canvas A');
    expect((await getCanvasB({ params: { id: SHARED_CANVAS_ID } })).canvas[0]?.name).toBe('Canvas B');

    const updateCanvasB = router.api.canvas.update.callable({ context: context(tenantB) });
    await updateCanvasB({ params: { id: SHARED_CANVAS_ID }, body: { name: 'Canvas B renamed' } });
    expect((await service.canvas.findById(tenantA, { id: SHARED_CANVAS_ID }))?.name).toBe('Canvas A');
    expect((await service.canvas.findById(tenantB, { id: SHARED_CANVAS_ID }))?.name).toBe('Canvas B renamed');

    const cloneFileB = router.api.file.clone.callable({ context: context(tenantB) });
    const cloned = await cloneFileB({ body: { url: `/files/${SHARED_FILE_ID}.png` } });
    const clonedId = cloned.url.slice('/files/'.length, -'.png'.length);
    expect(await service.file.getById(tenantA, { id: clonedId })).toBeNull();
    expect(await service.file.getById(tenantB, { id: clonedId })).toMatchObject({ hash: 'hash-b' });

    const getToolsA = router.api.tool.groups.get.callable({ context: context(tenantA) });
    const getToolsB = router.api.tool.groups.get.callable({ context: context(tenantB) });
    expect((await getToolsA({ name: 'Shared tools' })).json).toBeNull();
    expect((await getToolsB({ name: 'Shared tools' })).json).toEqual({ svgIcon: '<svg>B</svg>' });

    const listFilesystemsA = router.api.filesystem.listRegisteredFilesystems.callable({ context: context(tenantA) });
    const listFilesystemsB = router.api.filesystem.listRegisteredFilesystems.callable({ context: context(tenantB) });
    expect((await listFilesystemsA()).map(({ description, path }) => ({ description, path }))).toEqual([
      { description: 'Tenant A', path: '' },
      { description: null, path: '' },
    ]);
    expect((await listFilesystemsB()).map(({ description, path }) => ({ description, path }))).toEqual([
      { description: 'Tenant B', path: '' },
    ]);

    const homeB = router.api.filesystem.home.callable({ context: context(tenantB) });
    await expect(homeB({ filesystemId: SHARED_FILESYSTEM_ID })).resolves.toEqual({ path: '' });
    expect(calls.filesystem.at(-1)).toBe(tenantB);

    const listPtyB = router.api.pty.list.callable({ context: context(tenantB) });
    await expect(listPtyB({ filesystemId: SHARED_FILESYSTEM_ID, workingDirectory: '' })).resolves.toEqual([]);
    expect(calls.pty.at(-1)).toBe(tenantB);

    const snapshotA = router.api.actors.instances.snapshot.callable({ context: context(tenantA) });
    const snapshotB = router.api.actors.instances.snapshot.callable({ context: context(tenantB) });
    expect(await snapshotA({ instanceId: SHARED_INSTANCE_ID })).toMatchObject({ state: 'state-A', context: { tenant: 'A' } });
    expect(await snapshotB({ instanceId: SHARED_INSTANCE_ID })).toMatchObject({ state: 'state-B', context: { tenant: 'B' } });
  });

  test('makes known-foreign and unknown identifiers indistinguishable at APIs', async () => {
    const getCanvasB = router.api.canvas.get.callable({ context: context(tenantB) });
    expect(await rejectionSignature(getCanvasB({ params: { id: FOREIGN_CANVAS_ID } })))
      .toEqual(await rejectionSignature(getCanvasB({ params: { id: UNKNOWN_ID } })));

    const updateCanvasB = router.api.canvas.update.callable({ context: context(tenantB) });
    expect(await rejectionSignature(updateCanvasB({ params: { id: FOREIGN_CANVAS_ID }, body: { name: 'Denied' } })))
      .toEqual(await rejectionSignature(updateCanvasB({ params: { id: UNKNOWN_ID }, body: { name: 'Denied' } })));

    const removeCanvasB = router.api.canvas.remove.callable({ context: context(tenantB) });
    expect(await rejectionSignature(removeCanvasB({ params: { id: FOREIGN_CANVAS_ID } })))
      .toEqual(await rejectionSignature(removeCanvasB({ params: { id: UNKNOWN_ID } })));
    expect(calls.automerge).toEqual([]);
    expect(await service.canvas.findById(tenantA, { id: FOREIGN_CANVAS_ID })).not.toBeNull();

    const cloneFileB = router.api.file.clone.callable({ context: context(tenantB) });
    expect(await rejectionSignature(cloneFileB({ body: { url: `/files/${FOREIGN_FILE_ID}.png` } })))
      .toEqual(await rejectionSignature(cloneFileB({ body: { url: `/files/${UNKNOWN_ID}.png` } })));
    const removeFileB = router.api.file.remove.callable({ context: context(tenantB) });
    await expect(removeFileB({ body: { url: `/files/${FOREIGN_FILE_ID}.png` } })).resolves.toEqual({ ok: true });
    await expect(removeFileB({ body: { url: `/files/${UNKNOWN_ID}.png` } })).resolves.toEqual({ ok: true });
    expect(await service.file.getById(tenantA, { id: FOREIGN_FILE_ID })).not.toBeNull();
    expect(await rejectionSignature(cloneFileB({ body: { url: `/files/${FOREIGN_DIGEST}.png` } })))
      .toEqual(await rejectionSignature(cloneFileB({ body: { url: `/files/${UNKNOWN_DIGEST}.png` } })));
    expect(await rejectionSignature(removeFileB({ body: { url: `/files/${FOREIGN_DIGEST}.png` } })))
      .toEqual(await rejectionSignature(removeFileB({ body: { url: `/files/${UNKNOWN_DIGEST}.png` } })));

    const getToolsB = router.api.tool.groups.get.callable({ context: context(tenantB) });
    expect(await rejectionSignature(getToolsB({ name: 'Tenant A tools' })))
      .toEqual(await rejectionSignature(getToolsB({ name: 'Unknown tools' })));
    const removeToolsB = router.api.tool.groups.remove.callable({ context: context(tenantB) });
    expect(await rejectionSignature(removeToolsB({ name: 'Tenant A tools' })))
      .toEqual(await rejectionSignature(removeToolsB({ name: 'Unknown tools' })));
    expect(await service.toolGroup.getByName(tenantA, { name: 'Tenant A tools' })).not.toBeNull();

    const homeB = router.api.filesystem.home.callable({ context: context(tenantB) });
    expect(await rejectionSignature(homeB({ filesystemId: FOREIGN_FILESYSTEM_ID })))
      .toEqual(await rejectionSignature(homeB({ filesystemId: UNKNOWN_ID })));
    const listPtyB = router.api.pty.list.callable({ context: context(tenantB) });
    expect(await rejectionSignature(listPtyB({ filesystemId: FOREIGN_FILESYSTEM_ID, workingDirectory: '' })))
      .toEqual(await rejectionSignature(listPtyB({ filesystemId: UNKNOWN_ID, workingDirectory: '' })));
    expect(calls.filesystem).toEqual([]);
    expect(calls.pty).toEqual([]);

    const snapshotB = router.api.actors.instances.snapshot.callable({ context: context(tenantB) });
    expect(await rejectionSignature(snapshotB({ instanceId: FOREIGN_INSTANCE_ID })))
      .toEqual(await rejectionSignature(snapshotB({ instanceId: UNKNOWN_ID })));
  });
});
