export const WIDGET_RUNTIME_LOAD_CAPACITY_ERROR_CODE = 'WIDGET_RUNTIME_LOAD_CAPACITY';
export const WIDGET_RUNTIME_LOAD_CANCELLED_ERROR_CODE = 'WIDGET_RUNTIME_LOAD_CANCELLED';
export const WIDGET_RUNTIME_LOAD_TIMEOUT_ERROR_CODE = 'WIDGET_RUNTIME_LOAD_TIMEOUT';
