CREATE DOMAIN IF NOT EXISTS ACCOUTN_KIND AS TEXT
	DEFAULT 'user'
	NOT NULL
	CONSTRAINT account_kind_allowed CHECK (value IN ('user', 'service_account', 'system', 'anonymous'));
--> statement-breakpoint

CREATE DOMAIN IF NOT EXISTS ACCOUNT_ROLE AS TEXT
	DEFAULT 'member'
	NOT NULL
	CONSTRAINT account_role_allowed CHECK (value IN ('member', 'owner', 'admin', 'viewer'));
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS `accounts` (
	`id` TEXT PRIMARY KEY NOT NULL,
	`kind` ACCOUTN_KIND DEFAULT 'user' NOT NULL,
	`display_name` TEXT NOT NULL,
	`role` ACCOUNT_ROLE DEFAULT 'member' NOT NULL,
	`is_autogenerated` BOOLEAN DEFAULT true NOT NULL,
	`created_at` TIMESTAMP DEFAULT (datetime('now')) NOT NULL,
	`updated_at` TIMESTAMP DEFAULT (datetime('now')) NOT NULL
) STRICT;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS `accounts_display_name_unique` ON `accounts` (`display_name`);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS `accounts_role_idx` ON `accounts` (`role`);
--> statement-breakpoint
CREATE TRIGGER IF NOT EXISTS `accounts_updated_at_after_update`
AFTER UPDATE ON `accounts`
FOR EACH ROW
WHEN NEW.`updated_at` = OLD.`updated_at`
BEGIN
	UPDATE `accounts`
	SET `updated_at` = datetime('now')
	WHERE `id` = OLD.`id`;
END;
