SELECT __SELECTED__, COUNT(*) AS `violation_count`
FROM __CHILD_TABLE__ AS fk_child
WHERE __CHILD_VALUES_PRESENT__
  AND NOT EXISTS (
    SELECT 1
    FROM __PARENT_TABLE__ AS fk_parent
    WHERE __PARENT_MATCH__
  )
GROUP BY __CHILD_EXPRESSIONS__
