SELECT 1 AS violation
FROM __CHILD_TABLE__ AS __CHILD_ALIAS__
WHERE __CHILD_VALUES_PRESENT__
  AND NOT EXISTS (
    SELECT 1
    FROM __PARENT_TABLE__ AS __PARENT_ALIAS__
    WHERE __PARENT_MATCHES__
  )
LIMIT 1
