/** @file Complete built-in theme registrations. */

import type {
  ThemeId,
  TThemeDefinition,
  TThemeSrgbColor,
} from "@omnidraw/theme-contract";

export type {
  ThemeId,
  TThemeDefinition,
  TThemeSrgbColor as TCanvasThemeColor,
} from "@omnidraw/theme-contract";

export const THEME_ID_LIGHT = "light" satisfies ThemeId;
export const THEME_ID_DARK = "dark" satisfies ThemeId;
export const THEME_ID_SEPIA = "sepia" satisfies ThemeId;
export const THEME_ID_GRAPHITE = "graphite" satisfies ThemeId;
export const DEFAULT_THEME_ID = THEME_ID_LIGHT;

function color(hex: string, alpha = 1): TThemeSrgbColor {
  const normalized = hex.replace("#", "");
  if (!/^[0-9a-fA-F]{6}$/.test(normalized)) {
    throw new TypeError(`Expected a six-digit hex color, received '${hex}'`);
  }
  const channel = (offset: number) => (
    Number.parseInt(normalized.slice(offset, offset + 2), 16) / 255
  );
  return {
    space: "srgb",
    r: channel(0),
    g: channel(2),
    b: channel(4),
    a: alpha,
  };
}

const transparent = color("#000000", 0);

export const BUILTIN_THEMES = [
  {
    id: THEME_ID_LIGHT,
    label: "Light",
    appearance: "light",
    ui: {
      background: "#fafaf9",
      foreground: "#1c1917",
      card: "#f5f5f4",
      cardForeground: "#1c1917",
      popover: "#ffffff",
      popoverForeground: "#1c1917",
      muted: "#e7e5e4",
      mutedForeground: "#57534e",
      primary: "#f59e0b",
      primaryForeground: "#0c0a09",
      secondary: "#e7e5e4",
      secondaryForeground: "#1c1917",
      accent: "#fef3c7",
      accentForeground: "#78350f",
      destructive: "#dc2626",
      destructiveForeground: "#fafaf9",
      success: "#16a34a",
      successForeground: "#fafaf9",
      warning: "#d97706",
      warningForeground: "#0c0a09",
      border: "#d6d3d1",
      input: "#d6d3d1",
      ring: "#f59e0b",
      hover: "#e7e5e4",
      hoverForeground: "#1c1917",
      active: "#d6d3d1",
      activeForeground: "#1c1917",
      selected: "#fef3c7",
      selectedForeground: "#78350f",
      focusVisible: "#f59e0b",
      disabled: "#e7e5e4",
      disabledForeground: "#a8a29e",
    },
    canvas: {
      colors: {
        transparent: { fill: transparent },
        neutral: { fill: color("#d6d3d1"), ink: color("#1c1917") },
        red: { fill: color("#fca5a5"), ink: color("#b91c1c") },
        yellow: { fill: color("#fde047"), ink: color("#a16207") },
        green: { fill: color("#86efac"), ink: color("#15803d") },
        blue: { fill: color("#93c5fd"), ink: color("#1d4ed8") },
      },
      viewport: {
        background: color("#a8a29e", 0.10),
        gridMinor: color("#475569", 0.16),
        gridMajor: color("#475569", 0.28),
      },
      chrome: {
        selectionFill: "rgba(59, 130, 246, 0.12)",
        selectionStroke: "#3b82f6",
        groupBoundary: "#1e1e1e",
        debugText: "rgba(71, 85, 105, 0.80)",
        text: "#000000",
        textEditorOutline: "#3b82f6",
      },
      selection: {
        outline: color("#3b82f6"),
        handleFill: color("#ffffff"),
        handleStroke: color("#3b82f6"),
        handleSize: 10,
        rotateHandleOffset: 24,
        outlinePadding: 0,
      },
      path: {
        outline: color("#3b82f6"),
        anchorFill: color("#ffffff"),
        midpointFill: color("#93c5fd"),
        handleStroke: color("#3b82f6"),
        handleSize: 10,
        midpointSize: 8,
        rotateOffset: 24,
      },
    },
    terminal: {
      background: "#111214",
      foreground: "#e5e7eb",
      cursor: "#f59e0b",
      selectionBackground: "#374151",
      mutedForeground: "#9ca3af",
      errorForeground: "#fecaca",
      warningForeground: "#fcd34d",
      successForeground: "#86efac",
    },
  },
  {
    id: THEME_ID_DARK,
    label: "Dark",
    appearance: "dark",
    ui: {
      background: "#0c0a09",
      foreground: "#fafaf9",
      card: "#1c1917",
      cardForeground: "#fafaf9",
      popover: "#1c1917",
      popoverForeground: "#fafaf9",
      muted: "#292524",
      mutedForeground: "#a8a29e",
      primary: "#f59e0b",
      primaryForeground: "#0c0a09",
      secondary: "#292524",
      secondaryForeground: "#fafaf9",
      accent: "#44403c",
      accentForeground: "#fcd34d",
      destructive: "#ef4444",
      destructiveForeground: "#fafaf9",
      success: "#22c55e",
      successForeground: "#0c0a09",
      warning: "#fbbf24",
      warningForeground: "#0c0a09",
      border: "#292524",
      input: "#292524",
      ring: "#f59e0b",
      hover: "#292524",
      hoverForeground: "#fafaf9",
      active: "#44403c",
      activeForeground: "#fafaf9",
      selected: "#44403c",
      selectedForeground: "#fcd34d",
      focusVisible: "#f59e0b",
      disabled: "#292524",
      disabledForeground: "#78716c",
    },
    canvas: {
      colors: {
        transparent: { fill: transparent },
        neutral: { fill: color("#44403c"), ink: color("#fafaf9") },
        red: { fill: color("#7f1d1d"), ink: color("#f87171") },
        yellow: { fill: color("#713f12"), ink: color("#facc15") },
        green: { fill: color("#14532d"), ink: color("#4ade80") },
        blue: { fill: color("#1e3a8a"), ink: color("#60a5fa") },
      },
      viewport: {
        background: color("#0c0a09", 0.92),
        gridMinor: color("#94a3b8", 0.16),
        gridMajor: color("#94a3b8", 0.28),
      },
      chrome: {
        selectionFill: "rgba(96, 165, 250, 0.18)",
        selectionStroke: "#60a5fa",
        groupBoundary: "#e7e5e4",
        debugText: "rgba(214, 211, 209, 0.72)",
        text: "#fafaf9",
        textEditorOutline: "#60a5fa",
      },
      selection: {
        outline: color("#60a5fa"),
        handleFill: color("#1c1917"),
        handleStroke: color("#60a5fa"),
        handleSize: 10,
        rotateHandleOffset: 24,
        outlinePadding: 0,
      },
      path: {
        outline: color("#60a5fa"),
        anchorFill: color("#1c1917"),
        midpointFill: color("#1e3a8a"),
        handleStroke: color("#60a5fa"),
        handleSize: 10,
        midpointSize: 8,
        rotateOffset: 24,
      },
    },
    terminal: {
      background: "#111214",
      foreground: "#e5e7eb",
      cursor: "#f59e0b",
      selectionBackground: "#374151",
      mutedForeground: "#9ca3af",
      errorForeground: "#fecaca",
      warningForeground: "#fcd34d",
      successForeground: "#86efac",
    },
  },
  {
    id: THEME_ID_SEPIA,
    label: "Sepia",
    appearance: "light",
    ui: {
      background: "#f8f1e5",
      foreground: "#433422",
      card: "#f2e8d8",
      cardForeground: "#433422",
      popover: "#fff8ed",
      popoverForeground: "#433422",
      muted: "#eadcc7",
      mutedForeground: "#7c6549",
      primary: "#c17b2e",
      primaryForeground: "#fff8ed",
      secondary: "#eadcc7",
      secondaryForeground: "#433422",
      accent: "#f3e1b7",
      accentForeground: "#6a4518",
      destructive: "#b8573d",
      destructiveForeground: "#fff8ed",
      success: "#4f8a4b",
      successForeground: "#fff8ed",
      warning: "#b7791f",
      warningForeground: "#2a1c0c",
      border: "#d7c3a1",
      input: "#d7c3a1",
      ring: "#c17b2e",
      hover: "#eadcc7",
      hoverForeground: "#433422",
      active: "#d7c3a1",
      activeForeground: "#433422",
      selected: "#f3e1b7",
      selectedForeground: "#6a4518",
      focusVisible: "#c17b2e",
      disabled: "#eadcc7",
      disabledForeground: "#9b8468",
    },
    canvas: {
      colors: {
        transparent: { fill: transparent },
        neutral: { fill: color("#d7c3a1"), ink: color("#433422") },
        red: { fill: color("#dc9f89"), ink: color("#8c3f2b") },
        yellow: { fill: color("#dec97a"), ink: color("#8a5d16") },
        green: { fill: color("#9db37d"), ink: color("#365f34") },
        blue: { fill: color("#8caecc"), ink: color("#3d5975") },
      },
      viewport: {
        background: color("#d7c3a1", 0.20),
        gridMinor: color("#7c6549", 0.14),
        gridMajor: color("#7c6549", 0.24),
      },
      chrome: {
        selectionFill: "rgba(193, 123, 46, 0.16)",
        selectionStroke: "#c17b2e",
        groupBoundary: "#6b4f2d",
        debugText: "rgba(67, 52, 34, 0.68)",
        text: "#362718",
        textEditorOutline: "#c17b2e",
      },
      selection: {
        outline: color("#c17b2e"),
        handleFill: color("#fff8ed"),
        handleStroke: color("#c17b2e"),
        handleSize: 10,
        rotateHandleOffset: 24,
        outlinePadding: 0,
      },
      path: {
        outline: color("#c17b2e"),
        anchorFill: color("#fff8ed"),
        midpointFill: color("#ddb57b"),
        handleStroke: color("#c17b2e"),
        handleSize: 10,
        midpointSize: 8,
        rotateOffset: 24,
      },
    },
    terminal: {
      background: "#241d17",
      foreground: "#f6e7cf",
      cursor: "#d6a14d",
      selectionBackground: "#5d4630",
      mutedForeground: "#c7ad8b",
      errorForeground: "#f4a995",
      warningForeground: "#e4bc68",
      successForeground: "#a9c88a",
    },
  },
  {
    id: THEME_ID_GRAPHITE,
    label: "Graphite",
    appearance: "dark",
    ui: {
      background: "#111827",
      foreground: "#f3f4f6",
      card: "#1f2937",
      cardForeground: "#f3f4f6",
      popover: "#1f2937",
      popoverForeground: "#f3f4f6",
      muted: "#334155",
      mutedForeground: "#94a3b8",
      primary: "#f59e0b",
      primaryForeground: "#111827",
      secondary: "#334155",
      secondaryForeground: "#f3f4f6",
      accent: "#374151",
      accentForeground: "#fbbf24",
      destructive: "#f87171",
      destructiveForeground: "#111827",
      success: "#4ade80",
      successForeground: "#111827",
      warning: "#fbbf24",
      warningForeground: "#111827",
      border: "#374151",
      input: "#374151",
      ring: "#f59e0b",
      hover: "#334155",
      hoverForeground: "#f3f4f6",
      active: "#475569",
      activeForeground: "#f8fafc",
      selected: "#374151",
      selectedForeground: "#fbbf24",
      focusVisible: "#f59e0b",
      disabled: "#1f2937",
      disabledForeground: "#64748b",
    },
    canvas: {
      colors: {
        transparent: { fill: transparent },
        neutral: { fill: color("#334155"), ink: color("#f8fafc") },
        red: { fill: color("#7f1d1d"), ink: color("#fca5a5") },
        yellow: { fill: color("#a16207"), ink: color("#fde047") },
        green: { fill: color("#166534"), ink: color("#86efac") },
        blue: { fill: color("#1d4ed8"), ink: color("#93c5fd") },
      },
      viewport: {
        background: color("#0f172a", 0.92),
        gridMinor: color("#94a3b8", 0.16),
        gridMajor: color("#94a3b8", 0.30),
      },
      chrome: {
        selectionFill: "rgba(96, 165, 250, 0.18)",
        selectionStroke: "#60a5fa",
        groupBoundary: "#cbd5e1",
        debugText: "rgba(203, 213, 225, 0.72)",
        text: "#f3f4f6",
        textEditorOutline: "#60a5fa",
      },
      selection: {
        outline: color("#60a5fa"),
        handleFill: color("#1f2937"),
        handleStroke: color("#60a5fa"),
        handleSize: 10,
        rotateHandleOffset: 24,
        outlinePadding: 0,
      },
      path: {
        outline: color("#60a5fa"),
        anchorFill: color("#1f2937"),
        midpointFill: color("#1d4ed8"),
        handleStroke: color("#60a5fa"),
        handleSize: 10,
        midpointSize: 8,
        rotateOffset: 24,
      },
    },
    terminal: {
      background: "#0b1120",
      foreground: "#e5e7eb",
      cursor: "#f59e0b",
      selectionBackground: "#334155",
      mutedForeground: "#94a3b8",
      errorForeground: "#fecaca",
      warningForeground: "#fde047",
      successForeground: "#86efac",
    },
  },
] as const satisfies readonly TThemeDefinition[];
