/** @file Public ThemeService surface. */

export { ThemeService, type TThemeServiceArgs } from "./ThemeService.js";
export type {
  IThemeService,
  TThemeChangeListener,
  TThemeRegistryChangeListener,
  TThemeRememberedStyleChangeListener,
} from "./interface.js";
export {
  BUILTIN_THEMES,
  DEFAULT_THEME_ID,
  THEME_ID_DARK,
  THEME_ID_GRAPHITE,
  THEME_ID_LIGHT,
  THEME_ID_SEPIA,
} from "./builtins.js";
export type {
  ThemeId,
  TCanvasColorCode,
  TCanvasColorRole,
  TCanvasFillColorCode,
  TCanvasInkColorCode,
  TThemeAppearance,
  TThemeCanvasChrome,
  TThemeCanvasColorPalette,
  TThemeCanvasViewport,
  TThemeDefinition,
  TThemeDefinitionInheritance,
  TThemePathAppearance,
  TThemeRegistration,
  TThemeSelectionAppearance,
  TThemeSnapshot,
  TThemeSrgbColor,
  TThemeTerminalColors,
  TThemeUiColorRole,
  TThemeUiColors,
} from "@omnidraw/theme-contract";
export { fxGetThemeCssVariables, txApplyThemeToElement } from "./dom.js";
export {
  getThemeColorPickerPalette,
  getThemeColorValueMap,
  getThemeStyle,
  isThemeColorToken,
  resolveThemeCanvasColor,
  resolveThemeColor,
  themeSrgbColorToCss,
} from "./styles.js";
export {
  THEME_CORNER_RADIUS_OPTIONS,
  THEME_CORNER_RADIUS_VALUE_MAP,
  THEME_FONT_SIZE_OPTIONS,
  THEME_FONT_SIZE_VALUE_MAP,
  THEME_STROKE_STYLE_OPTIONS,
  THEME_STROKE_WIDTH_OPTIONS,
  THEME_STROKE_WIDTH_VALUE_MAP,
  THEME_STYLE_DEFAULTS_BY_SCOPE,
  THEME_TEXT_ALIGN_OPTIONS,
  THEME_VERTICAL_ALIGN_OPTIONS,
} from "./style.shared.js";
export {
  THEME_CORNER_RADIUS_NAMES,
  THEME_FONT_SIZE_NAMES,
  THEME_STROKE_STYLES,
  THEME_STROKE_WIDTH_NAMES,
  THEME_STYLE_SCOPE_IDS,
  THEME_TEXT_ALIGNS,
  THEME_VERTICAL_ALIGNS,
  type TCanvasThemeStyle,
  type TResolvedThemeCanvasStyle,
  type TThemeBuiltinStyleScopeId,
  type TThemeCanvasColorSwatch,
  type TThemeCanvasInkSwatch,
  type TThemeCanvasStyle,
  type TThemeColorPickerPalette,
  type TThemeColorValueMap,
  type TThemeCornerRadiusName,
  type TThemeCornerRadiusOption,
  type TThemeCornerRadiusToken,
  type TThemeCornerRadiusValueMap,
  type TThemeFontSizeName,
  type TThemeFontSizeOption,
  type TThemeFontSizeToken,
  type TThemeFontSizeValueMap,
  type TThemeRememberedStyle,
  type TThemeRememberedStyleMap,
  type TThemeStrokeStyle,
  type TThemeStrokeStyleOption,
  type TThemeStrokeWidthName,
  type TThemeStrokeWidthOption,
  type TThemeStrokeWidthToken,
  type TThemeStrokeWidthValueMap,
  type TThemeStyleDefaultsMap,
  type TThemeStyleScopeId,
  type TThemeTextAlign,
  type TThemeTextAlignOption,
  type TThemeTokenOption,
  type TThemeVerticalAlign,
  type TThemeVerticalAlignOption,
} from "./types.js";
